### ISSUE TITLE
Add Engineering Processes to Readme

### ISSUE THREAD

**Issue by smcgregor** [responsible-ai-collaborative/aiid#1013]
@Janetbananet created this documentation for our engineering process, which should be in the readme.

https://docs.google.com/document/d/1SMA6JNAGZI2brSpSt5RAJihhz-o1lYlPdHBIfL2sKcM/edit

Please comment on the doc if you have input. In the short term I may just add the doc as a link.

**Comment by lmcnulty** [comment]
This has been open for a week – it seems like nobody has any comments and this should just be added to the readme as-is?

**Comment by smcgregor** [comment]
Sounds good to me.
