### ISSUE TITLE
Too many similar incidents with large texts

### ISSUE THREAD

**Issue by LKchemposer** [responsible-ai-collaborative/aiid#1014]
[Incident 271](https://incidentdatabase.ai/cite/271) - Too many similar incidents with large title texts

<img width="1311" alt="image" src="https://user-images.githubusercontent.com/39468345/186735262-24c1e553-c69e-44ea-b10d-680e912764ea.png">

**Comment by smcgregor** [comment]
I think this is a case where the similar incident display needs to be more responsive

**Comment by lmcnulty** [comment]
This is fixed by #1016 in staging.
