### ISSUE TITLE
Bulleted Lists on Blog Posts are Broken

### ISSUE THREAD

**Issue by smcgregor** [responsible-ai-collaborative/aiid#1015]
See: https://incidentdatabase.ai/blog/using-ai-to-connect-ai-incidents

**Comment by LKchemposer** [comment]
Is it related to #999?

**Comment by lmcnulty** [comment]
Tailwind by default includes:

```css
ol,
ul {
 list-style:none;
 margin:0;
 padding:0
}
```

It apparently [wants you to use](https://tailwindcss.com/docs/list-style-type) `.list-disc` and `.list-decimal` to get bullets and numbers, respectively. It seems inconvenient to do that every time, though. Maybe someone should invent a language that would let us declaratively add `.list-disc` to every `ul`. Or maybe they could create a standardized set of components that would already include `.list-disc` in all the places where it fit the semantics. 🤔

Until someone invents such a technology, though, [we can just add](https://github.com/responsible-ai-collaborative/aiid/pull/1017) `ul, ol { list-style: revert; }`

**Comment by cesarvarela** [comment]
@smcgregor we'll have to hotfix https://github.com/responsible-ai-collaborative/aiid/pull/1017 because staging is not feeling well

https://github.com/responsible-ai-collaborative/aiid/pull/1009 is ready to be merged too:
