### ISSUE TITLE
Create a Gatsby schema customization to link Reports with Incidents

### ISSUE THREAD

**Issue by cesarvarela** [responsible-ai-collaborative/aiid#1035]
This will simplify querying Incidents and their Reports' data.

```
diff --git a/site/gatsby-site/gatsby-node.js b/site/gatsby-site/gatsby-node.js
index 924421bc..657d4f6c 100644
--- a/site/gatsby-site/gatsby-node.js
+++ b/site/gatsby-site/gatsby-node.js
@@ -190,6 +190,7 @@ exports.createSchemaCustomization = ({ actions }) => {
       editor_similar_incidents: [Int]
       editor_dissimilar_incidents: [Int]
       flagged_dissimilar_incidents: [Int]
+      reports: [mongodbAiidprodReports] @link(by: "report_number")
     }

     type mongodbAiidprodSubmissions implements Node {
@@ -203,6 +204,7 @@ exports.createSchemaCustomization = ({ actions }) => {
       tags: [String]
       plain_text: String
       embedding: reportEmbedding
+      report_number: [Int]
     }

     type mongodbAiidprodTaxaField_list implements Node {
```

**Comment by smcgregor** [comment]
@cesarvarela adding you on this one, but I think it might already be addressed in the many-to-many?

**Comment by cesarvarela** [comment]
This is more of a DX thing than anything else. In the long run, it will save development time, but it is a significant change that won't add any visible features.

It will make it possible to execute this query against Gatsby's auto-generated graphql endpoint: 

`{
  incident {
    title
    reports {
      report_number
      title
    }
  }
}`

This is not possible at the moment and forces us to query `incidents` and `reports` separately and to manually link them like it is being done here https://github.com/responsible-ai-collaborative/aiid/blob/master/site/gatsby-site/page-creators/createCitationPages.js#L44 and on several components.

I think It should be part of a future tech debt cleaning sprint, but it's not worth it if there are other higher-priority things.
