### ISSUE TITLE
Flowbite vs Tailwind UI

### ISSUE THREAD

**Issue by clari182** [responsible-ai-collaborative/aiid#1038]
We are still debating where to base our components from. The two candidates are [Flowbite](https://flowbite.com/docs/components) and [Tailwind UI](https://tailwindui.com/components).

@lmcnulty has made a great analysis regarding Flowbite:

> It seems slightly better than Bootstrap. Some thoughts:
> The light gray background for input elements is good – I think white-on-white makes the visual hierarchy less visible, especially combined with thin gray outlines. I think adding a .[inner-shadow](https://tailwindcss.com/docs/box-shadow#adding-an-inner-shadow) would help as well.
> I like that it uses box-shadow on the cards and in some other places.
> We have an [open issue](https://github.com/responsible-ai-collaborative/aiid/issues/889) concerning the popovers on the submission form, which I think will be solved by switching over since the [Flowbite popovers](https://flowbite.com/docs/components/popover/) seem to correctly remain visible on mouseover, which the ones we're currently using don't.
> The [buttons](https://flowbite.com/docs/components/buttons/) don't have an :active style -- the style applied on click is just :focus + :hover, or :focus alone on mobile. This seems like just throwing away built-in affordances for no reason. I think active:inner-shadow could serve to indicate when a button is depressed.
> The alternative button is the same color as the background and has a *very* thin and light border (which is for some reason lighter than the plain "Light" button style?). I don't love that, but I still like it better than the dark-gray Bootstrap secondary buttons which I just find ugly.
> The [colored shadow buttons](https://flowbite.com/docs/components/buttons/#colored-shadows) are a refreshing example of current fashions adding, rather than removing, physically-inspired affordances. I think we should use them all over the place.
> I think the [toasts](https://flowbite.com/docs/components/toast/) look worse than the ones we have currently – they're white with a colored icon, which I think communicates less than coloring the whole toast.

It would be helpful to analyze Tailwind UI, in the same manner, to choose the one to work with.

The idea is that once we choose one when using elements, we directly go to the component page and copy-paste the code. For example, if we need a card we would:
- Go to [Flowbite Card](https://flowbite.com/docs/components/card/), choose a Card
- Choose the card design we want
- Copy paste the code (with the tailwind classes)

**Comment by lmcnulty** [comment]
It seems like we've been moving forward with Flowbite – that seems good to me. I'm sorry I didn't get to this promptly: Tailwind UI and Flowbite seem quite similar from a usability perspective, and the most salient difference seemed to be that Tailwind has more free components.

**Comment by clari182** [comment]
Hey @lmcnulty ! I think flowbite is a good option too. Their documentation is good and straightforward. I'm going to create an issue to update the readme on how to use it.
