### ISSUE TITLE
Update to React 18

### ISSUE THREAD

**Issue by cesarvarela** [responsible-ai-collaborative/aiid#1058]
`flowbite-react` has a hard requirement of `react ^18` but `gatsby-theme-i18n` has a peer dependency set to `react ^17`. 

We'll need to add the `--legacy-peer-deps` flag back :/ (npm has an accepted rfc of a yarn-like `resolutions` setting https://github.com/npm/rfcs/blob/main/accepted/0036-overrides.md)

**Comment by smcgregor** [comment]
I think this one can be closed?
