### ISSUE TITLE
Issues in Staging

### ISSUE THREAD

**Issue by smcgregor** [responsible-ai-collaborative/aiid#1063]
Starting the list for the eventual deploy to production preview, since I am playing with staging at the moment.

- [x] The TSNE visualization is broken:

<img width="1070" alt="Screen Shot 2022-09-06 at 5 34 13 PM" src="https://user-images.githubusercontent.com/64780/188763370-70c55607-15e0-486c-b07a-5d17ac810286.png">

**Comment by smcgregor** [comment]
I think this covers everything. This should be ready to deploy, but there are a few items that will need addressing in short order.

- [ ] The accessibility of the incidents application is much higher in this layout, so the annoying design elements are of higher importance. The spinner below does not look good and should be updated. The table that is displayed after the data loads should also be updated to match the table display @cesarvarela is working with on his entity branch, but that will be an issue when the entity pages land.

![Screen Shot 2022-09-12 at 3 16 22 PM](https://user-images.githubusercontent.com/64780/189768213-9141d79f-bfd6-422c-8ca6-9f1e5dbb9407.png)

- [ ] Nothing on this page is translated, and the links all direct to the english language pages. https://staging-aiid.netlify.app/es/apps/incidents/
- [ ] The search box on the landing page should be changed to 1700 from 1600.
- [ ] Clicking on modals appears to be triggering a re-render on the underlying page: https://staging-aiid.netlify.app/apps/discover?display=details&hideDuplicates=1&page=1 Maybe 
- [ ] The flag report button on the Discover application modal is not rendering properly,

![Screen Shot 2022-09-12 at 3 27 57 PM](https://user-images.githubusercontent.com/64780/189769534-1d6f64b6-9981-4218-ab89-a95a0881ff01.png)

- [ ] The footer on mobile is not margined properly (I believe @lmcnulty has a branch for this one)
- [ ] This page has a 404 and it does not give a spinner while the table is loading. https://staging-aiid.netlify.app/apps/classifications/
- [ ] IMPORTANT but not blocking: the submission form has taken a big step backward in usability. I don't want to list all the issues with it here, but this needs attention. Whoever takes on this issue should likely better segment submitting new incidents+reports and new reports better. Many of the fields before the user gets to the incident number field are irrelevant if the user is submitting to an already existing incident. Some of the fields also need their instruction popover text. Aside from these, there are a large number of hot points in terms of dynamic content that jumps things around and produces a rather scary experience.
- [ ] Double stated title

![Screen Shot 2022-09-12 at 3 50 25 PM](https://user-images.githubusercontent.com/64780/189771915-c6838a67-065e-464b-a4e1-232dfb9baf3d.png)

- [ ] Many clicks in the nav appear to trigger a render of the logo in the upper left
- [ ] Email signup accounts are not verified email identities/accounts.
- [ ] The reset password email is for MongoDB (see below) and the image within that email is also broken

![Screen Shot 2022-09-12 at 3 55 00 PM](https://user-images.githubusercontent.com/64780/189772606-801282ac-d267-4a8c-adc5-f81e7da5285c.png)

**Comment by lmcnulty** [comment]
>  The footer on mobile is not margined properly (I believe @lmcnulty has a branch for this one)

#1078.

>  Double stated title

This is fixed in #1071, although that needs further design review.

>  IMPORTANT but not blocking: the submission form has taken a big step backward in usability.

This is addressed in #988, although it needs additional work.

**Comment by pdcp1** [comment]
> * [ ] Email signup accounts are not verified email identities/accounts.
> * [ ]  The reset password email is for MongoDB (see below) and the image within that email is also broken

I take these ones

**Comment by pdcp1** [comment]
@smcgregor Regarding Verification email and Password reset emails, the [documentation](https://www.mongodb.com/docs/atlas/app-services/authentication/email-password/#send-a-confirmation-email) says that they don't provide a way to customize the email's content, only the email subject, and the link URL.
<img width="790" alt="image" src="https://user-images.githubusercontent.com/6564809/189980353-013821e4-f5de-4baa-9980-a7cf64b50d04.png">


If we want to customize those emails, we have to create two functions:
- A function to send the verification email when a new Email user is registered
- A function to send the Password reset email

Both functions will use Sendgrid in order to customize and send both emails.
Let me know if it's worth doing.

**Comment by smcgregor** [comment]
@pdcp1 Any idea the effort cost?

**Comment by cesarvarela** [comment]
>  Many clicks in the nav appear to trigger a render of the logo in the upper left

This is because the `Layout` component is set at page level, it should be set one level above if we don't want re renders there, it could be done alongside this: https://github.com/responsible-ai-collaborative/aiid/issues/1059

**Comment by pdcp1** [comment]
> @pdcp1 Any idea the effort cost?

I estimate it in ~6 hs of effort for both functions

**Comment by smcgregor** [comment]
@pdcp1 Sounds good!

**Comment by clari182** [comment]
> [ ] Nothing on this page is translated, and the links all direct to the english language pages. https://staging-aiid.netlify.app/es/apps/incidents/

I'm fixing this one in PR #850 (adding both french and spanish to that page)

**Comment by smcgregor** [comment]
This issue list is for a prior staging, but it isn't closed so I will continue appending issues in the current staging. Unless I indicate otherwise, none of these issues will block deployment.

- [ ] The "Common Entities" panel on the landing page should be clickable in its entirety (e.g., the logo and the white space surrounding it should lead to the entity page)
- [ ] The relative size of text is off on the entities page:
<img width="780" alt="Screen Shot 2022-09-27 at 2 38 21 PM" src="https://user-images.githubusercontent.com/64780/192640824-91d1c8d1-a476-4231-a7d1-e59353a8a32f.png">
- [ ] The entity pages have two different types of cards (incidents and entities). The designs between them should be harmonized (consistent width properties, button affordances/more button, etc.)

(more from me soon)

**Comment by smcgregor** [comment]
- [ ] These both reference specific things that could be clickable, but only one of them is actually clickable. Either "Latest Incident Report" should be clickable (preferred) or "2. Facebook" should not be clickable.
<img width="391" alt="Screen Shot 2022-09-27 at 2 49 12 PM" src="https://user-images.githubusercontent.com/64780/192642403-ec087155-2092-4cbb-b074-a2268565056b.png">

**Comment by smcgregor** [comment]
- [ ] We have more than 1800 incident reports now and the landing page still says 1600.

**Comment by smcgregor** [comment]
- [ ] page jumps when the donut chart loads. I think it takes too long to load the data and produce the visualization and it negatively impacts UX. I think the query generating the donut chart needs to be run at build time and compressed to the data elements visualized.
<img width="1105" alt="Screen Shot 2022-09-27 at 3 28 45 PM" src="https://user-images.githubusercontent.com/64780/192648944-d7c2f1f2-6f17-4af9-a9db-bd20d1e68369.png">

**Comment by smcgregor** [comment]
- [ ] The donut charts shown in the carousel give a pointer type cursor when hovering it, but it is not actually clickable. I am not sure whether this was ever the case, but it should link to the filter on the discover application. In the absence of that linkage, it should not display the pointer.

**Comment by smcgregor** [comment]
- [ ] The citation page needs a block displaying the human written description of the incident.
- [ ] The edit page for reports gives no user feedback (e.g., spinner) while an update to the report is pending.

**Comment by smcgregor** [comment]
- [ ] **BUG** The review queue is fantastically broken in its display
<img width="1324" alt="Screen Shot 2022-09-27 at 3 48 04 PM" src="https://user-images.githubusercontent.com/64780/192651119-838efbdd-d5dd-4b94-99c1-4ffcc72f9197.png">

**Comment by smcgregor** [comment]
Nothing blocking, but if staging deploys, it will need to be deployed again within 24 hours to fix the review queue. I am done with my click testing. Lots of display improvements!

**Comment by cesarvarela** [comment]
@smcgregor, before merging, please remember to create the variables listed in the PR description

**Comment by smcgregor** [comment]
OK, should I deploy now after assigning those variables? This one? https://github.com/responsible-ai-collaborative/aiid/pull/1106

**Comment by cesarvarela** [comment]
It's that one, but there is one bug left that we found in `/apps/submitted`; it Should be ready soon; if not, we could do it while on tomorrow's call.

**Comment by smcgregor** [comment]
OK, I'll hold until you ping me.

**Comment by cesarvarela** [comment]
Looks like everything here has been either fixed or there is a separate incident for it
