### ISSUE TITLE
Typeset July and August Incident Report Blog Post

### ISSUE THREAD

**Issue by Janetbananet** [responsible-ai-collaborative/aiid#1069]
Here is the content:https://docs.google.com/document/d/174TZHgEh2VFtO0Xj7QSmS0srZpgpOUI4fTBLXB1YJmM/edit?usp=sharing

This will also need a Spanish translation.

**Comment by lmcnulty** [comment]
Also, was there a reason you sometimes linked to the report anchor in the incident page? Like this:

```markdown
07/18/2022: [Incident 285](/cite/285): Google Lens’s Camera Translation Feature Provided an Offensive Mistranslation of a Book Title in Korean

07/21/2022: [Incident 241](/cite/241#23r62de08405939a0bbe4a14784): Chess Robot Broke Child's Finger in Russia (5 reports)

07/24/2022: [Incident 271](/cite/271): Tesla Model 3 Sedan on Autopilot Killed Motorcyclist in a Rear Collision in Utah
```

**Comment by lmcnulty** [comment]
I went ahead and made a simple image to use for the thumbnail if we don't have anything else:

![aiid-july-august](https://user-images.githubusercontent.com/25443411/189366876-b2dc531b-da7f-488f-b72f-93f98e2b8aca.png)

**Comment by Janetbananet** [comment]
> Also, was there a reason you sometimes linked to the report anchor in the incident page? Like this:
> 
> ```gfm
> 07/18/2022: [Incident 285](/cite/285): Google Lens’s Camera Translation Feature Provided an Offensive Mistranslation of a Book Title in Korean
> 
> 07/21/2022: [Incident 241](/cite/241#23r62de08405939a0bbe4a14784): Chess Robot Broke Child's Finger in Russia (5 reports)
> 
> 07/24/2022: [Incident 271](/cite/271): Tesla Model 3 Sedan on Autopilot Killed Motorcyclist in a Rear Collision in Utah
> ```

I think that was just a copy/paste from the URL error, so please link to the main page. Thank you for catching that!

**Comment by Janetbananet** [comment]
> I went ahead and made a simple image to use for the thumbnail if we don't have anything else:
> 
> ![aiid-july-august](https://user-images.githubusercontent.com/25443411/189366876-b2dc531b-da7f-488f-b72f-93f98e2b8aca.png)

I like this! We're going to be doing this at the end of each month moving forward, so we can use this to help brand the monthly post.
