### ISSUE TITLE
Fix Facebook Login Setup Information

### ISSUE THREAD

**Issue by smcgregor** [responsible-ai-collaborative/aiid#1098]
`On Facebook Authentication settings, set the "Client ID" with the Facebook App Id. To get the Facebook App ID you should go to the [Facebook Developer Portal](https://developers.facebook.com/apps/), and check your app.`

The wording on this confused me for a while on which settings were being set where. I _think_ "Facebook Authentication settings" is referring to the secret in MongoDB, but I am still not sure.

Please re-work the documentation to be clearer and give more context. For instance, do I need to create a full Facebook organization and change the app mode from `Development` to `Live`?

**Comment by smcgregor** [comment]
Also, please @cesarvarela and @pdcp1 make sure that all these manual deployment changes are highlighted in the deployment pull request. I did not expect to be working this tonight.

**Comment by pdcp1** [comment]
@smcgregor You're right, in the documentation, I assume that the Facebook App is already created. Next time I will add more context and detailed instructions in the deployment PR.

To complete the FB integration we have to create another FB App. I created the FB Staging App using my personal Facebook account. If you give me your Facebook email user I can add you as an Administrator.

If you already have a Business account associated with AIID on Facebook, you should create an app under that Business.
If not, you can create an App using your personal Facebook user account.

In both cases, to create a new FB App you should go to https://developers.facebook.com/apps/create, click "Create App" > Select "Consumer" type

To help you in this process, please add me (pablocostapossamai@gmail.com) as an Administrator or Developer in the new FB App under the Roles FB app section (https://developers.facebook.com/apps/[appID]/roles/roles), so I can work on the setup on my side.

**Comment by pdcp1** [comment]
@smcgregor It says that if we are not friends on Facebook, you have to use the username to add a user as Administrator. Please try with `pablo.costa`

**Comment by smcgregor** [comment]
Done!

**Comment by pdcp1** [comment]
@smcgregor Great! I made the changes on the Facebook App, now we have to add the FB App secret value as a Realm App secret.

1. First, copy the **FB app secret** value from https://developers.facebook.com/apps/1313947142744767/settings/basic/
2. Go to Production Atlas App Service > Values
3. "Create new value" with name `facebookAppSecret`, type `Secret` and value = the **FB app secret** copied on step 1

<img width="1156" alt="image" src="https://user-images.githubusercontent.com/6564809/190713843-cc5689f1-1ce4-48ec-8cf3-e9680bd29f16.png">

4. Click "Save Draft"
5. Go to "Authentication" on the left-side menu
6. Select "Facebook"
7. Complete "Client ID" field with `1313947142744767`
8. On "Client Secret (Secret Name)", select  `facebookAppSecret` previously created
9. On "Redirect URIs" keep just the Production URL: `https://incidentdatabase.ai/logincallback`
10. The rest of the fields should be the same as this from Staging:

<img width="741" alt="image" src="https://user-images.githubusercontent.com/6564809/190716975-155b5129-187e-401d-a309-7d0872d455a5.png">

11. Click "Save Draft"
12. And confirm the deploy 🚀

**Comment by smcgregor** [comment]
Updated per above! Successfully deployed the Realm app.

Please note, the `Client ID` field previously had `353371620329953`. If this config is deploying from Realm config, the value may get changed in production the next time we merge staging in. I believe this is likely the case.

**Comment by pdcp1** [comment]
@smcgregor Great thanks!

Regarding the `Client ID` field, you're right, that value is part of the `providers.json` and unfortunately, it cannot be parametrizable.
We already discussed this with Cesar and we decided to update that Client ID on `providers.json` with the Production value, so that next time we deploy Staging to Prod it won't break the Production Facebook login.
If we need to log to Staging with Facebook we can change that value manually from the Realm UI.

**Comment by cesarvarela** [comment]
If this becomes a problem, we could store these ids in env variables and update the JSON files with `jq` or similar before doing `realm-cli push.`

**Comment by pdcp1** [comment]
@smcgregor can you give me access (or send me log file content) for this log https://realm.mongodb.com/groups/5d3353e1014b761468e4cee4/apps/5d3a950966a7dfbe51bcda7f/logs?co_id=632a1112789576db73925cb0 ?
It's from Production Realm

**Comment by smcgregor** [comment]
```AuthError Error | Sep 20 12:14:26-07:00 | 14ms | Authenticationlogin | oauth2-facebook | -- | 632a1112789576db73925cb0
-- | -- | -- | -- | -- | -- | --
Error:state presented does not match expectedRemote IP Address:186.52.105.183

AuthError Error
Sep 20 12:14:26-07:00
14ms
Authenticationlogin
oauth2-facebook
--
[632a1112789576db73925cb0](https://realm.mongodb.com/groups/5d3353e1014b761468e4cee4/apps/5d3a950966a7dfbe51bcda7f/logs?co_id=632a1112789576db73925cb0)
Error:

state presented does not match expected
Remote IP Address:
186.52.105.183```

**Comment by pdcp1** [comment]
Closing this since Facebook Login is currently working on production site
