### ISSUE TITLE
Add Login, Sign up and Logout buttons

### ISSUE THREAD

**Issue by pdcp1** [responsible-ai-collaborative/aiid#1107]
The login and sign-up functionality were released. We need to add the Login, Sign up, and Logout buttons/links somewhere in the design.

- The Login button should redirect to `/login`
- The Sign-up button should redirect to `/signup`
- The Logout button should redirect to `/logout`

I think we can add them in the top header or in the left-side menu.

@clari182 @lmcnulty Feel free to assign this issue to you since you have better UX/UI design expertise to decide where and how these buttons/links.

**Comment by clari182** [comment]
@pdcp1 I'll take it!
