### ISSUE TITLE
Edit Submission view issues

### ISSUE THREAD

**Issue by LKchemposer** [responsible-ai-collaborative/aiid#1111]
This is the `Edit Submission` view for an incident that already has an assigned `incident id`. Description, alleged developer, deployer, harmed parties should not appear, or be automatically populated, preferably hidden

![image](https://user-images.githubusercontent.com/39468345/190959670-521f01e5-9ae5-4748-af9f-91dfba57ac81.png)

**Comment by LKchemposer** [comment]
Also, there is no "Incident title" field. There is only the "Report title" field (i.e., `Title`)

**Comment by LKchemposer** [comment]
Could we hot fix the issue of requiring description and alleged parties for already id-assigned reports? I'm currently refraining from ingesting these, because I don't want incident metadata to be overwritten, if there's a chance of that

**Comment by LKchemposer** [comment]
Please also add `Editors` field to the window. It will save me considerable effort pulling up the Table View and manually change the editor for each incident.

**Comment by smcgregor** [comment]
I promoted this issue to `critical` because it is currently blocking the ingestion of any report associated with a currently existing incident. The problem is that when you edit a report in the submission queue, you are forced to fill in the incident details (entities, description, title) and these entries will overwrite the details found in the incident collection upon ingestion. The expected behavior here should be that these form elements should not be set-able if/when the incident ID is assigned in the form. They may be displayed as the current value if it is populated from the incidents collection, but this would be an added feature and those values should then not be editable.

**Comment by LKchemposer** [comment]
I want to confirm that #1166 would also fix the issue in **editor** submission form as well, and not only the submitter submission form.

**Comment by LKchemposer** [comment]
@cesarvarela the new deployment fixed the alleged `deployer`, `developer`, and `harmed parties`, but `description` should also treated the same – i.e., hidden with the description text already filled in, or else it'd be overwritten (attached image).

also, i'd appreciate greatly if there's also an `editor` and **incident** `title` field in the editor submission form too; these should not be available for submitters, but only for editors – it will save me considerable effort pulling up the Table View and manually change them for each incident. i'm happy to submit a separate issue for this if needed.

<img width="831" alt="image" src="https://user-images.githubusercontent.com/39468345/193203323-13935fad-43b9-47b6-8479-ea461cca9fb7.png">

**Comment by lmcnulty** [comment]
I'm kind of unsure about how descriptions are supposed to work. While the "alleged ..." fields only exist on the incident, both incidents and reports currently have a description field. So just based on the shape of the data, I would expect the submission to contain the description of the report, not the incident. But I don't really understand why reports have their own descriptions – do we use them anywhere? How many of the just restate the incident description? In any case, it seems like if they both have them, then the incident description on the submission form should be an editor-only field like you're proposing for the incident title.

**Comment by LKchemposer** [comment]
I am not aware of any use of `report description`, the only description I am aware of is the `incident description`. I don't believe reports need description, only incidents do. Description should only be a metadata at the incident level, like the allegedly parties.

**Comment by lmcnulty** [comment]
They're in [the schema](https://github.com/responsible-ai-collaborative/aiid/blob/master/site/realm/data_sources/mongodb-atlas/aiidprod/reports/schema.json#L27), and they exist on at least some reports:

![image](https://user-images.githubusercontent.com/25443411/193319921-953dd027-e68d-4d8a-81a0-956ada8e21ee.png)

**Comment by smcgregor** [comment]
`description` on reports used to be a short version of the text (i.e., for previewing the contents). I believe it is close to deprecated at this point, but it is still around. Users should not see it at this point. I think I gave @clari182 some text for the UI to describe `description` on incidents.

**Comment by LKchemposer** [comment]
interesting. welp, I didn't know that that existed. @lmcnulty, have the recent descriptions been added as `report` descriptions or `incident` descriptions? I know that it shows up on incident Table View so it definitely is added at the `incident` level, but I'm not sure if it's been added simultaneously at the `report` level

**Comment by lmcnulty** [comment]
It seems like on all recent reports, the `description` is just the first $n$ characters of the text, so I don't think the submission descriptions get copied to the reports.
