### ISSUE TITLE
New submission form issues

### ISSUE THREAD

**Issue by LKchemposer** [responsible-ai-collaborative/aiid#1112]
1. "Report description" should be "incident description". The distinction here is relevant because we need submitters to give info about the incident central to the report, not describe the report itself.
2. Description and alleged-parties fields should be hidden or automatically populated when an `incident id` is assigned, preferably hidden. Otherwise, would they create conflict with the existing filled-in fields if they get ingested in the database?
3. Description limit needs to be longer. It is currently set at 200 characters, many of existing descriptions are longer than that. Please set it at 500 at least.
4. Please give some cues about which fields are mandatory and which are not

**Comment by cesarvarela** [comment]
Have you tried this one: https://staging-aiid.netlify.app/apps/submit ? Would like to hear your thoughts.

**Comment by LKchemposer** [comment]
Love the staging submit form! A few things:
1. "Report description" should be "incident description," and higher character limit for it, per above
3. If we haven't rolled out tags (officially), not sure if we should hide it
4. The "press Enter to begin new item" mechanic for the alleged parties is not intuitive for me, although it is the same mechanic in the "incident table." Is it possible to make `,` as the button to separate item instead? This is also for the `authors` field since in many cases, authors are copy-pasted in with `,` and it would take a bit of effort to press Enter for each author to register them in.
5. I really like the dropdown with the "Tell us more" text. "Tell us more about the incident ... " can be good for clarity, but may not be necessary.

**Comment by LKchemposer** [comment]
Also, a minor ask (optional): if you could put the `alleged deployer` field before/above `alleged developer` field, that would help me so much. I've recently run into issues where I put the wrong entities in, because I was in a flow state and I got used to the workflow of deployer-before-developer of the incident table.
