### ISSUE TITLE
Build crashing nightmare

### ISSUE THREAD

**Issue by cesarvarela** [responsible-ai-collaborative/aiid#1140]
When trying to get the build working with the new language, I've seen a myriad of different errors:

- 1

![image](https://user-images.githubusercontent.com/1172479/191852457-98df947f-4b6d-4f3c-9fa6-455bcf8ccc92.png)

- 2

![image](https://user-images.githubusercontent.com/1172479/191854143-0afeffc2-c7d6-4b10-baa0-8f478b2dd394.png)

Some people have the same issue here:

https://github.com/gatsbyjs/gatsby/issues/35018#issuecomment-1209608857

- 3 Netlify is just killing the process with no helpful error message

![image](https://user-images.githubusercontent.com/1172479/191854657-f818f7e6-1234-4a55-9c42-f2b0b80e8984.png)

- 4 (not an error but a warning about having many pages)

![image](https://user-images.githubusercontent.com/1172479/191856358-b4d0cce9-5b5c-401c-8855-73c96ee12571.png)

And more ...

My guesses on why this is happening:

- images are too big (hopeful death within  #1134) 
- we are querying too much data at once
  - `text` field of an incident with many reports
  - too many pages overall for the netlify box to handle (`fr` adds 1k gatsby nodes,) 
  - wordcounts page is too big
- there is a memory leak somewhere in the build process
- we are simply reaching the Netlify box's limits (number of pages? ram used? artifacts size?)
...

**Comment by cesarvarela** [comment]
Removing cypress' screenshot & video capturing seems to improve consistency a lot 🤔

**Comment by cesarvarela** [comment]
Let's see if we get some answers: https://answers.netlify.com/t/build-crashing-is-a-3k-pages-site-considered-big/76338

**Comment by cesarvarela** [comment]
Another page to this diary, disabling Cypress allows the build to run much faster https://github.com/responsible-ai-collaborative/aiid/pull/1171 and leaves room to have French  enabled: https://staging--cesarvarela-staging.netlify.app/fr/

**Comment by TRegourd** [comment]
I am also experiencing it, randomly. It's a shame because my site is supposed to rebuild automatically on a certain interval, but one time in two I have to clear cache and relaunch the build myself ...

**Comment by cesarvarela** [comment]
`GATBSY_CPU_COUNT=2` fixed the remaining issues, and it is currently documented.
