### ISSUE TITLE
Cloudinary image component crashing randomly

### ISSUE THREAD

**Issue by cesarvarela** [responsible-ai-collaborative/aiid#1143]
![image](https://user-images.githubusercontent.com/1172479/191860402-fe5b6ad9-d8d9-4d23-a3e0-28a877ba7138.png)

I think that the component is a little bit over-engineered, could be worth updating the Cloudinary React library and using as much as possible of their code, including their built-in fallback handling.

**Comment by smcgregor** [comment]
Is anyone still experiencing this? Please reopen.
