### ISSUE TITLE
Plot of incident growth

### ISSUE THREAD

**Issue by smcgregor** [responsible-ai-collaborative/aiid#1156]
We have seen a good amount of growth in the number of indexed incidents and the total number of reports. This is a valuable metric for the pace of the database and the growth of the incident reporting community. We need a plot with time on the x axis and the y axis should have the cumulative number of reports added to the AIID. Either on a second chart, or as a second series on the same plot, there should also be a line for the number of incidents within the AIID through time. In both instances, the time variable is determined by the reports, which includes a field for the submission date. It will be necessary to infer when an incident was first reported on the basis of that submission date.

**Comment by cesarvarela** [comment]
@lmcnulty, please use d3. We should have also used it for TSNE viz.
