### ISSUE TITLE
Disable Netlify Forms post-processing

### ISSUE THREAD

**Issue by cesarvarela** [responsible-ai-collaborative/aiid#1172]
Netlify has a feature that parses all generated HTML looking for forms and then does some magic to capture when such forms are submitted. We are not using that, which negatively affects build/deploy times.

Form detection should be set to `disabled`:

![image](https://user-images.githubusercontent.com/1172479/192873517-9649d28d-e01a-44cb-bfae-27a8c310c826.png)

@smcgregor

**Comment by smcgregor** [comment]
You made this change in staging/I should make the change in production?

**Comment by cesarvarela** [comment]
Yes, it is disabled in staging and should be disabled in production too.

**Comment by smcgregor** [comment]
Done. Closing this.
