### ISSUE TITLE
Put the `alleged deployer` field before/above `alleged developer` field

### ISSUE THREAD

**Issue by cesarvarela** [responsible-ai-collaborative/aiid#1175]
Also, a minor ask (optional): if you could put the `alleged deployer` field before/above `alleged developer` field, that would help me so much. I've recently run into issues where I put the wrong entities in, because I was in a flow state and I got used to the workflow of deployer-before-developer of the incident table. (a classic case of UX design influences behaviors)

_Originally posted by @LKchemposer in https://github.com/responsible-ai-collaborative/aiid/issues/1112#issuecomment-1254735968_

**Comment by LKchemposer** [comment]
Thank you so much, @cesarvarela!

**Comment by cesarvarela** [comment]
@clari182 you should incorporate this in the new submit form too
