### ISSUE TITLE
Page jumps when the donut chart loads

### ISSUE THREAD

**Issue by cesarvarela** [responsible-ai-collaborative/aiid#1177]
- [ ] page jumps when the donut chart loads. I think it takes too long to load the data and produce the visualization and it negatively impacts UX. I think the query generating the donut chart needs to be run at build time and compressed to the data elements visualized.
<img width="1105" alt="Screen Shot 2022-09-27 at 3 28 45 PM" src="https://user-images.githubusercontent.com/64780/192648944-d7c2f1f2-6f17-4af9-a9db-bd20d1e68369.png">

_Originally posted by @smcgregor in https://github.com/responsible-ai-collaborative/aiid/issues/1063#issuecomment-1260141144_

**Comment by cesarvarela** [comment]
This is mentioned over there too:

The donut charts shown in the carousel give a pointer type cursor when hovering it, but it is not actually clickable. I am not sure whether this was ever the case, but it should link to the filter on the discover application. In the absence of that linkage, it should not display the pointer.

**Comment by lmcnulty** [comment]
@cesarvarela I'm including the fix for this in #1067.
