### ISSUE TITLE
Gmail thinks notifications are in Catalan

### ISSUE THREAD

**Issue by smcgregor** [responsible-ai-collaborative/aiid#1183]
It wants me to translate the message for some reason. Maybe a config setting somewhere? Also, is there something we get out of wrapping the URLs in SendGrid addresses?

<img width="690" alt="Screen Shot 2022-09-29 at 12 22 09 AM" src="https://user-images.githubusercontent.com/64780/192966560-bcabfc5e-2522-477c-9337-bcb055d63a38.png">

**Comment by pdcp1** [comment]
Regarding the translation suggestion to Catalan, it never happened to me on my personal Gmail and neither to my company Gmail account. It looks like a Gmail issue, not something related to Sendgrid configuration or the email content itself.

According to this [post](https://litmus.com/community/discussions/7028-gmail-mis-translating-our-english-only-emails-into-other-languages), it happens sometimes for no reason. Even if they specify the email language using the `lang` attribute on the `<html>` tag:

<img width="194" alt="image" src="https://user-images.githubusercontent.com/6564809/193073512-e76c134e-e9a2-47a4-9615-df8c762865f6.png">

Sendgrid doesn't add that attribute to the email templates, but I have tested with a custom email with the lang attribute set to French `<html lang="fr">` and Gmail still infer the email language based on the email content (English), which is correct.

**Comment by pdcp1** [comment]
@smcgregor Sendgrid wraps the email links into sendgrid.net domain to allow email tracking analytics (open rate and email link tracking for example.
To link branding, we need to do this https://docs.sendgrid.com/ui/account-and-settings/how-to-set-up-link-branding

It's easy. Basically, you need to add two more records to our Netlify DNS. In the same way that you did before for the sender domain validation.
I just sent you the instructions by email, but I put the records here for a quick reference:

TYPE | HOST | VALUE 
-- | -- | -- 
CNAME | url3236.incidentdatabase.ai | sendgrid.net 
CNAME | 28653340.incidentdatabase.ai | sendgrid.net

Please let me know when you finish so I can click on "Verify"

**Comment by smcgregor** [comment]
Finished!

**Comment by pdcp1** [comment]
Done! Now all email tracking links are under `incidentdatabase.ai` domain.
I just tested and it works correctly 👍 

<img width="1156" alt="image" src="https://user-images.githubusercontent.com/6564809/193093249-0bdd12d9-3da6-42f9-b82f-d70d0c0715ea.png">

We are good to close this issue.
