### ISSUE TITLE
Pull Entity information from Wikidata

### ISSUE THREAD

**Issue by lmcnulty** [responsible-ai-collaborative/aiid#1191]
> I like how iNaturalist pulls in content from Wikipedia for its species pages. Ideally we could do something very similar for our entities pages in the future and have a lot more details on the entities. That will take work beyond this particular issue though.

_Originally posted by @smcgregor in https://github.com/responsible-ai-collaborative/aiid/issues/1132#issuecomment-1255341532_

---

In particular, I think it would be useful to pull logos and descriptions. 

We might be able to integrate incident data as well. Incident 1 has a [Wikipedia page](https://en.wikipedia.org/wiki/Elsagate) and a [Wikidata node](https://www.wikidata.org/wiki/Q43376553). It might be the only incident for which this is the case, however.

**Comment by smcgregor** [comment]
This is a good idea, but I think it is going to take too much time (editor and developer) to get done short term. I am going to close the issue for now, but likely return to it in >1 year.
