### ISSUE TITLE
Entity adjective order

### ISSUE THREAD

**Issue by lmcnulty** [responsible-ai-collaborative/aiid#1203]
Some of the Facebook-related entities have an awkward ordering of adjectives.

- [Facebook female users](https://incidentdatabase.ai/entities/facebook-female-users) → Female Facebook Users
- [Facebook black users](https://incidentdatabase.ai/entities/facebook-black-users) → Black Facebook Users
- [Facebook male users](https://incidentdatabase.ai/entities/facebook-male-users) → Male Facebook Users

[Wikipedia says](https://en.wikipedia.org/wiki/Adjective#Order) that adjectives are ordered as follows 

> 1.  Opinion – limiter adjectives (e.g. a _real_ hero, a _perfect_ idiot) and adjectives of subjective measure (e.g. _beautiful_, _interesting_) or value (e.g. _good_, _bad_, _costly_)
> 2.  Size – adjectives denoting physical size (e.g. _tiny_, _big_, _extensive_)
> 3.  Shape or physical quality – adjectives describing more detailed physical attributes than overall size (e.g. _round_, _sharp_, _swollen_, _thin_)
> 4.  Age – adjectives denoting age (e.g. _young_, _old_, _new_, _ancient_, _six-year-old_)
> 5.  Colour – adjectives denoting colour or pattern (e.g. _white_, _black_, _pale_, _spotted_)
> 6.  Origin – denominal adjectives denoting source (e.g. _Japanese_, _volcanic_, _extraterrestrial_)
> 7.  Material – denominal adjectives denoting what something is made of (e.g., _woollen_, _metallic_, _wooden_)
> 8.  Qualifier/purpose – final limiter, which sometimes forms part of the (compound) noun (e.g., _rocking_ chair, _hunting_ cabin, _passenger_ car, _book_ cover

I think that when the noun specifies an actor (such as a "user"), the adjective specifying the object of the action (such as "Facebook") would be ranked 7.5 on the above list. Analogous examples:

- ```
  "young encyclopedia salesman" not "encyclopedia young salesman"
     4       7.5                         7.5        4
  ```
- ```
  "robot first-grade teacher" not "first-grade robot teacher"
     7       7.5                      7.5        7
  ```

- ```
  "robot 12th-grade driving instructor" not "robot driving 12th-grade instructor"
     7      7.5        8                       7      8       7.5
  ```



  - "12th-grade robot driving instructor" sounds OK, but it means a robot driving instructor in 12th grade, not a robot who teaches driving to students in 12th grade.

**Comment by LKchemposer** [comment]
thanks! agreed, it sounds awkward

change all instances to:
- [ ] female Facebook users
- [ ] male Facebook users
- [ ] Black Facebook users
