### ISSUE TITLE
Include specific harmed entities in common entity cards

### ISSUE THREAD

**Issue by lmcnulty** [responsible-ai-collaborative/aiid#1211]
Currently, the common entity cards say "allegedly harming \<however many\> entities." I find those counts kind of underwhelming because it's not immediately clear what the scale of an "entity" is. I mean, Facebook is used by a billion "entities": shouldn't they be harming at least a couple million?

![image](https://user-images.githubusercontent.com/25443411/194156687-529bc411-8389-43f3-b822-08e7aff8c937.png)

If it's not too spicy, it might help to add top the few harmed entities (by number of incidents) inline. So for instance "Tesla... allegedly harming motorists, Tesla drivers, and 37 other entities." For Google I think it would be "allegedly harming women, minority groups, and 24 other entities," which... yeah, pretty spicy. If that's too much, maybe we could whitelist some harmed entities that could communicate what an "entity" is without provoking as much visceral outrage. E.g. "Allegedly harming {motorists, Illinois residents, small businesses}". Or maybe we could list a few incidents along with the alleged harmed entities – that would make it more clear that we're recording what other people reported, not accusing anyone directly. It would require more change to the card design, though.

**Comment by smcgregor** [comment]
In the future we are going to incentivize providing incident responses by more prominently displaying incidents for which we have no incident responses from the entities involved. I think we should view the "spice" here similarly and roll it into that effort.

**Comment by smcgregor** [comment]
I am going to close this here in favor of: https://github.com/responsible-ai-collaborative/aiid/issues/1437
