### ISSUE TITLE
Menu on Table View – Oversized button texts & icons

### ISSUE THREAD

**Issue by LKchemposer** [responsible-ai-collaborative/aiid#1221]
Oversized `Submit` and `Discover` button text and icons when opening the Menu from Table View

<img width="455" alt="image" src="https://user-images.githubusercontent.com/39468345/194595484-e13c4523-ec61-444b-b6d7-d2a2eb8f1db5.png">

**Comment by lmcnulty** [comment]
I've also noticed this happening when a modal is open. It's very strange.
