### ISSUE TITLE
`Your Account` button style is broken on `Table View`

### ISSUE THREAD

**Issue by pdcp1** [responsible-ai-collaborative/aiid#1244]
### Steps to reproduce

1. Go to Staging https://staging-aiid.netlify.app
2. Check `Your Account` button on the sidebar. It's displayed correctly
<img width="253" alt="image" src="https://user-images.githubusercontent.com/6564809/195138902-c27dc5bc-b9e0-4277-aa70-dc77988c5358.png">

3. Click on `Table View` sidebar menu item
4. Check `Your Account` button on the sidebar again. It's displayed incorrectly.
<img width="256" alt="image" src="https://user-images.githubusercontent.com/6564809/195139246-edd34aaa-6972-4ca1-b923-c52fbb5158ae.png">

**Comment by lmcnulty** [comment]
This is fixed by #1227.
