### ISSUE TITLE
Strange Bullet Behavior

### ISSUE THREAD

**Issue by smcgregor** [responsible-ai-collaborative/aiid#1261]
It is putting the text on the line after the bullet.

<img width="614" alt="Screen Shot 2022-10-12 at 3 47 19 PM" src="https://user-images.githubusercontent.com/64780/195461820-fe636c0f-432b-4aae-a71d-e6428cedcd84.png">

**Comment by pdcp1** [comment]
Closing this since https://github.com/responsible-ai-collaborative/aiid/pull/1262 was merged and fixed on Staging

**Comment by pdcp1** [comment]
Closing this since https://github.com/responsible-ai-collaborative/aiid/pull/1264 was merged and fixed on Staging
- https://staging-aiid.netlify.app/taxonomy/cset
- https://staging-aiid.netlify.app/taxonomies
