### ISSUE TITLE
Editor Submission Form – Add `Editors` & `Incident Title` fields

### ISSUE THREAD

**Issue by LKchemposer** [responsible-ai-collaborative/aiid#1266]
Legacy requests from #1111

`Editors` and `Incident Title` fields are available in the Table View Edit form:

<img width="599" alt="image" src="https://user-images.githubusercontent.com/39468345/195535123-6a781e67-8de9-4c88-975b-cf17fa2f1f67.png">

But they are not available in the Submission form *for a new incident* in the Tell us more:

<img width="827" alt="image" src="https://user-images.githubusercontent.com/39468345/195535822-d1ae6375-c3bc-4fa3-a6f2-f089d19fe672.png">

These fields should _only_ be available to editors, not submitters, and for new incidents. This saves editor time spent on manually changing these entries for each incident.

**Comment by LKchemposer** [comment]
@smcgregor not sure if there are new updates? this would also resolve the issue where emails sent to subscribers have edited incident titles as opposed to report titles.

**Comment by smcgregor** [comment]
@LKchemposer I believe @lmcnulty is working on it. I think the editor likely needs to be derived from the user hitting the ingestion button but the user accounts don't have names attached to them. That part may need to wait one more change set.

**Comment by LKchemposer** [comment]
@smcgregor, can the `Title` be in the immediate next patch since it is a bit more needed?

**Comment by smcgregor** [comment]
Something may land before it, but the title fix is the current development target and will land as soon as it is ready.
