### ISSUE TITLE
Cannot submit report

### ISSUE THREAD

**Issue by LKchemposer** [responsible-ai-collaborative/aiid#1272]
Pressing the Submit button:

![](https://user-images.githubusercontent.com/39468345/196107244-b5ce2301-40ce-4725-b14e-824f422484e7.png)

... gives this box with no text, and no confirmation that the report is submitted

![](https://user-images.githubusercontent.com/39468345/196107582-7b50c7cc-f612-449d-ae73-4647b1e87800.png)

The report does not appear in the queue either

**Comment by lmcnulty** [comment]
Ok, this occurs when you try to submit a new report of an existing incident.

![image](https://user-images.githubusercontent.com/25443411/196216313-a47f2953-5738-4e8c-88f8-da2dd0184b81.png)
