### ISSUE TITLE
Prevent triggers crash on DB restore

### ISSUE THREAD

**Issue by pdcp1** [responsible-ai-collaborative/aiid#1275]
Each time that we restore a DB image, it fires tons of `insert` and `update` events.
This makes the triggers on `updates` and `inserts` fails and crash.

**Triggers that crashed:**

- onIncidentUpdate
- onNewIncident

The error is:
```
Error: change stream was invalidated
```

We already added a pre-condition (Match expression) on the `onIncidentUpdate` trigger, to only process updates on certain incident fields, but it looks like it’s not enough to avoid crashing on DB restores.

![image](https://user-images.githubusercontent.com/6564809/196236918-d7a7cd94-52fd-46c1-ba81-97f773dfb818.png)

**Comment by pdcp1** [comment]
@smcgregor I found that the reason for the trigger failure is the drop option of the `mongorestore` command that we use.

It fires a [`invalidate` event](https://www.mongodb.com/docs/manual/reference/change-events/invalidate/#mongodb-data-invalidate). An invalidate event occurs when an operation renders the change stream invalid. For example, a change stream opened on a collection that was later dropped or renamed would cause an `invalidate` event.

No matter the trigger's code, it will fail and needs to be resumed. You can restart a suspended Trigger from the App Services UI or by importing an application directory with [realm-cli](https://www.mongodb.com/docs/atlas/app-services/cli/#mongodb-binary-bin.realm-cli)

My suggestion is to restart the triggers right after you receive the Trigger failure email notification.
To do that:

1. Go to Atlas App Service > Triggers
2. Click on `Restart` on the trigger that is suspended
3. Uncheck `Restart this trigger with a resume token?` option
4. Click `Resume Trigger` button

More information about suspended triggers: https://www.mongodb.com/docs/atlas/app-services/triggers/database-triggers/#suspended-triggers

**Comment by smcgregor** [comment]
You are saying that when we restore a database, some triggers will stop and all we need to do is restart them? One note: we likely need to turn off email notifications on staging since we are updating the staging database from production and we don't want users to be notified of staging changes.

**Comment by pdcp1** [comment]
Yes, correct. Each time that we restore a database, some triggers will stop and all we need to do is restart them as part of the restore process.

There are more complex programmatic solutions to detect the trigger failure, but since the DB restore is not done too often, I think it doesn't worth it.

Regarding Staging email notifications, we can add an IF condition asking if the `SendGridApiKey` app value is defined. If not, we skip the email notification.
Doing it in that way, we can avoid re-enabling the email notifications by accident on the next Staging deployment.

**Comment by smcgregor** [comment]
Sounds good to me.

**Comment by pdcp1** [comment]
@smcgregor I just realized that since the users and the user's subscription information is on `customData` database, not in the `aiidprod` database, we are not going to have any Prod user subscription on Staging.
Assuming that we are not updating Staging `customData` database.

Anyways, I created this PR #1281 to add the ability to turn on/off the email notification just with the `SendGridApiKey` App secret value.

**Comment by pdcp1** [comment]
Closing this since the ability to turn on/off email notifications was already merged and the prevention of the trigger failures was resolved using Pre and Post deployment PRs.
Feel free to reopen this (or open another issue) if you think that we have to implement it in another way.
