### ISSUE TITLE
Incident Response Support

### ISSUE THREAD

**Issue by smcgregor** [responsible-ai-collaborative/aiid#1282]
We are going to support the collection of post-incident responses from involved entities. These responses include what happened, why did it happen, and what will they do to prevent it from happening again. Entities that provide this information will be credited in the UI, while entities producing many incidents and no incident responses will have less favorable display within the user interface. Several people will need to contribute to this issue before it will be completed.

1. @clari182 An [example](https://incidentdatabase.ai/cite/51#r1765) of a incident response is on incident 51. While it lacks some important information, it does give the company's perspective on the incident. We will treat this response as our test case. This report should be tagged with `report`, then when rendering the card associated with the report there should be some change to the manner in which it is rendered so it is clearly identified as an incident response. One idea here is to add a badge to the headline saying something like `{author} post-incident response`.

2. @clari182 The incident cards should likely be reworked since they are very large. Each card can have a "Read More" button that expands the textual contents, while the image can be displayed next to the text similar to the "Latest Incident Report" component on the landing page.

3. @clari182 or @lmcnulty Something should annotate the incident citation page to indicate it has an incident response. Some ideas include:
* the timeline can have a special symbol for the response.
* The header of the citation page can indicate there is an incident response with a badge.

4. @LKchemposer and @Janetbananet We need a page on the website linked from the footer that defines what an incident response is. I think Khoa and Janet should collaborate on this, with me as reviewer. The important points for this are to define what an incident response is, link to example(s), and say what an incident response should not be (simply PR fluff). Initially the page can be black so you can link to it as appropriate.

5. @clari182 We need a button on the citation page for adding an incident response. We can use the same pattern we used for creating a new report for an existing incident by pre-filling the tag (`response`) that will be applied to the report. I think it would be good to change the title of the page from `New Incident Report` to `New Incident Response` when this tag is set so people will clearly know that they are in the right place.

6. @clari182 The `Common Entities` component and the `Entities` page should both include information crediting the entities that are providing incident responses. Perhaps on the landing page, add `, with {response count} incident responses` to the landing page component. On the entities page it may be best to add a column for responses.

7. @pdcp1 Finally, and this could likely be done first, we want people at companies to know when an incident happens involving their company for which they should prepare a response. The entities pages should thus be subscribeable so users can be notified when an incident is (1) newly tagged with their monitored entity name and (2) when an update is made to an incident for which they are monitoring its entity. These are two different subscription types the user should be able to sign up for.

I am assigning @pdcp1 to own this feature development and bring in additional people when needed, particularly since the subscription elements are likely to be the most complicated.

**Comment by pdcp1** [comment]
@smcgregor Regarding the subscription part, do you think it's OK to add the Subscribe option on the `/entities` page on each Entity item?
Do you have any email drafts for both cases (new and updated incidents)? If not, I can sketch something and let you know for approval.

**Comment by smcgregor** [comment]
Something like the following,

Subject: New Incident for {entity}
```
A new incident has just been added to the AI Incident Database for an entity you monitor.

Entity: {entity -- link to entity page}
Incident Number: {number -- link to citation page}
Incident Title: {title}
Incident Description: {description}
Incident Date: {date}

{entity string, the one that says who developed/deployed the system and who was harmed. Don't work too hard to include this.}

Manage Subscriptions
```

Note that this can not be sent until the site builds because the page won't exist yet.

Subject: Update Incident for {entity}
```
A incident involving {entity} has just been updated within the AI Incident Database.

Incident Title: {title}
Incident Description: {description}
Incident Date: {date}

{entity string, the one that says who developed/deployed the system and who was harmed. Don't work too hard to include this.}

Updates include new reports added to the citation page and other modifications of what is presented to the public.

Manage Subscriptions
```

This may also need to be sent at next build...

**Comment by pdcp1** [comment]
## Development strategy point by point

1. Assigned to @clari182
Issue: https://github.com/responsible-ai-collaborative/aiid/issues/1395
PR: https://github.com/responsible-ai-collaborative/aiid/pull/1399

2. Assigned to @clari182 
Issue: https://github.com/responsible-ai-collaborative/aiid/issues/1398
PR: TDB

3. Assigned to @clari182 
Issue: https://github.com/responsible-ai-collaborative/aiid/issues/1398
PR: TDB

4. Assigned to @lmcnulty and @Janetbananet (as a page content editor)
Issue: https://github.com/responsible-ai-collaborative/aiid/issues/1382
PR: https://github.com/responsible-ai-collaborative/aiid/pull/1385

5. Assigned to @clari182 
Issue: https://github.com/responsible-ai-collaborative/aiid/issues/1396
PR: https://github.com/responsible-ai-collaborative/aiid/issues/1396

6. Assigned to @pdcp1 
Issue: https://github.com/responsible-ai-collaborative/aiid/issues/1394
PR: https://github.com/responsible-ai-collaborative/aiid/pull/1402

7. Assigned to @pdcp1 
Issue: https://github.com/responsible-ai-collaborative/aiid/issues/1299
PRs: https://github.com/responsible-ai-collaborative/aiid/pull/1312
https://github.com/responsible-ai-collaborative/aiid/pull/1350
https://github.com/responsible-ai-collaborative/aiid/pull/1359

**Comment by pdcp1** [comment]
@smcgregor I think we can close this issue since every part of it is done and merged.
