### ISSUE TITLE
Variant Support

### ISSUE THREAD

**Issue by smcgregor** [responsible-ai-collaborative/aiid#1283]
We are going index high-volume data associated with several system types that tend to produce a large number of incidents. One example includes chatbots that can produce high volume of abusive content. This type of data is generally very structured, and thus is difficult to index in a generic manner. Initially, we will ask for inputs into two text areas: `inputs and circumstances` and `outputs and outcomes`. We will provide instructions on what these mean to the users (please design with 2 sentences of Lorem text).

**Design notes:**

1. Users should have the ability to add variants only via the citation pages for an incident. For now, this should not require a user account, but if we start getting flooded with trash we can lock it down to user accounts.

2. The form should have two text areas for input. One is prompted to be the `input and circumstances`, while the other is prompted to be the `output and outcomes`. People can put whatever they like into these and we can support markdown.

3. Submissions to this form should be flagged as "unreviewed" and editors should have the ability to change the flag to "approved" and "rejected", as well as have the ability to edit/destroy the submission.

4. Regardless of the flag status, the entries in the collection can be displayed on the citation page to which they were submitted, with appropriate display on the UI indicating when something has not been reviewed.

5. In the future, we will likely extend this variant submission process to provide for more explicit structure of inputs and outputs. For example, we want to have the ability to download all GPT-3 prompts and outputs as strings separated from any discussion about the contents of those prompts/responses.

6. The editors will need some user interface to quickly page through and approve variants. I think this can be a table view with the incident number, title, and description next to each variant's inputs/outputs.

7. Most incidents will not have variants, but for those that do, there should be some mention within the statistics panel of the associated citation page.

@pdcp1 I am assigning you on here to lead the feature to delivery. Please feel free to bring in me/other people as may be appropriate.

**Comment by smcgregor** [comment]
Test case: https://incidentdatabase.ai/cite/118

**Comment by pdcp1** [comment]
@smcgregor Please confirm if we are on the same page about this feature:

1. Variants will use the same Report form but with some extra optional fields, like Inputs and Outputs
2. Variants will be stored in the `reports` collection
3. Variants will have a `report_number`, `input` (text field) and `output` (text field)
4. The idea is that Algolia indexes Variants in the same way that it indexes Reports, that's the main reason to store it in the same collection. So users can search for Variants inputs/outputs on the Discovery page.
5. We should add a simpler way to add an Incident Variant. It could be a small form on the citations page that is opened when the user clicks on `Add Variant`
6. Variants will be displayed at the bottom of the citations page. Taking into consideration that they can be many.

**Comment by smcgregor** [comment]
All looks great except for `4`. I think we will likely only want to index reports in algolia where there is text in the text field.

**Comment by pdcp1** [comment]
I add this link provided by @smcgregor on Slack with more context of Variants: https://arxiv.org/abs/2211.10384

**Comment by pdcp1** [comment]
@smcgregor Please take a look at this Figma mockup that I created. Ignore small things like fonts, colors, padding, and margins, the purpose of this mockup is just to confirm if we are on the same page in terms of design and component position. Since we plan to have multiple variants per incident, my idea is to add a scroll as needed in the Variant list.

## Unauthenticated User view
<img width="616" alt="image" src="https://user-images.githubusercontent.com/6564809/205154304-84ed294d-10e1-419d-8c32-90239d984b20.png">

When the user clicks on the `New Variant` button:

<img width="794" alt="image" src="https://user-images.githubusercontent.com/6564809/205154646-335f665b-6c1e-4f4b-95d8-b69018308f85.png">

## Editors view
<img width="636" alt="image" src="https://user-images.githubusercontent.com/6564809/205160800-2a03f620-59f6-495c-917f-81b9d592a4f8.png">

**Comment by smcgregor** [comment]
@pdcp1 this is looking good, but I think we may need to talk about backend design choices today or Monday -- please let me know when you are available on Slack.

Some notes:

* I think you can remove the `submit` button from the editor views since the form is exposed it should update when you hit approve and reject.
* I want to talk a bit about how this will be stored on the backend

The current `reports` schema is: https://github.com/responsible-ai-collaborative/aiid/blob/master/mongo.md#reports-collection-details

I think the way to work on top of that collection is to consider the only hard requirements of a variant: `_id `, `report_number`, `date_submitted`, `date_modified`, `epoch_date_submitted`, `epoch_date_modified`. The reports collection would then need to have new fields for `text_inputs` and `text_outputs` and be presented to users as `Inputs and circumstances` and `outputs and circumstances`. All the other mandatory fields can auto-fill in the backend. In the future, I think we would allow for all the other fields of a report to be entered in, but getting UX right on that will take a lot more thought and should be left to later. We are also going to be attaching more fields and field types to the report documents (e.g., sensor data), but that will also be left to later. For now, we can presume these two new field types will be everything that is necessary -- they will need to be added to the standard submit form as optional fields.

* We also need to differentiate reports for the original incident and the reports of variants. I think the best way to handle this will be to treat some set of fields as being "variant related", which for now would only be the `text_inputs` and `text_outputs` fields. If those fields are specified, then the report would be considered a variant.


If this is getting too complicated/brittle, we can also scrap it and simplify. Let's talk!

**Comment by pdcp1** [comment]
@smcgregor After researching different technical alternatives, I can say that the option that you mentioned before looks good to me. Since we plan to add more report fields to the variants in the future, makes sense to use the `reports` collection to store variants as well. Adding `text_outputs` and `text_inputs` text fields into the `reports` collection.

To differentiate between Reports, Issues and Variants we can use GraphQL, so the frontend conditional logic is not too complex to handle.
The conditions are:
- Issues: report document with no Incidents associated. AKA orphans reports.
- Variants: report document with at least one Incident associated, `text_outputs` and `text_inputs` fields defined.

I will proceed with this approach.

**Comment by pdcp1** [comment]
@smcgregor I'm storing the Variant review status as a tag in order to reuse the current `reports` collection DB schema.
The different Variant statuses are:
- Approved. Tag `approved`
- Rejected. Tag `rejected`
- Unreviewed, Tag `unreviewed`

What do you think?

**Comment by smcgregor** [comment]
How about `variant:approved`, `variant:rejected`, and `variant:unreviewed`?

**Comment by pdcp1** [comment]
@smcgregor We need to define the texts for:
- Section subtitle
- Tooltips for Inputs and Outputs

<img width="896" alt="image" src="https://user-images.githubusercontent.com/6564809/207360353-646e822c-6392-4153-a301-5ed8777e9230.png">


Could you help me with that?

**Comment by smcgregor** [comment]
## Variants

A "variant" is an incident that shares the same causative factors, produces similar harms, and involves the same intelligent systems as a known AI incident. Rather than index variants as entirely separate incidents, we list variations of incidents under the first incident submitted to the database. Unlike other submission types to the incident database, variants are not required to have reporting in evidence external to the Incident Database. [Learn more from the research paper.](https://arxiv.org/abs/2211.10384)

? (Input and circumstances)  
Provide the relevant details producing the incident. Examples include the input prompts to a chatbot or a description of the circumstances leading to injuries sustained from a robot.

? (Output and outcomes)  
Provide the relevant details surrounding the incident. Examples include output text from a chatbot or the nature of injuries sustained from a robot.

**Comment by pdcp1** [comment]
@smcgregor We need to define where the link to the `/apps/variants` page will be. Maybe another sidebar menu item?
This is a preview of how it looks like:

<img width="1376" alt="image" src="https://user-images.githubusercontent.com/6564809/207961441-76c9836e-5d32-43b4-aa4f-3933c2e274f0.png">

**Comment by smcgregor** [comment]
@pdcp1 let's get this into production without the link to start -- we can go to it directly.

I think we are going to want to have an editor's page that links out to all these pages since only editors should look at the review queues.

**Comment by pdcp1** [comment]
@smcgregor this initial version of the variants with `inputs` and `outputs` is done and live in Production. I suggest closing this issue and opening a new one if we want to change the Variants feature in the future.
