### ISSUE TITLE
Broken Blog Images

### ISSUE THREAD

**Issue by smcgregor** [responsible-ai-collaborative/aiid#1302]
Our first blog post has a bunch of broken blog images. https://incidentdatabase.ai/blog/the-first-taxonomy-of-ai-incidents

**Comment by lmcnulty** [comment]
With the fix in #1303, there still seems to be one missing image:

![image](https://user-images.githubusercontent.com/25443411/199748486-6f5c5402-8437-4a7a-86ad-7cf1b773d6cc.png)
