### ISSUE TITLE
Cannot update reports assigned with an incident id

### ISSUE THREAD

**Issue by LKchemposer** [responsible-ai-collaborative/aiid#1305]
For reports that are submitted without an already assigned incident id:

<img width="831" alt="image" src="https://user-images.githubusercontent.com/39468345/197558129-545dc595-7d4e-4d8c-8681-e4453c4ba2dc.png">

... assigning it an incident id still runs into `Some data is missing` message:

<img width="831" alt="image" src="https://user-images.githubusercontent.com/39468345/197558510-e3d11300-802d-4708-b017-80794df20800.png">

... and the Update button cannot be pressed:

<img width="831" alt="image" src="https://user-images.githubusercontent.com/39468345/197558573-5024e23d-5e4a-44f0-8297-b647055cf422.png">

**Comment by LKchemposer** [comment]
Actually reports already assigned with an incident id are also affected

**Comment by lmcnulty** [comment]
I think any mandatory fields should be moved outside of "tell us more." The label comes with a very strong implication that its contents are optional, and I would annoyed if that inference turned out to be incorrect.

**Comment by LKchemposer** [comment]
For submitters, "Tell us more" fields should be optional. For editors, they should be mandatory.

**Comment by pdcp1** [comment]
In this case, the issue is with the `Description` field. The current implementation (for submitters) **allows null values** for `description` but if it has a text, it must have at least 3 characters and can't be longer than 500 characters.

Is that correct?

**Comment by pdcp1** [comment]
> For submitters, "Tell us more" fields should be optional. For editors, they should be mandatory.

@LKchemposer Should all "Tell us more" fields be mandatory for editors?

<img width="823" alt="image" src="https://user-images.githubusercontent.com/6564809/197580667-cd6046d3-69ab-4ee7-9bf9-bdba4ecd2ec3.png">

**Comment by LKchemposer** [comment]
@pdcp1 `description`, `developer`, `deployer`, `harmed parties` should all be mandatory. `editor notes` and `tags` are not.

**Comment by pdcp1** [comment]
@smcgregor @LKchemposer This is fixed on PR #1308 and ready to review on this preview link https://deploy-preview-1308--staging-aiid.netlify.app/

**Comment by pdcp1** [comment]
> I think any mandatory fields should be moved outside of "tell us more." The label comes with a very strong implication that its contents are optional, and I would annoyed if that inference turned out to be incorrect.

@lmcnulty I agree with you on that, maybe you can create a separate issue to discuss.

**Comment by pdcp1** [comment]
This fix was merged to Staging, feel free to close this issue if everything works as expected.

**Comment by LKchemposer** [comment]
Argh. It seems that although I can now update the incident, I cannot add it to the database. Should I open a separate issue for it?

<img width="1092" alt="image" src="https://user-images.githubusercontent.com/39468345/197836349-6d62cd13-976c-4e05-943b-52b8a550420a.png">

**Comment by smcgregor** [comment]
@LKchemposer this is for an submission that was already in the queue, or for a newly submitted report?

**Comment by LKchemposer** [comment]
This is a report that was added last week (before the cannot update issue). Should I try with a newly submitted report – e.g., submitted today?

**Comment by smcgregor** [comment]
Didn't you already submit a new one and ingest it?

**Comment by LKchemposer** [comment]
Ones without an assigned incident id (new incidents), and they worked.

**Comment by smcgregor** [comment]
@pdcp1 can you take a look at adding a new report to an existing incident?

**Comment by pdcp1** [comment]
@LKchemposer Keep in consideration that this fix includes validation on the `description` field that is now mandatory for editors. If you are trying to `Add New Report` on a pre-existing submission, maybe that submission doesn't have the description field set, and that's why it fails.
Maybe it's better to test the whole workflow from the beginning, submitting a new submission from scratch.

I will test adding a new report to an existing incident as well.

**Comment by smcgregor** [comment]
@pdcp1 The description field is a property on `incidents` which is assigned via the form for new incidents, but should not be assigned for existing incidents via this form.

**Comment by LKchemposer** [comment]
@pdcp1 I thought for a pre-existing submission, when assigning it an `incident id` the `description` field of the incident is auto-filled with the `description` of the incident but is hidden. is that correct?

**Comment by pdcp1** [comment]
Yes, I agree with you both. We are on the same page.

I open this PR to match the expected behavior:

1. On `/apps/submit` submission form, none of these fields are **required**:
    - `Incident ID`
    - `description`
    - `Alleged developer of AI system`
    - `Alleged deployer of AI system`
    - `Alleged harmed or nearly harmed parties`

2. On `/apps/submitted` submission review form:

   2.1. If no `Incident ID` is set, all of these fields are **required** and will be set to the New Incident created:
    - `description`
    - `Alleged developer of AI system`
    - `Alleged deployer of AI system`
    - `Alleged harmed or nearly harmed parties`

   2.2. If a valid `Incident ID` is set, none of these fields are required since they will be picked up from the Incident selected:
    - `description`
    - `Alleged developer of AI system`
    - `Alleged deployer of AI system`
    - `Alleged harmed or nearly harmed parties`

**Comment by LKchemposer** [comment]
This is confirmed resolved
