### ISSUE TITLE
Bug – Report shown with `AI translated` tag although original report is in English

### ISSUE THREAD

**Issue by LKchemposer** [responsible-ai-collaborative/aiid#1337]
Report 2167 of [incident 371](https://incidentdatabase.ai/cite/371)

<img width="1399" alt="image" src="https://user-images.githubusercontent.com/39468345/199425700-84691ac7-347a-432e-b302-ac220ffded45.png">

**Comment by LKchemposer** [comment]
Also, just noticed that the header says `Incidents Reports`, which should be `Incident Reports` (no `s`)

**Comment by smcgregor** [comment]
I fixed this -- oddly enough it was related to why the table view recently went down
