### ISSUE TITLE
Informal Security Audit

### ISSUE THREAD

**Issue by smcgregor** [responsible-ai-collaborative/aiid#1362]
Need to evaluate the system for potential security issues, including:

* Front end
* Backend
* DevOps

Contact @smcgregor or @cesarvarela before taking this one on.

**Comment by cesarvarela** [comment]
What has been done:

- went over every Atlas schema rules checking unprotected collections
- updated npm packages fixing critical dependencies
- followed this https://docs.netlify.com/platform/security/#recommended-security-measures
- and this https://www.mongodb.com/docs/atlas/app-services/security/


Something to improve is adding a WAF like the one offered by Cloudflare.
