### ISSUE TITLE
Incident response - #5 Create response btn

### ISSUE THREAD

**Issue by clari182** [responsible-ai-collaborative/aiid#1396]
Part of #1282 

We need a button on the citation page for adding an incident response. We can use the same pattern we used for creating a new report for an existing incident by pre-filling the tag (response) that will be applied to the report. I think it would be good to change the title of the page from New Incident Report to New Incident Response when this tag is set so people will clearly know that they are in the right place.

**Comment by pdcp1** [comment]
@clari182 this Issue should be renamed to # 5. I can't change the title.
