### ISSUE TITLE
Add as Issue – cannot add as issue if `description` is blank

### ISSUE THREAD

**Issue by LKchemposer** [responsible-ai-collaborative/aiid#1429]
It is counterintuitive that although adding as an issue ignores incident fields, it requires `description` to be filled in.

<img width="1095" alt="image" src="https://user-images.githubusercontent.com/39468345/204713433-1075e96f-1615-4e3b-8639-6b909eeb02b6.png">

**Comment by smcgregor** [comment]
Highlighted in the pull request, but it doesn't have a separate issue yet: https://github.com/responsible-ai-collaborative/aiid/pull/1408
