### ISSUE TITLE
Standardize New Incident and New Incident for Entity Emails

### ISSUE THREAD

**Issue by smcgregor** [responsible-ai-collaborative/aiid#1431]
The entity email has more information, I think we can use that notification email for new incidents as well.

<img width="967" alt="Screen Shot 2022-11-29 at 10 33 29 PM" src="https://user-images.githubusercontent.com/64780/204724593-8573c8cf-f9ce-428b-b574-d299729dc1fd.png">

<img width="1009" alt="Screen Shot 2022-11-29 at 10 33 49 PM" src="https://user-images.githubusercontent.com/64780/204724615-dac84d81-ba30-4ca2-99a4-668c9618abce.png">

**Comment by pdcp1** [comment]
Closing this since it was already merged into Staging
