### ISSUE TITLE
Incident Table View is Broken

### ISSUE THREAD

**Issue by smcgregor** [responsible-ai-collaborative/aiid#1432]
What was increasingly a long load time is now spinning for minutes (and counting). I believe it is completely broken at the moment in both staging and production. I have tested this in chrome and in firefox on macos, and Firefox on iOS.

https://incidentdatabase.ai/apps/incidents/

**Comment by smcgregor** [comment]
Staging has now loaded after more than a minute.

**Comment by smcgregor** [comment]
Prod is still loading...

I am changing the MongoDB service tier to M5, which is the highest shared tier. This will bring the database down for a few minutes. We have observed in the past that triggering the DB migration can refresh the DB software environment, this may restore the incidents table. It may also be time to switch to a dedicated tier, but I am skeptical that will fix this problem.

**Comment by smcgregor** [comment]
Still a problem in the Realm logs:

```
Error:


ERROR: could not validate document 'ObjectID("6356adfd642a3e49ac4c13ae")' for read

Function Call Location:

US-OR

GraphQL Query:


query FindIncidents($query: IncidentQueryInput) { incidents(query: $query, limit: 999) { incident_id title description editors date AllegedDeployerOfAISystem { entity_id name __typename } AllegedDeveloperOfAISystem { entity_id name __typename } AllegedHarmedOrNearlyHarmedParties { entity_id name __typename } nlp_similar_incidents { incident_id similarity __typename } editor_similar_incidents editor_dissimilar_incidents flagged_dissimilar_incidents reports { report_number __typename } embedding { from_reports vector __typename } __typename } }

Compute Used:

172150406605 bytes•ms

Remote IP Address:

68.228.95.60

Rule Performance Metrics:

{
  "namespacesMetrics": {
    "aiidprod.entities": {
      "roles": {
        "role is admin": {
          "matchingDocuments": 1660,
          "evaluatedFields": 0,
          "discardedFields": 0
        }
      },
      "noMatchingRole": 0
    },
    "aiidprod.incidents": {
      "roles": {
        "role is admin": {
          "matchingDocuments": 401,
          "evaluatedFields": 0,
          "discardedFields": 0
        }
      },
      "noMatchingRole": 0
    },
    "aiidprod.reports": {
      "roles": {
        "role is admin": {
          "matchingDocuments": 2106,
          "evaluatedFields": 0,
          "discardedFields": 0
        }
      },
      "noMatchingRole": 0
    }
  }
}
```

**Comment by smcgregor** [comment]
I have temporarily hidden the table view from navigation so we can resolve this later today without directing people to a broken page.

This should be rolled back when there is a fix:

https://github.com/responsible-ai-collaborative/aiid/pull/1433

**Comment by pdcp1** [comment]
I see this error response on production for the `FindIncidents` query:
```
{
    "data": null,
    "errors": [
        {
            "message": "reason=\"could not validate document: \\n\\t(root): plain_text is required\\n\\t(root): language is required\"; code=\"SchemaValidationFailedRead\"; untrusted=\"read not permitted\"; details=map[]",
            "locations": [
                {
                    "line": 31,
                    "column": 5
                }
            ],
            "path": [
                "incidents",
                352,
                "reports"
            ]
        }
    ]
}
```

**Comment by cesarvarela** [comment]
I think that adding `plain_text` to this report should fix it:

![image](https://user-images.githubusercontent.com/1172479/204867877-a882633b-13e6-42e3-a7d1-e668082e3543.png)

`text` doesn't seem to be markdown, so it might be just a matter of copying that into the `plain_text` field.
