### ISSUE TITLE
Ingest form – data validation bug

### ISSUE THREAD

**Issue by LKchemposer** [responsible-ai-collaborative/aiid#1455]
The form did not let me update, said "missing info," despite all the required field filled out. Occurred for reports where the submitter did not assign an `incident id`, but when I added an incident id` which supposedly autofilled the fields, but the "missing info" was still there.

Workaround: unassign an `incident id` > fill in random text for `description` and `alleged parties` > remove the random text > assign the `incident id`

**Comment by lmcnulty** [comment]
I think this will be solved when #1438 is merged. I was able to replicate on staging, but not on that branch.

**Comment by LKchemposer** [comment]
I was able to add a newly submitted (in the past day) report with an assigned `incident id` just now, but I still couldn't add an older report (submitted a week ago) with an assigned `incident id`
