### ISSUE TITLE
Translate editor's guide

### ISSUE THREAD

**Issue by lmcnulty** [responsible-ai-collaborative/aiid#1456]
#1327 needs to be translated into French and Spanish – opening as a new issue so anyone who wants to do it can assign themselves.

**Comment by smcgregor** [comment]
The guide is likely to develop fairly quickly over the next few months, so let's hold this one until it begins to stabilize. We should link to the English version from the translated pages.

**Comment by lmcnulty** [comment]
Ok, closing for now.
