### ISSUE TITLE
Typeset Blog Post: Subscriptions and eNewsletter

### ISSUE THREAD

**Issue by Janetbananet** [responsible-ai-collaborative/aiid#1459]
The content is in this google doc: https://docs.google.com/document/d/1JoL6uOUdomLleO4GgG5D-YriBjRayUxXRQtqXn_bxpM/edit?usp=sharing

**Comment by Janetbananet** [comment]
Please use the spotlight thumbnail image from https://incidentdatabase.ai/blog/user-story-spotlights

**Comment by lmcnulty** [comment]
Should there should be a link where it says "Sign up for the eNewsletter..."?

> If you are interested in the latest in AI incidents, you can now have new incidents delivered straight to your inbox. The AI Incident Database now has a subscription feature along with a monthly newsletter to make it even easier to keep up with the latest reports.
>
> Sign up now for the eNewsletter: “AI Incident Monthly Roundup”
>
> The eNewsletter is designed to answer the questions:

**Comment by Janetbananet** [comment]
Yes! I was hoping maybe we could create a button or something else a little flash my that would make people click on it. If that's out of the cards given how much time it would take, then a regular link is also just fine.

**Comment by lmcnulty** [comment]
I can probably do that. What's the URL to subscribe to the newsletter?

**Comment by Janetbananet** [comment]
I actually have the same question! @pdcp1 Is there a URL we can use for people to connect directly to the subscribe page?

**Comment by pdcp1** [comment]
@Janetbananet @lmcnulty We can link to `/signup`. The same link that we have for the `Subscribe` button on the left sidebar menu.
