### ISSUE TITLE
Google Indexing for Non-English

### ISSUE THREAD

**Issue by smcgregor** [responsible-ai-collaborative/aiid#1465]
I don't believe we are well indexed by Google in French and Spanish. I activated the Google Search console and added @cesarvarela and @pdcp1 to work on this at their next opportunity. Should someone else work on this issue, I will add them to the console.

**Comment by cesarvarela** [comment]
For the time being, I'll assume this has been fixed:

<img width="614" alt="image" src="https://user-images.githubusercontent.com/1172479/224198183-93103a8b-ebaf-4bad-93d4-1bc6299c8d04.png">
