### ISSUE TITLE
Updates to the Site Header and Footer

### ISSUE THREAD

**Issue by Janetbananet** [responsible-ai-collaborative/aiid#1492]
Remove the following links from the footer:
- Launch announcement
- Initial Collection Methodology (note that the page itself should remain, as it will be linked to elsewhere on the website.)

Add the Facebook and LinkedIn icons/links to the footer/header next to the Twitter icon.
https://www.facebook.com/IncidentsDB
https://www.linkedin.com/company/responsible-ai-collaborative

**Comment by Janetbananet** [comment]
@smcgregor This is a very simple update of the ones we discussed. Is it okay to go ahead and add it to the backlog now?

**Comment by smcgregor** [comment]
Added to backlog
