### ISSUE TITLE
Style glitches with viewport width at exactly 767px

### ISSUE THREAD

**Issue by lmcnulty** [responsible-ai-collaborative/aiid#1530]
Especially around the sidebar:

https://user-images.githubusercontent.com/25443411/211658226-fc1f81a3-0c7d-4761-aa38-5c0ff149a7ca.mp4

**Comment by smcgregor** [comment]
How did you find this? I am getting a sense for how many screens are this width...

**Comment by lmcnulty** [comment]
This one came up while working on the sidebar -- I tried resizing the viewport with down arrow keys and saw that there was a problem with the sidebar, which I then realized was present elsewhere.
