### ISSUE TITLE
Change Email Sender on Notifications

### ISSUE THREAD

**Issue by smcgregor** [responsible-ai-collaborative/aiid#1568]
Maybe `AIID:Notifications` or something similar. `Notifications` is too generic.

<img width="478" alt="Screen Shot 2023-01-26 at 10 25 01 AM" src="https://user-images.githubusercontent.com/64780/214918816-4cf9a40c-bef1-42ba-b66b-8455c86f22d2.png">

**Comment by pdcp1** [comment]
Closing this since it was already merged
