### ISSUE TITLE
JS bundle contains a 240Kb list of paths

### ISSUE THREAD

**Issue by lmcnulty** [responsible-ai-collaborative/aiid#1570]
Loading the landing page of the current production site makes a request for a **956**Kb (236Kb gzipped) JS bundle. Of this, **240**Kb (32K gzipped) is taken up by a very long JSON string listing the paths of every page on the site, including every entity, duplicated at least three times on account of the translations.

```javascript
A=JSON.parse('[{"path":"/es/summaries/es/spatial","matchPath":"/es/summaries/es/spatial"},{"path":"/es/summaries/fr/spatial","matchPath":"/es/summaries/fr/spatial"},{"path":"/fr/summaries/es/spatial","matchPath":"/fr/summaries/es/spatial"},{"path":"/fr/summaries/fr/spatial","matchPath":"/fr/summaries/fr/spatial"},{"path":"/es/apps/classifications/","matchPath":"/es/apps/classifications/"}, … ')
```

I'm not sure what this is doing, so I can't say whether it's necessary. However, if we want to reduce the payload size, this looks like a good place to investigate.

**Comment by cesarvarela** [comment]
This might be a gatsby thing, but yes, we should have a "improve page speed score" issue eventually.

**Comment by pdcp1** [comment]
Closing this since it was already merged into Production
