### ISSUE TITLE
Report card expand/collapse UX

### ISSUE THREAD

**Issue by lmcnulty** [responsible-ai-collaborative/aiid#1572]
The new report cards look good, but when you expand them the image abruptly disappears and you need to scroll all the way to the bottom of the article to collapse it again.

https://user-images.githubusercontent.com/25443411/215551185-c1a87c4f-cb5d-42a1-8732-2124bf7e1b6b.mp4

**Comment by smcgregor** [comment]
Keeping the image around somehow would be good and maybe two buttons for collapsing? I am not sure the right answer here without playing with some mocks.

**Comment by clari182** [comment]
I can work on that! I hide the image when expanded because it looked a little strange with both the text and image but I can try some options and open a PR

**Comment by lmcnulty** [comment]
I have two ideas for how this could work. One would be that the image could be `float: left` within the padding of the card rather than bleeding to the edges. The other is that the card could stay as it is now, but rather than the text inside it expanding, the full article text could slide out from under it. I could draw what I mean if that would help.
