### ISSUE TITLE
Report submission – Cannot submit reports _sometimes_

### ISSUE THREAD

**Issue by LKchemposer** [responsible-ai-collaborative/aiid#1579]
All required fields in step 3 were filled out, but it ran into this issue:

<img width="1180" alt="Screen Shot 2023-02-01 at 4 13 00 PM" src="https://user-images.githubusercontent.com/39468345/216000553-ea61a17c-56d2-4ba9-9ab4-734a1a433ea7.png">

Refreshing and submitting only at step 2 is the work-around, so there may be some issue in step 3.

**Comment by LKchemposer** [comment]
Update: it may be a bug in an earlier step, because when trying to submit this report `https://futurism.com/cnet-editor-in-chief-addresses-ai` (assigned to incident `457`) it ran into the `Was not able to create the report` issue

Update: refreshing and re-submitting the report works, not sure why

**Comment by smcgregor** [comment]
You are submitting multiple reports? It may be residual state from prior submissions since that is a less tested element.

**Comment by LKchemposer** [comment]
I'm not sure what multiple reports mean, but if it means submitting one after another, then yes. Come to think of it, there is an issue where after submitting a report, there is no longer a screen that tells me that the report is submitted, it is now a pop-up notification, and it takes me back to the submission form.

**Comment by smcgregor** [comment]
Reseting the state between submissions can be tricky. @clari182 can you see if you can replicate this?
