### ISSUE TITLE
News Search – Fetched text formatted incorrectly

### ISSUE THREAD

**Issue by LKchemposer** [responsible-ai-collaborative/aiid#1588]
When the article info is pulled from News Search, the text that is automatically fetched from the article has an issue where the Markdown lines within a paragraph are split (similarly to how the lines are displayed in the article), manually resolving this by deleting each new line would take a lot of time.

<img width="1034" alt="image" src="https://user-images.githubusercontent.com/39468345/217207226-e1729421-f84f-4551-84a3-e0776b987759.png">

Current workaround: use `Fetch info` button in the Submitter's form to re-fetch the text

**Comment by lmcnulty** [comment]
Yeah, the library we use to extract the Markdown text in the news search workflow wraps the text at 80 columns, which looks bad when the browser text input soft-wraps it. Markdown ignores single line-breaks, so it looks like the only issue with the rendered HTML is that the [] and () parts of the links are getting split across lines.

**Comment by smcgregor** [comment]
I think this is distinct from the problem where translations often insert a space in the markdown, but each could be addressed by post-processing the string output to error correct? I don't like fixing errors programmatically (it is better to have them not happen), but I think that may be the best solution here. Open to other options...

**Comment by pdcp1** [comment]
@lmcnulty As you mentioned, the article text is wrapped in 80 characters columns and stored in the `candidates` collection in that format. That's the source of the problem.
Where can I find that piece of code?
The other solution is to trigger the "fetch info" function when the page loads in order to get the correct text.

**Comment by lmcnulty** [comment]
@pdcp1 This occurs in [fetch-news.py](https://github.com/responsible-ai-collaborative/nlp-monitoring/blob/main/fetch-news.py) from the [nlp-monitoring](https://github.com/responsible-ai-collaborative/nlp-monitoring) repo. I could also take this one if you like.

**Comment by pdcp1** [comment]
@lmcnulty Yes, please. I will fix this issue triggering the "Fetch Info" when the page loads and the querystring has the `url` parameter defined.
I created this [issue](https://github.com/responsible-ai-collaborative/aiid/issues/1623) to fix the `fetch-news.py` scrapping process and assign it to you.

**Comment by pdcp1** [comment]
Closing this since it was already merged into Staging
