### ISSUE TITLE
Candidates collection size

### ISSUE THREAD

**Issue by lmcnulty** [responsible-ai-collaborative/aiid#1599]
The candidates collection grows over time, and currently we keep the full text of a many articles that are unlikely to be used.

**Comment by smcgregor** [comment]
Wow, quite a large collection already. Let's clean it out from time to time before we decide what our retention strategy should be here.

**Comment by cesarvarela** [comment]
Another option could be to move them to a new database since the snapshots only include `aiidprod,` and for dev purposes, we usually only restore `aiidprod` and `translations.`

<img width="316" alt="image" src="https://github.com/responsible-ai-collaborative/aiid/assets/1172479/d25e5050-dafd-471d-bba8-241341a4757a">

**Comment by kepae** [comment]
This could go to another DB but if we reduce the size enough, it's less important.

`candidates` currently accounts for 125mb of the snapshot:

<img width="595" alt="image" src="https://github.com/responsible-ai-collaborative/aiid/assets/4238598/edea428d-d204-450b-913a-df5b49e3efed">

We could also prune via:
* dropping the `text` field for documents beyond a certain date, which is only present on documents that represent a match. @lmcnulty conjectured that might be a majority of the payload.
* dropping old documents entirely. Do we need beyond 3 months?

What do you think @lmcnulty ?

**Comment by lmcnulty** [comment]
We probably want to keep at least the url of old documents, because otherwise we could end up re-indexing them. I think we should just discard the full text of those entries older than a month or so – that won't really lose us anything and should save most of the storage cost.
