### ISSUE TITLE
TSNE Visualization colors hidden

### ISSUE THREAD

**Issue by lmcnulty** [responsible-ai-collaborative/aiid#1601]
The TSNE visualization currently shows incidents with higher incident numbers above ones with lower numbers. That's preferable to the reverse, but since newer classification are less likely to be classified, the colorful, classified incidents tend to get buried in colorless ones, which looks bad. Instead, classified incidents should appear above unclassified ones.

<img src="https://user-images.githubusercontent.com/25443411/217922848-e212da05-64c8-451d-b645-dd7f0f766bbe.png" width="600"/>

**Comment by smcgregor** [comment]
This will get a bit better with some of the newer taxonomies coming to delivery.
