### ISSUE TITLE
Fix `fetch-news.py` news scrapping process from the `nlp-monitoring` repo

### ISSUE THREAD

**Issue by pdcp1** [responsible-ai-collaborative/aiid#1623]
@lmcnulty As you mentioned, the article text is wrapped in 80 characters columns and stored in the `candidates` collection in that format. That's the source of the problem. In addition to that, some Ad content is included in the text.

![image](https://user-images.githubusercontent.com/6564809/219122033-04c5f1c8-7e24-41ed-84f2-81bc90d32440.png)

**Comment by lmcnulty** [comment]
Resolved on backend via https://github.com/responsible-ai-collaborative/nlp-monitoring/pull/1
