### ISSUE TITLE
Feasibility of 404 fallback and active querying

### ISSUE THREAD

**Issue by smcgregor** [responsible-ai-collaborative/aiid#1637]
Most of the site is currently SSRd with some components being dynamic from the database, but I believe we could explore solutions that leverage the best of SSR while having dynamic queries to the DB as a fallback (e.g., when the first request 404s). This issue is not about implementation, but it is about deciding whether doing things like having a 404 patch for pages like `cite/490` that will check whether the content exists in the DB when it fails to load from the SSR content. This design approach could additionally be used on pages like `/apps/incidents/`, which would be able to default to the SSR content while also having the ability to switch to dynamic content.

**Comment by pdcp1** [comment]
Closing this since it was already merged to Production
