### ISSUE TITLE
Submit a report to the database

### ISSUE THREAD

**Issue by smcgregor** [responsible-ai-collaborative/aiid#1665]
Periodically it is good to play the role of the user. Please find a new incident report and submit it to the website, while recording things that were painful or unclear.

**Comment by lmcnulty** [comment]
Here's an issue I wasn't aware of: the form shows me the entity inputs, but I wasn't able to submit until I removed them.

![Screenshot_2023-03-01_11-16-58](https://user-images.githubusercontent.com/25443411/222198678-dc3e0a66-f794-4b86-804f-0333f46e8c59.png)

**Comment by pdcp1** [comment]
@lmcnulty According to your screenshot, it looks like there is a typo on the role name `deafult`. I don't know if that is the reason for the error, but it's something to fix for sure.

**Comment by Janetbananet** [comment]
Lots of what @LKchemposer, @smcgregor, and I discussed early this week is related to the ease of using the submit a report function. I'm adding in a batch of GitHub issues with the "Data: Pain Points" label onto it, but would love to hear back from the engineering team what their experience is.

**Comment by Janetbananet** [comment]
@smcgregor Should we close this issue since we are addressing updates to the submission and ingest forms in other GitHub issues related to Data Pain Points?

**Comment by smcgregor** [comment]
@Janetbananet no, this is one we will close once @cesarvarela @pdcp1 and @clari182 submit an incident report to the database. This is more about dogfooding than any particular issue with the code. :)
