### ISSUE TITLE
Save form state in sessionStorage or localStorage

### ISSUE THREAD

**Issue by lmcnulty** [responsible-ai-collaborative/aiid#1677]
> It seems that prompting before switching to a different page is unsupported https://github.com/gatsbyjs/gatsby/issues/10726. Instead they recommend saving the form state in localStorage. That seems like the most correct solution, it will just be a bit more work.

_Originally posted by @lmcnulty in https://github.com/responsible-ai-collaborative/aiid/issues/1631#issuecomment-1438711485_

**Comment by clari182** [comment]
Hey @lmcnulty are you working on this issue or is it available to assign to me? Thanks!
