### ISSUE TITLE
User Management in the UI

### ISSUE THREAD

**Issue by smcgregor** [responsible-ai-collaborative/aiid#1703]
We need a front-end to list user accounts, their current roles, and the permissions conferred to roles.

Steps

1. [x] Design mock
2. [x] Implement the design
3. [x] Fully specify role set and document them on the page
4. [x] Audit the roles and permissions applied to current users and ensure we can expand the user roles across the app

**Comment by Janetbananet** [comment]
@smcgregor I would like to follow along with this development from an end user perspective (maybe @LKchemposer wants to as well).

**Comment by Janetbananet** [comment]
I added the "Data:Pain Points" label here even though the label name itself isn't a perfect fit because it categorically fits into the Community Editor Project issues.

**Comment by Janetbananet** [comment]
This will likely relate to #1783 , in that when a new role is conferred upon a user, it will need to update in their user profile page as well.

**Comment by cesarvarela** [comment]
Some observations after going over every collection's ruleset:

- `candidates`: Everybody is allowed to write/search/delete 

- `classifications`: The taxonomy-specific roles do not check the classification namespace, so `taxonomy_editor` is equivalent to `taxonomy_editor_cset`

- `entities`: anybody can create new entities

- `incidents`: 
    - The `incident_editor` role doesn't allow for editing incidents. 
    - The `Add Variant` rule should be joined with the default rule.

- `reports`: 
   - `incident_editor` role can't edit reports.
   - anybody can insert/delete reports 💀    


- `translations` db
   - `incident_editor`  role can't edit translations

**Comment by cesarvarela** [comment]
follow up here: https://github.com/responsible-ai-collaborative/aiid/issues/1974
