### ISSUE TITLE
UI for Resolving duplicates

### ISSUE THREAD

**Issue by smcgregor** [responsible-ai-collaborative/aiid#1705]
Right now when we accidentally ingest a duplicate incident I go into the backend and add an entry to the duplicates collection and shift all the reports over to the original incident number. We need a UI to perform this activity.

**Comment by Janetbananet** [comment]
@LKchemposer This is one of the items we have on the process pain points!

**Comment by Janetbananet** [comment]
@smcgregor Could we expand the scope of this GitHub issue to include deleting incident (profiles) in general, rather than only in the case that there is a duplicate?

**Comment by smcgregor** [comment]
Incident numbers are meant to be permanent. We should never delete it entirely, but we can have something that marks it as erroneous/not actually an incident in some form.

**Comment by smcgregor** [comment]
I just moved the reports associated with 512 to 506 then added 

```
{"_id":{"$oid":"643644dc8af3d17a4004edac"},"duplicate_incident_number":{"$numberInt":"512"},"true_incident_number":{"$numberInt":"506"}}
```

to the duplicates collection.

I deleted:

```
{"_id":{"$oid":"6433d4e7b85bae8b1707b43d"},"title":"ChatGPT Reportedly Made up Facts when Prompted about Scandals of a Real Law Professor","description":"When prompted about scandals involving a law professor, ChatGPT cited non-existent accusations, events, quotes, reports, and sources involving a real law professor's name.","incident_id":{"$numberInt":"512"},"reports":[],"editors":["Khoa Lam"],"date":"2023-03-17","Alleged deployer of AI system":["openai"],"Alleged developer of AI system":["openai"],"Alleged harmed or nearly harmed parties":["openai","pseudonymized-law-professor"],"nlp_similar_incidents":[{"incident_id":{"$numberInt":"13"},"similarity":{"$numberDouble":"0.9970689415931702"}},{"similarity":{"$numberDouble":"0.9969437718391418"},"incident_id":{"$numberInt":"267"}},{"similarity":{"$numberDouble":"0.996849000453949"},"incident_id":{"$numberInt":"138"}}],"editor_similar_incidents":[],"editor_dissimilar_incidents":[],"tsne":{"x":{"$numberDouble":"0.7884930967237823"},"y":{"$numberDouble":"-0.3850890885158578"}}}
```

CC @LKchemposer

**Comment by kepae** [comment]
@lmcnulty would you like to consider this resolved with https://github.com/responsible-ai-collaborative/aiid/pull/2130 ?
