### ISSUE TITLE
Add MTF Grant to Landing Page

### ISSUE THREAD

**Issue by smcgregor** [responsible-ai-collaborative/aiid#1722]
Add a new block to the "The Responsible AI Collaborative" section titled "Sponsors and Grants" on the landing page with greater prominence than the in-kind sponsors with a logo link to: https://foundation.mozilla.org/en/what-we-fund/awards/mozilla-technology-fund-mtf/

We have one more grant logo that will be going into this section in short order.

**Comment by clari182** [comment]
@smcgregor what would be the text for this sponsor? The one that goes inside the Modal. Thanks!

**Comment by smcgregor** [comment]
```
Mozilla Foundation

The Responsible AI Collaborative received a $50,000 grant from the Mozilla Technology Fund for the development of AI risk checklists. For more details on the project, visit the cohort [launch announcement](https://foundation.mozilla.org/en/what-we-fund/awards/mozilla-technology-fund-mtf/) and follow the Collab blog as we announce advancements.

(MTF/Mozilla Foundation logo here)
```
