### ISSUE TITLE
Remove Bootstrap from Site

### ISSUE THREAD

**Issue by kepae** [responsible-ai-collaborative/aiid#1732]
Today's blog post is great and has a ton of supporting link references. However, I almost missed them because they appear as slightly bolded text of the same color as the standard text. Hovering doesn't highlight or change the appearance in any way, either (though the cursor changes to the "click" format).

https://incidentdatabase.ai/blog/chatgpt-incidents-and-issues/

<img width="791" alt="image" src="https://user-images.githubusercontent.com/4238598/225107017-3cf50c70-d2ac-4d34-a940-af65d6be52aa.png">

I'm not familiar with the styling resources for the site at large, but other links, such as the variant paragraph description, are blue and more clearly distinguishable.

<img width="965" alt="image" src="https://user-images.githubusercontent.com/4238598/225107357-dc0f78b6-8351-4436-bb72-187d3a38bcb2.png">

**Comment by lmcnulty** [comment]
This arose when we added the Tailwind Typography plugin. The [Tailwind site itself](https://tailwindcss.com/docs/typography-plugin) has bold. uncolored links, but they're underlined. None of the links on our site have underlines, so this might be a conflict between a pre-existing global style and Tailwind Typography.

**Comment by kepae** [comment]
Seems so! Perhaps the best option is to tackle it at the config level with [a custom theme for `--tw-prose-links`](https://tailwindcss.com/docs/typography-plugin#element-modifiers).

Otherwise, can maybe use the [`prose-a` element modifier](https://tailwindcss.com/docs/typography-plugin#element-modifiers) in the template. But, the config level sounds better for consistency.

(I'm trying to prototype it locally, but managing my node versions first...)

**Comment by kepae** [comment]
The config looks more involved and has site-wide impact (?), but modifying the template allows a quick look.

Changing the template: `site/gatsby-site/src/templates/post.js`

```javascript
<StyledMainWrapper className="prose prose-a:text-blue-600 hover:prose-a:text-blue-500">
  <MDXProvider components={MdxComponents}>{children}</MDXProvider>
  <Author>By {mdx.frontmatter.author}</Author>
</StyledMainWrapper>
```
-->
<img width="659" alt="image" src="https://user-images.githubusercontent.com/4238598/225136844-60edf07c-9845-4718-a354-24ce9eb690da.png">

(These are perhaps _too blue_? Not my call.)
