### ISSUE TITLE
Incident Report Submission Form: Description validation fails when text contains newline

### ISSUE THREAD

**Issue by kepae** [responsible-ai-collaborative/aiid#1745]
When entering text into the optional "Description" field of an incident report submission, entering a newline will cause the field to fail validation and report a misleading error: "Description must have at least 3 characters."

Reproduced:

![image](https://user-images.githubusercontent.com/4238598/226027825-11b81e78-22fa-4911-9bee-f876f6c3e963.png)

**Comment by smcgregor** [comment]
I have been thinking about having some form of wiki-like area and/or talk page that would have a much longer synthesis of reports, but at present our descriptions are meant to be pretty spare. This would mean the error message is wrong, but the validation blocking submission would not be.

Regardless, in the short term we can fix the validation message.
