### ISSUE TITLE
Email user when submission is accepted

### ISSUE THREAD

**Issue by lmcnulty** [responsible-ai-collaborative/aiid#1759]
If the upcoming [user management changes](https://github.com/responsible-ai-collaborative/aiid/issues/1703) will associate submissions with user accounts, I believe that would give us the ability to email users when one of their submissions is accepted. I think this would make them more likely to return to the site and submit future reports.

**Comment by smcgregor** [comment]
+1

**Comment by Janetbananet** [comment]
+1 @LKchemposer You were talking about this! Adding into our Community Editor Project list of system support items :)

**Comment by Janetbananet** [comment]
@lmcnulty A related point is automatically subscribing the user to the report that has been submitted so that he/she receives emails whenever that report is updated. Should I make a separate GitHub issue for this or does it make sense to add to this issue?

**Comment by Janetbananet** [comment]
I think there are a category of issues under the umbrella "User Account" that relate to the Community Editor Project. I will create a parent item and associate this issue by checklist so that we can track them together.
