### ISSUE TITLE
Create a mockup for a new Variants UI

### ISSUE THREAD

**Issue by pdcp1** [responsible-ai-collaborative/aiid#1768]
Design a new Variants UI that allows the user to create chat conversation type variants like the ones on ChatGPT

# [Figma Design](https://www.figma.com/file/HY3xPYfL5Rhr1WBFDDtwiU/RAIC-team-library?node-id=711%3A9&t=DxhDCF5XWv0MSxSP-1)

The idea of this new design is to add a new free text field called `Input and output as a chat conversation` which allows a larger conversation text using the list markdown syntax `- text` to separate chat prompts and chat resposes.

### Incident Variants list

<img width="470" alt="image" src="https://user-images.githubusercontent.com/6564809/228371494-1055fc59-5d5b-40e5-ad0c-5df540963e11.png">

### Incident Variant form

<img width="1151" alt="image" src="https://user-images.githubusercontent.com/6564809/228943156-f5fd8513-97cb-4288-9a56-6b3e89134c2c.png">

**Comment by pdcp1** [comment]
@smcgregor Please let me know what do you think about this design for the chat conversation as a variant

**Comment by pdcp1** [comment]
@smcgregor [Figma design](https://www.figma.com/file/HY3xPYfL5Rhr1WBFDDtwiU/RAIC-team-library?node-id=711%3A9&t=DxhDCF5XWv0MSxSP-1) and screenshots here were updated, please take a look.

## Expected behaviour

1. Current `Input and circumstances` and `Output and outcomes` fields should be migrated to the existing `text` together. These two fields won't be used anymore.
2. A new Array text field will be added to the `reports` collection.
3. In the Variant form:
3.1. `Incident Date` field will be displayed (optional)
3.2. `Description of Incident Circumstances` field will be displayed. This field will store the value on the existing `reports.text` field. (optional)
3.3. New `Inputs / Outputs` array of texts field is added to the form. (optional)
3.4. The user can add multiple `Inputs / Outputs` texts that may represent a chat conversation.
4. The user should enter at least one of the text fields (`Description of Incident Circumstances` or `Inputs / Outputs`)

**Comment by smcgregor** [comment]
Expected behavior looks great. Some comments:

1. When you add the trash button after the user clicks for another row, it makes me think it is related to the collection rather than the row. Maybe add text indicating "Add Row" and "Delete Row" within their respective buttons.
2. Let's add something indicating the user account that is submitting the report (i.e., let's allow for setting "submitter" here). This will likely be updating with @cesarvarela's incoming changeset.

**Comment by smcgregor** [comment]
Moving to #1779
