### ISSUE TITLE
Submission Queue UX Changes

### ISSUE THREAD

**Issue by Janetbananet** [responsible-ai-collaborative/aiid#1787]
Currently, there is no way to interact with the submissions review queue beyond approve/reject. With the planned increase in submissions and Editors working with them, we need capabilities to sort/group/filter and coordinate Editing efforts in the queue.

Issues (Stories) so far include:

- [x] #1785 
- [ ] #1786
- [x] #1809 1809

**Comment by Janetbananet** [comment]
Whoever picks this one up needs to work with @LKchemposer since he will be the primary user for this feature at first.

**Comment by kepae** [comment]
Closing this in favor of tracking the last remaining item: #1786
