### ISSUE TITLE
Add autocomplete to Developers, Deployers, and Harmed Parties

### ISSUE THREAD

**Issue by Janetbananet** [responsible-ai-collaborative/aiid#1788]
The Developers, Deployers, and Harmed Parties fields in the Submission Form are all currently free-form text fields. This can cause a splintering effect in the Entities table because people may use slightly different names (ex: "Meta" vs "Meta Platforms") which will degrade the built in analytics and counts in the Entities table.

Adding an autocomplete feature based upon existing entries will help alleviate this issue.

**Comment by smcgregor** [comment]
Added this to the backlog
