### ISSUE TITLE
Fallback Image Not Displaying

### ISSUE THREAD

**Issue by smcgregor** [responsible-ai-collaborative/aiid#1797]
https://incidentdatabase.ai/cite/6/

I suspect what is happening here is that the fallback image is rendering faster than the 404 is returning, so it renders the fallback then the 404 replaces the fallback image.

<img width="1099" alt="Screen Shot 2023-03-30 at 9 39 27 PM" src="https://user-images.githubusercontent.com/64780/229024093-f22dfcfb-2894-4a71-9957-68691e6db9ba.png">

**Comment by smcgregor** [comment]
@clari182 @pdcp1 @cesarvarela can one of you take this on Friday?

**Comment by smcgregor** [comment]
@clari182 this is still an issue, primarily on the sidebars.

Examples:
https://staging-aiid.netlify.app/cite/14/
https://incidentdatabase.ai/cite/14
https://staging-aiid.netlify.app/cite/15/
https://incidentdatabase.ai/cite/15
https://incidentdatabase.ai/cite/16/
https://staging-aiid.netlify.app/cite/16/
https://incidentdatabase.ai/cite/17/
and more.

Also, polling the server to check for the existence of the image, then displaying the image, is not a good longer term solution. We still need at least a shorter term fix though.

**Comment by smcgregor** [comment]
I also think this change set may be preferentially using the old fallback image rather than the new dynamically generated image, which looks much better.

**Comment by clari182** [comment]
You're right, I thought it was the image from cloudinary that were failing but it's actually the fallback. I'm working on a fix now to remove the fetch logic and improve the current cloudinary logic to display the fallback on error.
