### ISSUE TITLE
Flaky tests

### ISSUE THREAD

**Issue by cesarvarela** [responsible-ai-collaborative/aiid#1801]
Tests that are hugely flaky:

- `Should add a new Variant - Unauthenticated user`
- `Should display correct Citation`
- `Should show a list of related reports` (seems to have been fixed by #1800) 

They can be seen failing here: https://github.com/responsible-ai-collaborative/aiid/pull/1784

**Comment by cesarvarela** [comment]
https://app.netlify.com/sites/cesarvarela-staging/deploys/6427349d6a002f0008d841f9

**Comment by clari182** [comment]
I'll work on `Should display correct Citation`

**Comment by clari182** [comment]
Nevermind just saw you're already working on those

**Comment by cesarvarela** [comment]
If that doesn't work, I'll skip them until we have a proper fix.

**Comment by cesarvarela** [comment]
It's been a while since I've seen flake coming from these.
