### ISSUE TITLE
Image component is loading original image instead of optimized one

### ISSUE THREAD

**Issue by cesarvarela** [responsible-ai-collaborative/aiid#1820]
We should be using Cloudinary's API to process the image and fetch the optimized version instead of the full version, which looks pixelated and it is heavy to load:

![image](https://user-images.githubusercontent.com/1172479/229616103-6384fbe3-072f-4f93-8ca4-7455928f4ea6.png)

If you right-click on it:

![image](https://user-images.githubusercontent.com/1172479/229616961-c87fe677-3e21-4a70-95b4-248943f0bd95.png)

**Comment by smcgregor** [comment]
Good thing our Cloudinary plan has high caps. Adding this to backlog...

**Comment by clari182** [comment]
Closing as this was fixed with #1819
