### ISSUE TITLE
Migrate Signups to Google Groups

### ISSUE THREAD

**Issue by smcgregor** [responsible-ai-collaborative/aiid#1829]
I believe our subscription process is to have people either sign up for an account or to collect their emails and we manually sign them up for the Google Group (i.e., the newsletter). I went into the backend to do the Google Group signup and I am not sure what I should be migrating...

**Comment by smcgregor** [comment]
@pdcp1 I think you may know what I am supposed to do here.

**Comment by pdcp1** [comment]
@smcgregor I think we already discussed this as part of this [issue](https://github.com/responsible-ai-collaborative/aiid/issues/1830).
Let me know if you have any questions.

**Comment by smcgregor** [comment]
Thanks, closing.
