### ISSUE TITLE
Sidebar footer overlaps hamburger menu at intermediate screen widths

### ISSUE THREAD

**Issue by lmcnulty** [responsible-ai-collaborative/aiid#1837]
![image](https://user-images.githubusercontent.com/25443411/230426013-9279ea20-741e-4134-a17d-b09a561504d9.png)

^At the bottom-left corner

**Comment by clari182** [comment]
Hey @lmcnulty, can you check if you're still able to reproduce this issue? I couldn't so maybe it has been fixed and we can close it out. Thanks!
