### ISSUE TITLE
Submission leaderboards should be shown side-by-side

### ISSUE THREAD

**Issue by lmcnulty** [responsible-ai-collaborative/aiid#1839]
There are separate leaderboards for "First Incident Reports", "Distinct Incidents Reported" and "Total Incident Reports." When the screen space is available, these should be shown side-by-side, as their length makes it uncomfortable to find the next one by scrolling.

![image](https://user-images.githubusercontent.com/25443411/230428409-1f1934c4-d8b4-4aaf-a6c7-8e8626fce076.png)

**Comment by pdcp1** [comment]
Closing this since it was already merged into Staging
