### ISSUE TITLE
Search Box Directly in Google Search

### ISSUE THREAD

**Issue by smcgregor** [responsible-ai-collaborative/aiid#1847]
I believe we can have a search box in Google search that connects directly into the Discover app.

**Comment by kepae** [comment]
I can confirm that according to Google Search Console, the site is indexed and the "sitelinks searchbox" is picked up for all supported languages. This can also be confirmed with the rich results test here:
https://search.google.com/test/rich-results

Regardless of correct configuration, it's not guaranteed to show in search results:

https://developers.google.com/search/docs/appearance/structured-data/sitelinks-searchbox
> Important: Google doesn't guarantee that a sitelinks search box will be shown in search results. Additionally, using the sitelinks search box markup doesn't make it more likely that a sitelinks search box will be shown. For a list of common reasons why Google may not show structured data in search results, review the [General Structured Data Guidelines](https://developers.google.com/search/docs/appearance/structured-data/sd-policies)

We might instead seek to add structured data to other core pages – namely the `/cite/incident` (and possibly `/cite/report` pages: https://github.com/responsible-ai-collaborative/aiid/issues/2229) – if we want to improve the SEO.

I'm going to close this in favor of tracking structured data possibilities on pages.
