### ISSUE TITLE
Keep the autocomplete menu of taxonomy classifications open after selection

### ISSUE THREAD

**Issue by lmcnulty** [responsible-ai-collaborative/aiid#1857]
From Nikiforos:

> Suggestion: when selecting classifications relevant to the snippet from the dropdown, when I click one the list closes. To add another, I have to click again to spawn the list. It'd be very helpful if it wasn't hidden and just removed my selection, such that I could multi-select with half the clicks. 

I thought this would be annoying to do, but it turns out [it's a supported behavior](https://ericgio.github.io/react-bootstrap-typeahead/#behaviors).

**Comment by smcgregor** [comment]
@lmcnulty I think this is for your backlog?
