### ISSUE TITLE
Convert Quick URL submissions to full submission forms

### ISSUE THREAD

**Issue by Janetbananet** [responsible-ai-collaborative/aiid#1860]
The process for turning a quick URL entry into a submission in order to ingest is manual and cumbersome: it currently requires a copy/paste of the quick URL into a new submission form followed by deleting the entry in the quick-URL submissions queue.

We need a way to more easily convert the quick URL entries into a submission form. (There may be a couple of different options for how to approach this.)

**Comment by Janetbananet** [comment]
@LKchemposer

**Comment by smcgregor** [comment]
Closing this since we are going to combine queues per #1786
