### ISSUE TITLE
Improvement to RSS feed

### ISSUE THREAD

**Issue by leeomara** [responsible-ai-collaborative/aiid#1870]
Hello,

Very interesting project. I'd like to suggest that the RSS feed could be improved in a few ways.

For each item, I'd like to see included:
- description
- a link to each item's writeup in the database
- item date 

The following sample is from https://incidentdatabase.ai/rss.xml (last built Thu, 13 Apr 2023 18:10:39 GMT)

```xml
<item>
  <title><![CDATA[Italian privacy regulator bans ChatGPT]]></title>
  <link>https://www.politico.eu/article/italian-privacy-regulator-bans-chatgpt/</link>
  <guid isPermaLink="false">d8463cdc-5971-51c5-997d-192c0c46063b</guid>
  <enclosure url="https://res.cloudinary.com/pai/image/upload/d_fallback.jpg,w_800/v1/reports/www.politico.eu/cdn-cgi/image/width%3D1200%2Cheight%3D630%2Cfit%3Dcrop%2Cquality%3D80%2Conerror%3Dredirect/wp-content/uploads/2023/03/31/iStock-1468873339-scaled.jpg" length="0" type="image/jpeg"/>
</item>
<item>
  <title><![CDATA[We tested a new ChatGPT-detector for teachers. It flagged an innocent student.]]></title>
  <link>https://www.washingtonpost.com/technology/2023/04/01/chatgpt-cheating-detection-turnitin/</link>
  <guid isPermaLink="false">156f90c9-0957-53c3-989b-eb5368ff3f11</guid>
  <enclosure url="https://res.cloudinary.com/pai/image/upload/d_fallback.jpg,w_800/v1/reports/upload.wikimedia.org/wikipedia/commons/thumb/9/93/The_Logo_of_The_Washington_Post_Newspaper.svg/500px-The_Logo_of_The_Washington_Post_Newspaper.svg.png" length="0" type="image/jpeg"/>
</item>
```

## Description

The example feed (https://deploy-preview-97--aiid.netlify.app/rss.xml), from [#45](https://github.com/responsible-ai-collaborative/aiid/issues/45#issuecomment-786763554) demonstrated including a description in the `<description>` tag, however the current implementation (based on #97) doesn't include description.

## Link

Right now there is no way to go from an item in the RSS feed to the Incident Database. It would be nice if the abbreviated description included a link to the IncidentDatabase page about that report.

Currently the RSS feed includes a link to the "source". I think this is a good idea and worth keeping.

E.g. for "Italian privacy regulator bans ChatGPT", the link is to https://www.politico.eu/article/italian-privacy-regulator-bans-chatgpt/. I think it would be good to also include a link the particular report (e.g. https://incidentdatabase.ai/cite/513/#r2900) and/or to the incident (e.g. Incident 513: ChatGPT Banned by Italian Authority Due to OpenAI's Lack of Legal Basis for Data Collection and Age Verification / https://incidentdatabase.ai/cite/513

## Date

Currently RSS readers have no reference about item dates, other than when their reader first saw them. Including the report date would improve this.

**Comment by smcgregor** [comment]
Hi @leeomara! The RSS feed was an early user request, but we have not touched it for a long time. Many of the data elements that are now available were not available when the feed started. For the description, would you want the incident description or some preview of the link content?

**Comment by leeomara** [comment]
Hi @smcgregor 

Totally understandable, and I appreciate that you already have an RSS feed.

I'm still new to this project, so take this perspective in that context. I think the incident description is more appropriate for the `<description>` than the content at the other end of the "source" link.

**Comment by smcgregor** [comment]
Sounds good. I am going to add this to the backlog. Feel free to pick it up if you would like to develop, otherwise I think this will get picked up in a ~month.

Note for whoever picks this up: I would guess the RSS feed hooks into the reports collection rather than into the incidents collection. This would mean it presents both incident reports and issue reports. The incident reports will have associated incident descriptions, while the issue reports will not. For issue reports, I think the description should be "this news report presents risks that may develop into an incident."

**Comment by smcgregor** [comment]
(increased priority to get this more attention)
