### ISSUE TITLE
CSET Taxonomy Consistency Check Tool

### ISSUE THREAD

**Issue by smcgregor** [responsible-ai-collaborative/aiid#1879]
CSET has multiple people that annotate incidents independently of one another in copies of their new taxonomy. Once the annotators reach a reasonable degree of consistency between each other, they no long need to have as many checks of their annotations and the extra taxonomies are no longer used. However, CSET _does_ need a tool that will help them identify when there are inconsistencies. When they identify inconsistencies talk with one another and resolve the differences.

While the ideal tool is one that compares each instance of the CSET taxonomies and outputs only those cases where there are differences, this is also a pretty big implementation effort since it would require doing a bunch of things like sorting and matching tags, filtering fields that are full text and should not match, etc. All this work is likely to be one-off and not serve any general case. I am going to set this option aside and consider the following options.

**Add to Incident Table View**

A better approach is likely to just make it easy to look at the classification columns for each of the taxonomy replicates and visually check them for differences. The CSET columns could be collated and displayed on the current incident table view.

**New Extensible Table View**

Another way to table inspect classification consistency would be to build a table view for the taxonomies. Specifically, a table view where you can turn on/off columns across all taxonomies for each incident. CSET would then be able to visually inspect collections of columns for consistency. As an added benefit, it would be possible compose views of the tabular data related to incidents. We could (eventually) put the column configurations in the query string of the page to save state.

Why is this better than adding to the current table? We can ship it faster while it is still messy since CSET can use this now. We can then tighten it down, then eventually deprecate the old table.

**Hook tableau or similar into API**

Direct export to highly dynamic table view

**Export to CSV**

Easy enough...

**Priorities?**

I think we do the extensible table view if we can get it into prod within a week without displaying it to the public. Otherwise the CSV export is likely the way to go.

**Comment by cesarvarela** [comment]
The mvp has been depoloyed
