### ISSUE TITLE
Configure Cypress Dashboard (Cloud)

### ISSUE THREAD

**Issue by cesarvarela** [responsible-ai-collaborative/aiid#1894]
We had it working before, but now it seems it is not working:

![image](https://user-images.githubusercontent.com/1172479/232921796-bec0c7c0-6519-4cbd-8368-689d95ec5af9.png)

It helps with keeping tabs on flake and test suite time.

**Comment by pdcp1** [comment]
@cesarvarela I will add back the dashboard integration but it looks like the flaky test analysis is not included on our plan 😕 
<img width="387" alt="image" src="https://github.com/responsible-ai-collaborative/aiid/assets/6564809/edab635f-ee63-4280-a468-35115abf84bf">

**Comment by pdcp1** [comment]
It's done
