### ISSUE TITLE
Awkward Layout on leaderboard

### ISSUE THREAD

**Issue by smcgregor** [responsible-ai-collaborative/aiid#1912]
<img width="1158" alt="Screen Shot 2023-04-20 at 12 52 14 PM" src="https://user-images.githubusercontent.com/64780/233473364-e61a7895-332e-44f6-8c7a-ccee0d0397e5.png">

Options:
* make all the leaderboards the same height with the ability to expand to display all
* Densely pack the leaderboards
* Something else?

**Comment by Janetbananet** [comment]
I'd argue to make the leaderboards the same height, and only display the top 3 - 5 individuals before expanding.

It's also hard to know what all the categories are. Could we solve this by making the leaderboards into a grid on the page (e.g. 3 across?) With a really short height on each of the boards this would make it easy for someone to see all the available categories above the fold.

If we collapse these tables, then we're going to have an issue with people trying to search for individuals/entities. For instance, if I (Janet) want to see how many submissions I have made, I hit command F and can easily search the page. This will go away by collapsing the boards. Can we add a search bar at the top of the webpage?

Finally, I have an issue with the category titles. "First Incident Reports", "Distinct Incident Reports", and "Total Incident Reports" are not intuitive to an outsider. How about:
"First Incident Reports" -> "New Incidents Contributed"
"Distinct Incident Reports" -> "Reports added to Existing Incidents"
"Total Incident Reports" -> "Total Report Contributions"

**Comment by smcgregor** [comment]
Maybe we should convert the leaderboards to the table presentation, which has sorting, filtering, etc.? We can also highlight the top three outside the table...

**Comment by Janetbananet** [comment]
I like that idea, both the sortable table and highlighting top 3 in each category outside the table.

**Comment by lmcnulty** [comment]
I think the simple solution is to make each leaderboard a fixed height with individual scrolling. Then searching for your name will still work, but the layout will be clearer and less cluttered. I think it would make sense to split the submitter leaderboards and the author/publication ones into separate rows.

If we make it a sortable table, I think we'll probably want to do that after we rework the relationship between submitters and user accounts.

**Comment by smcgregor** [comment]
+1 to Luna's suggestion.

**Comment by Janetbananet** [comment]
Also +1 to Luna's suggestion.

**Comment by pdcp1** [comment]
Agreed! I will proceed with the approach that Luna suggested.

**Comment by pdcp1** [comment]
> "First Incident Reports" -> "New Incidents Contributed"
> "Distinct Incident Reports" -> "Reports added to Existing Incidents"
> "Total Incident Reports" -> "Total Report Contributions"

@smcgregor What do you think about these title changes? Should we change them too?

**Comment by smcgregor** [comment]
Yes please, that is much better. :)
