### ISSUE TITLE
Broken Image in Safari browser on home page

### ISSUE THREAD

**Issue by Janetbananet** [responsible-ai-collaborative/aiid#1916]
The image corresponding to the latest blog post on the home page is broken when I view it on the Safari browser (see screenshot below).

![image](https://user-images.githubusercontent.com/28989465/233690746-94f1bbbd-5d05-493b-97de-ac732d9c5296.png)

**Comment by smcgregor** [comment]
I don't see that on Safari. Can you look one more time?

**Comment by smcgregor** [comment]
Can you close and reopen Safari and see if it still happens? If so, let's do a live session so I can look at your JS console.

**Comment by Janetbananet** [comment]
It's still happening in my Safari browser. Ping me on Slack when you'd like to do a live session on this.

**Comment by smcgregor** [comment]
Will do.

**Comment by smcgregor** [comment]
I did a live debug session with @Janetbananet. It looks like it was an older version of safari that did not support the webp file format. We'll reopen this if that proves not to be the case.
