### ISSUE TITLE
Replace Wordcounts panel on landing page with a web form that captures emails

### ISSUE THREAD

**Issue by Janetbananet** [responsible-ai-collaborative/aiid#1917]
We want to make it visually loud and functionally quick and easy for site visitors to express their interest in keeping up with the AIID. Suggest replacing the "Wordcounts" panel on the landing page with a web form that captures emails without clicking through.

Questions to consider:
- What should the language be in the panel?
- What type of image/visuals can call attention to the panel?
- Should this have a captcha test to prevent spam?
- How will the emails input into the web form be added to the email subscriber list (currently captured in the gmail listserv)? Is this a manual or automatic process?

@smcgregor Kicking this to you to add your inputs and prioritize/assign.

**Comment by Janetbananet** [comment]
Here are some thoughts on words/design.

I like the Montrealethics.ai version of this, although the verbiage would be different.
![image](https://user-images.githubusercontent.com/28989465/233695356-fe3aea57-ee39-4e23-b38c-b128209f5c55.png)

Ideas for our verbiage:
Section Title:
"The AI Incident Briefing" 

Section Language:
Want to keep up with the latest on AI incidents? We collect incidents from all over the web in our database.
Found an AI incident online or in our database and want to add or edit it? We need your help!

Subscribe to the AI Incident Briefing and get incident round-ups delivered straight to your inbox, and major organizational updates.

**Comment by Janetbananet** [comment]
@LKchemposer Would love your input from a marketing/verbiage perspective.

**Comment by Janetbananet** [comment]
Adding this comment from the conversation during the Engineering stand-up today: 
The problem to solve for is attracting website visitors to subscribe to email updates. The word counts panel is a space that can be replaced on the home page, but it is up for discussion what the best solve for this is.

**Comment by lmcnulty** [comment]
I think on adding this, we should fully split the UI for signing up for an account and signing up for the newsletter. The current sign up form that's split between subscribing to "major updates" and subscribing to new incidents is really unexpected.

![image](https://user-images.githubusercontent.com/25443411/234405762-be41f97c-7131-442a-97e2-daeffa080955.png)
