### ISSUE TITLE
Allow user to pause scrolling on taxonomies' pie charts

### ISSUE THREAD

**Issue by samuelmcurtis** [responsible-ai-collaborative/aiid#1930]
Hi, I think it would be helpful if the pie charts on the [taxonomies page](https://incidentdatabase.ai/taxonomies/) were to stop scrolling if a user clicks on that pane. It is difficult to read or interact with them otherwise.

**Comment by smcgregor** [comment]
@samuelmcurtis Agreed...The pie charts are available on the taxonomy detail pages as well... How about making it so that the pie charts on the index page don't support interaction, but clicking on them would open and scroll to that specific pie chart in the detail page?

**Comment by samuelmcurtis** [comment]
I think that'd be a good solution!

**Comment by smcgregor** [comment]
Added to backlog. Someone will pick it up fairly soon. Thanks for the issue!

**Comment by lmcnulty** [comment]
The fix is in production now.
