### ISSUE TITLE
Accidentally collapsing incident reports during text selection

### ISSUE THREAD

**Issue by npit** [responsible-ai-collaborative/aiid#1948]
When reading through an incident report for annotation (e.g. [506](https://incidentdatabase.ai/cite/506/#r2893)) apart from clicking the "Read more" and "Collapse" dynamic buttons, you can also do so by clicking the border of the panel (a few pixels in the perimeter).

While useful (you don't have to scroll down to the end of the report to collapse it), it turns out that it's easy to click it by mistake when annotating for GMF, where you're often clipping out text segments as snippets relevant to classifications.

This happens because to do that snippet extraction, you have to select the report text to copy-paste. If you release the click-and-drag over that border area (pretty common, since you're often selecting or dragging the mouse to the edge of the text area), the panel collapses and you have to painfully track back and repeat.

Some naive fix ideas off the top of my head:
- Make only the left or right side trigger the collapse
- Add a floating "collapse" button that follows you while you scroll
- Add a floating "goto report start" button that follows you while you scroll (which is useful functionality in general), duplicate a "collapse" button there
- If no workaround is possible, add some visual aid to warn users that the cursor is over the danger zone (e.g. different color, dynamic highlight, etc)

@smcgregor 's thoughts:
> I think this problem commonly occurs when it triggers on the mouse-up event rather than the click event. If you are highlighting text, you will often mouse-up in the boarder, but the click is on the text. If we make the border require a full click rather than a mouse up for the toggle expand/collapse, then I think you should be good. Agreed/disagree/need to try?

**Comment by clari182** [comment]
@smcgregor @npit 
I've been working on this and I actually like the idea of the floating collapse button. I think it wasn't very clear that the margin was clickable which could lead to frustration.

I've been working on a PR [here](https://github.com/responsible-ai-collaborative/aiid/pull/2011) and it can be tested [here](https://deploy-preview-2011--staging-aiid.netlify.app/).

Let me know your thoughts on this!

**Comment by npit** [comment]
Tested a few reports, works great! Props for pinning the just-collapsed report to the top of the list too, so that you don't have to look for it!

**Comment by smcgregor** [comment]
Works great for me!
