### ISSUE TITLE
Test `Successfully filter and edit incident 112` is failing with unrelated error

### ISSUE THREAD

**Issue by cesarvarela** [responsible-ai-collaborative/aiid#1967]
Error: The following error originated from your application code, not from Cypress.
7:11:03 PM:   > A profile was never fetched for this user
7:11:03 PM: When Cypress detects uncaught errors originating from your application it will automatically fail the current test.
7:11:03 PM: This behavior is configurable, and you can choose to turn this off by listening to the `uncaught:exception` event.

**Comment by pdcp1** [comment]
Closing this since this test is not failing in the last days on Staging and Production.
