### ISSUE TITLE
Cannot submit new incident?

### ISSUE THREAD

**Issue by LKchemposer** [responsible-ai-collaborative/aiid#1969]
I was trying to submit this report `https://www.reuters.com/article/us-storm-sandy-newjerseytransit/exclusive-readying-for-sandy-nj-transit-erred-in-modeling-storm-idUSBRE90B00I20130112` as a new incident. I filled in all the required fields, but I cannot submit, got yellow flag.

**Comment by lmcnulty** [comment]
Hmm... I was able to submit it. I didn't assign an incident ID. Is it a new report of an old incident?

**Comment by cesarvarela** [comment]
It might have to do with this: https://github.com/responsible-ai-collaborative/aiid/pull/1964

@smcgregor, what roles does Khoa have?

**Comment by smcgregor** [comment]
@cesarvarela just `admin`

**Comment by cesarvarela** [comment]
@LKchemposer I'll need more info to reproduce this, maybe a screenshot of the submit form, a screenshot of the yellow flag,  a screenshot of the network panel from the Dev Tools, etc.

**Comment by cesarvarela** [comment]
@LKchemposer should I close this?
