### ISSUE TITLE
Update mongodb schema rules

### ISSUE THREAD

**Issue by cesarvarela** [responsible-ai-collaborative/aiid#1974]
- [x] candidates: Everybody is allowed to write/search/delete (we might want to keep it as it is)
- [x] classifications: The taxonomy-specific roles do not check the classification namespace, so taxonomy_editor is equivalent to taxonomy_editor_cset
- [x] entities: anybody can create new entities (we might want to keep it as it is)
- [x] incidents:
   - The incident_editor role doesn't allow for editing incidents.
    - The Add Variant rule should be joined with the default rule.
- [x] reports:
   - incident_editor role can't edit reports.
- [x] translations db
    -  incident_editor role can't edit translations

**Comment by kepae** [comment]
@pdcp1 if everything was covered in #2406, would you like to close this?

**Comment by pdcp1** [comment]
> @pdcp1 if everything was covered in #2406, would you like to close this?

Yes, I double checked and everything in this issue was covered in #2406
