### ISSUE TITLE
Duplicated Open AI entity

### ISSUE THREAD

**Issue by cesarvarela** [responsible-ai-collaborative/aiid#1977]
![image](https://github.com/responsible-ai-collaborative/aiid/assets/1172479/28d0fb53-c129-45bd-ba4a-519dfd4ced58)

Looks like one was submitted with `OpenAI` and another as `Open AI`

**Comment by smcgregor** [comment]
Updated to OpenAI on the one errant one. The incident in question also concerns `Stability AI`, which is likely how this happened. CC @LKchemposer
