### ISSUE TITLE
Create list of user accounts 

### ISSUE THREAD

**Issue by cesarvarela** [responsible-ai-collaborative/aiid#1984]
From https://github.com/responsible-ai-collaborative/aiid/pull/1951#issuecomment-1541327624

I need a list of the first and last names, user ids, and emails as they are shown on the user admin table.

This will be used to create a migration to link submissions and reports to user accounts.

Related to #1783

**Comment by kepae** [comment]
@cesarvarela can this be closed?

**Comment by cesarvarela** [comment]
yup
