### ISSUE TITLE
Fix AWS SDK warning during build

### ISSUE THREAD

**Issue by cesarvarela** [responsible-ai-collaborative/aiid#1985]
```
8:12:01 PM: error (node:4041) NOTE: We are formalizing our plans to enter AWS SDK for JavaScript (v2) into maintenance mode in 2023.
8:12:01 PM: Please migrate your code to use AWS SDK for JavaScript (v3).
8:12:01 PM: For more information, check the migration guide at https://a.co/7PzMCcy
```

I think this is related to the `gatsby-source-s3` plugin.

**Comment by pdcp1** [comment]
There is an open issue https://github.com/JoshuaWalsh/gatsby-plugin-s3/issues/423 on the `gatsby-plugin-s3` package to update the `aws-sdk` package to v3, but they say that they don't have time to work on it 😕

**Comment by pdcp1** [comment]
There is a PR open to solve this https://github.com/gatsby-uc/gatsby-plugin-s3/pull/457. As soon as this PR is merged and released we can update the package.
