### ISSUE TITLE
Discovery page bug when apply filters

### ISSUE THREAD

**Issue by pdcp1** [responsible-ai-collaborative/aiid#1990]
## Steps to reproduce

1. Go to Discover page
2. Search for `google`. 567 results are displayed
3. Apply filter Source: `theguardian.com`
4. 28 results should be displayed, but it displays 0 results

<img width="1284" alt="image" src="https://github.com/responsible-ai-collaborative/aiid/assets/6564809/304e927e-4f69-44a5-84b4-34421da6212e">

**Comment by smcgregor** [comment]
High priority on this one. Potentially `critical` depending on what is happening.

**Comment by lmcnulty** [comment]
It seems that the order matters. Search and then filter returns no results, but filter and then search does.

**Comment by pdcp1** [comment]
Closing this since it was already merged into Staging
