### ISSUE TITLE
GitHub Action for Restoring Staging DB from Prod Snapshot

### ISSUE THREAD

**Issue by smcgregor** [responsible-ai-collaborative/aiid#2010]
The staging database often drifts from the state of the production database. Further, there are times where we would like to run a deploy preview that has a migration and have the easy ability to roll that migration back after running the build. Both these problems can be solved with a GitHub action that pulls down the latest production DB snapshot and restores the staging DB from it. For this issue, let's create the GitHub workflow/action that allows a person to restore the staging DB from the production backup at the push of a button (i.e., when pushing the workflow button).

**Comment by pdcp1** [comment]
@cesarvarela 
In order to close this, we should test it on Prod using the GitHub action created: https://github.com/responsible-ai-collaborative/aiid/actions/workflows/mongodb-clone.yml
I don't have permissions to run the workflow

**Comment by kepae** [comment]
I wanted to test the news digest app (https://github.com/responsible-ai-collaborative/aiid/pull/2235) in staging and saw that it requires the candidates collection to be populated. I've come around to this. Running it in prod/master branch fails on step `Dump Production database`:

https://github.com/responsible-ai-collaborative/aiid/actions/runs/5940530087/job/16109308589#step:3:6
```
Run mongodump --uri=""
  mongodump --uri=""
  shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
2023-08-22T14:57:02.783+0000	Failed: can't create session: failed to connect to mongodb://localhost/: server selection error: server selection timeout, current topology: { Type: Single, Servers: [{ Addr: localhost:27017, Type: Unknown, Last error: connection() error occurred during connection handshake: dial tcp [::1]:27017: connect: connection refused }, ] }
Error: Process completed with exit code 1.
```

**Comment by pdcp1** [comment]
@kepae In order to use this Github Action we have to set some env values. I don't have permission, but maybe you can do that.
The instructions are on the README file section`Restoring Production database to Staging`.
Let me know if you need any assistance.

**Comment by kepae** [comment]
I updated the environment variables and ran this this week. All seems good, so closing now.
