### ISSUE TITLE
Being asked to submit an incident title and description even after linking to an already-existing incident

### ISSUE THREAD

**Issue by datherton09** [responsible-ai-collaborative/aiid#2049]
I was adding more incident reports to incident 541 and was presented with this in the form:

![image](https://github.com/responsible-ai-collaborative/aiid/assets/101356758/4f52db1d-3c02-4d07-a22c-f233efae11fb)

Khoa recommended that I submit a ticket regarding this and to leave the fields blank during submission in order to avoid potentially overriding any previous information.

**Comment by smcgregor** [comment]
@datherton09 you got here by clicking on `New Report` on this page? https://incidentdatabase.ai/cite/541

**Comment by datherton09** [comment]
Ah, I think what I did was submit the new report, then saw it go into the review queue. I then clicked the edit button of the new report in the queue to review the details, and noticed that even after linking it to 541 the fields were blank, prompting me to wonder what steps to take. That may not be a bug, but potentially opens up the potential for confusion?

**Comment by datherton09** [comment]
Adding a new incident response to an existing incident does lead to this form when filling out the details:

![image](https://github.com/responsible-ai-collaborative/aiid/assets/101356758/3b70aa7f-6900-406b-8da6-addb4b0cf5cb)

This does (at least for me) generate some confusion as an editor as to whether the details need to be filled out again.

**Comment by smcgregor** [comment]
Got it. I added this to the dev backlog.

I believe those fields will be ignored when it is added to an existing incident.

**Comment by datherton09** [comment]
Thanks! :)
