### ISSUE TITLE
Minor design issue: buttons become dark on hover in Discover incidents > Graph view

### ISSUE THREAD

**Issue by samuelmcurtis** [responsible-ai-collaborative/aiid#2084]
When hovering over incident cards in the Graph view, they become black, and the buttons on them become impossible to see.

<img width="642" alt="Screenshot 2023-06-10 at 10 34 34 AM" src="https://github.com/responsible-ai-collaborative/aiid/assets/64827107/9089fcaa-a9fe-49ed-a9b1-a4b7100aee35">

Please consider lightening the hover color, or making the buttons appear white on card hover.

🙏

**Comment by smcgregor** [comment]
Thanks Samuel, confirmed: https://incidentdatabase.ai/apps/discover/?display=compact&is_incident_report=true&page=1&sortBy=instant_search-en-featured

Added to the backlog with a higher priority (it should be a quicker fix).
