### ISSUE TITLE
Skeletons looking tiny

### ISSUE THREAD

**Issue by cesarvarela** [responsible-ai-collaborative/aiid#2116]
It defeats the purpose of a skeleton https://www.uxdesigninstitute.com/blog/whats-a-skeleton-screen/

<img width="1254" alt="image" src="https://github.com/responsible-ai-collaborative/aiid/assets/1172479/6fe10923-d1d4-4e21-8eed-b5babe3eee4a">

**Comment by clari182** [comment]
Looks like this has been fixed with the layout update
