### ISSUE TITLE
New Incident page layout is broken

### ISSUE THREAD

**Issue by pdcp1** [responsible-ai-collaborative/aiid#2120]
https://incidentdatabase.ai/incidents/new/

<img width="1798" alt="image" src="https://github.com/responsible-ai-collaborative/aiid/assets/6564809/66ff2187-5315-4fa5-80cc-0ccd1fa09338">

**Comment by smcgregor** [comment]
Confirmed. Weird it is just here.

**Comment by pdcp1** [comment]
Closing this since it was already merged into Staging
