### ISSUE TITLE
Submission Form – Bug where clicking Submit does not refresh the form

### ISSUE THREAD

**Issue by LKchemposer** [responsible-ai-collaborative/aiid#2126]
On the second time using the submission form in succession – i.e., after submitting a first report, clicking the `Submit` button does not refresh the form, giving the impression that the submission did not go through (despite there being a pop-up saying that it went through), prompting submitters to re-submit just in case, which creates duplicates.

This issue has been causing quite a few duplicates in the submission queue.

**Comment by LKchemposer** [comment]
Update: it seems that this bug occurs regardless of it being the second time use

**Comment by smcgregor** [comment]
@clari182 can you take a look at this?

**Comment by clari182** [comment]
Hey, @LKchemposer in what browser is this happening?
I can't reproduce the issue, I've tried Chrome, Firefox, and Safari. Is it on a specific step of the submission that this is happening?
