### ISSUE TITLE
Submission bug?

### ISSUE THREAD

**Issue by LKchemposer** [responsible-ai-collaborative/aiid#2132]
Could not submit the article <https://www.theverge.com/2020/8/18/21373316/nypd-facial-recognition-black-lives-matter-activist-derrick-ingram> Pop-up message `Was not able to create the report, please review the form and try again.` was not helpful.

**Comment by smcgregor** [comment]
"submit" means submitting the submit form or fetching the content?

**Comment by smcgregor** [comment]
Only this link, or all of them? One particular link should not cause this problem.

**Comment by LKchemposer** [comment]
I don't know of others, but this link ran into this problem.

**Comment by Janetbananet** [comment]
@LKchemposer Are you still experiencing this bug?

**Comment by pdcp1** [comment]
I am closing this since it cannot be reproduced anymore. Many changes to the submission form have been made since this was reported.
