### ISSUE TITLE
I cannot save changes to incident data

### ISSUE THREAD

**Issue by LKchemposer** [responsible-ai-collaborative/aiid#2139]
The `Save` button on the `Incident Editing Form` and the `Update` button on the `Table View Form` are grayed out, making it unavailable for me to save changes to edits to incident data (for incident 558). I am logged in as `admin`

<img width="760" alt="image" src="https://github.com/responsible-ai-collaborative/aiid/assets/39468345/c78aa822-581c-490c-afa9-380d600cd9b2">

<img width="760" alt="image" src="https://github.com/responsible-ai-collaborative/aiid/assets/39468345/e23a0f13-2205-4427-a103-8421ef465554">

**Comment by cesarvarela** [comment]
Can you try adding and removing text to the `Editor Notes` field?

We'll have a fix for prod soon.

**Comment by cesarvarela** [comment]
@LKchemposer the fix has been deployed
