### ISSUE TITLE
Typeset May & June Round Up Blog Post

### ISSUE THREAD

**Issue by Janetbananet** [responsible-ai-collaborative/aiid#2144]
Find the content here!
https://docs.google.com/document/d/1HYccouRKw7uIFQoFThTvY5-Aj-sKq_l-u4X2yH632Mc/edit?usp=sharing

Also needs translation.

**Comment by smcgregor** [comment]
@clari182 do you want to take this one? Worthwhile to do this on Prismic?

**Comment by clari182** [comment]
On it! 
I already did the logic to have old and new (Prismic) blog posts on the same page [here](https://deploy-preview-19--clarayoudale-staging.netlify.app/blog). The latest blog post is from Prismic and is a copy of the April roundup.

I can add the May & June round-up on Prismic as a test. The only issue is right now I'm on the free plan that only lets you have one user. Let me know how to proceed regarding this.

**Comment by smcgregor** [comment]
Is it live querying Prismic or SSRing Prismic? Maybe we have a shared login credential for the development period, then either pay or only have one user?
