### ISSUE TITLE
Update Contact Info on Website

### ISSUE THREAD

**Issue by Janetbananet** [responsible-ai-collaborative/aiid#2176]
Can we please update the contact page at https://incidentdatabase.ai/contact/ by replacing Sean's info as the AIID lead with Scott's? Can someone also please run a search on the website to see if Sean's contact info is listed anywhere else so that we can update there as well?

@SkotBotCambo Can you please provide the specific language you'd like to change?

Currently: AIID Lead: [Sean McGregor](https://seanbmcgregor.com/), sean 'at' incidentdatabase.ai
New: <<Scott to fill in>>

**Comment by smcgregor** [comment]
We'll update the contact page as soon as we have content. The "About" page also needs new content, specifically, the bios for new board members. Let's update the contact page then the about page?

**Comment by Janetbananet** [comment]
Yes, good call. Can we add a DSRI / UL blurb too? Or maybe we need to hold until we have more official language. I could see the about page having an iteration or two.

**Comment by smcgregor** [comment]
These pages are in the process of transitioning to Prismic as well, but I don't think we should wait. Perhaps we do something shorter term then can rewrite more easily at the transition time. I'll get some DSRI/UL language together.

**Comment by Janetbananet** [comment]
I split out the About page update to a separate GitHub issue #2178 
That way we can focus on updating contact info right away for this one.

**Comment by smcgregor** [comment]
Updated here: https://github.com/responsible-ai-collaborative/aiid/pull/2179

Please reopen if the details are different.
