### ISSUE TITLE
Create UI Figma mockup design for a new Incident history page

### ISSUE THREAD

**Issue by pdcp1** [responsible-ai-collaborative/aiid#2191]
## Figma design

https://www.figma.com/file/HY3xPYfL5Rhr1WBFDDtwiU/RAIC-team-library?type=design&node-id=1115%3A15&mode=design&t=7EgPDL38FM1ECjfJ-1

<img width="1293" alt="image" src="https://github.com/responsible-ai-collaborative/aiid/assets/6564809/c474bc3c-4ea6-4af1-9992-ff60347d25dc">

<img width="1284" alt="image" src="https://github.com/responsible-ai-collaborative/aiid/assets/6564809/c5bf4bb5-17c8-49c9-b9d0-37379abbfd1b">

## Development notes
Icon: `<FontAwesomeIcon icon={faClockRotateLeft} />`

**Comment by pdcp1** [comment]
@smcgregor This is the mockup for the incident version history page. The same idea applies to Report version history.
You can access the Figma file with the link in the issue description above.
Let me know your opinion or suggestions. And if you are OK, maybe we can proceed to implement it.

**Comment by smcgregor** [comment]
My comments:

1. I don't think we have editor's notes at the moment for justifying revisions. Are you proposing to add a field for this?
2. There should be an ability to look at the complete record at the revision since you need to know what you are restoring in total.
3. You are using a lot of column space for attributes that will be in common across the whole list of changes. It might make sense to go with a two column layout where the shared values are in a ribbon separating each revision. This gives a lot more space for showing revisions that may make multiple changes.
4. Everyone should be able to view the history, but only editors should be able to restore a past version.
5. Restoring should require confirmation.
6. Each revisions should likely be numbered in case there are multiple revisions on a single day.

@Janetbananet @LKchemposer @kateperk @kepae @SkotBotCambo any comments here?

**Comment by pdcp1** [comment]
@smcgregor 

_1. I don't think we have editor's notes at the moment for justifying revisions. Are you proposing to add a field for this?_

<img width="583" alt="image" src="https://github.com/responsible-ai-collaborative/aiid/assets/6564809/3e4958e1-7b1b-4d27-932b-cbf0bfda1a82">

We have `Editor notes` field on incidents and reports. I think it can be helpful to have an specific column to display that, but maybe it's better to treat that field as a regular field and display it in the `Changes` column only if it changes in that revision.

_2. There should be an ability to look at the complete record at the revision since you need to know what you are restoring in total._
I can add an option to see the full Incident/Report version 👍 

_3. You are using a lot of column space for attributes that will be in common across the whole list of changes. It might make sense to go with a two column layout where the shared values are in a ribbon separating each revision. This gives a lot more space for showing revisions that may make multiple changes._
I'm not clear about your comment. 
It is something like this?

| Description (before) | Description (after) | Text (before) | Text (after) | ... |
|----------------------|---------------------|---------------|--------------|-----|
|                      |                     |               |              |     |
|                      |                     |               |              |     |
|                      |                     |               |              |     |

_4. Everyone should be able to view the history, but only editors should be able to restore a past version._
👍 
_5.Restoring should require confirmation._
👍 
_6. Each revisions should likely be numbered in case there are multiple revisions on a single day._
Actually, now we have the date and specific timestamp of each revision, so we can add the hh:mm on that column.

**Comment by smcgregor** [comment]
1. I think of `Editor Notes` in this context as notes about the nature of the revision and not something that is characterizing the whole incident.
2. Date, Modified By, and Actions can all be a single row

**Comment by pdcp1** [comment]
@smcgregor I'm not sure if I understand correctly point number 3. This is how I interpreted your message. Please let me know if that is accurate or provide an example.

![image](https://github.com/responsible-ai-collaborative/aiid/assets/6564809/84926493-8ca6-414a-a78c-99a7b144da26)

**Comment by smcgregor** [comment]
Quick hack to show you what I am suggesting:
<img width="797" alt="Screenshot 2023-08-01 at 3 56 19 PM" src="https://github.com/responsible-ai-collaborative/aiid/assets/64780/9dc6f04d-7497-41df-9865-4602e7b3836b">


It could be much more artfully rendered, but this is the most efficient use of space when the edited contents might be quite long/wide.

**Comment by pdcp1** [comment]
Perfect, I got it now.
@smcgregor Do you think we are good to start with the development of this feature?

My plan is to develop this in three phases:
1. Version History page with the list of revisions and changes (read only)
2. Add the `View Full version` button and page (or modal)
3. Add the `Restore version` button, confirmation, and behavior.

**Comment by smcgregor** [comment]
@pdcp1 go ahead, it would be good to get more commentary but I don't think any commentary will result in making those efforts wasted time.

**Comment by pdcp1** [comment]
Closing this in favor of the development issues attached
