### ISSUE TITLE
Change Twitter logo to X logo

### ISSUE THREAD

**Issue by pdcp1** [responsible-ai-collaborative/aiid#2201]
## Share options
<img width="585" alt="image" src="https://github.com/responsible-ai-collaborative/aiid/assets/6564809/0cf9d638-34c6-4cbc-b45a-101836ff99f6">

## Footer
<img width="241" alt="image" src="https://github.com/responsible-ai-collaborative/aiid/assets/6564809/b088c5d5-5358-414e-be28-bd5960cfb638">

**Comment by smcgregor** [comment]
Let's hold off on this one for a bit. Twitter... err... "X" is a bit chaotic and people don't know what it is yet.

**Comment by cesarvarela** [comment]
![image](https://github.com/responsible-ai-collaborative/aiid/assets/1172479/e28cf41d-c711-4d42-a187-f7eae2b401e2)

**Comment by kepae** [comment]
The official brand guidelines for X have been about for a while, so per offline discussion, it might be time to commit the change and keep going onward. :-)

https://about.twitter.com/en/who-we-are/brand-toolkit

(plus, if we have to change it back somehow, it won't be us looking silly now. ;-) )

**Comment by kepae** [comment]
One more place needs changing -- the nav links in the header.
<img width="412" alt="image" src="https://github.com/responsible-ai-collaborative/aiid/assets/4238598/dadf97c4-cf9b-40e7-a732-a886304b5c38">

(The old logo is really hanging on for dear life (or persisting?) across the web.)

**Comment by pdcp1** [comment]
Closing this since it was already merged into Staging
