### ISSUE TITLE
Setup Cypress Code coverage

### ISSUE THREAD

**Issue by cesarvarela** [responsible-ai-collaborative/aiid#2214]
It will give us more visibility on what's lacking tests and keep track of coverage percentage over time.

https://docs.cypress.io/guides/tooling/code-coverage

**Comment by kepae** [comment]
Looking into this, we'll have to pay attention to how we merge coverage results from parallel tests, as suggested here:
https://docs.cypress.io/guides/tooling/code-coverage#Combining-code-coverage-from-parallel-tests

Alternatively, we could run all tests in serial on one runner in a periodic workflow/cron to calculate coverage.
