### ISSUE TITLE
Create and deploy an "empty" environment

### ISSUE THREAD

**Issue by cesarvarela** [responsible-ai-collaborative/aiid#2224]
To properly test #2128, we should have an environment that'll always be empty.

- [x] Create a new Atlas environment @smcgregor. This one is you
- [x] Create a new site on Netlify that deploys either `staging` or `master,` and it is using the Atlas env created above
- [x] Make environment-specific tests so we can filter out some tests depending on whether they are specific to the AIID or the empty state build. We should introduce a new function replacing `it` that checks for an environment variable and runs or skips the test as appropriate.

**Comment by smcgregor** [comment]
@kepae The Atlas environments are associated with my vanity domain because they pre-date the incidentdatabase.ai domain (my, how far we have come). I think we can create a new Atlas account, starting on the free tier and upgrading it shortly thereafter, and associate it with your UL email. Please let me know if you need assistance on this.

**Comment by kepae** [comment]
For posterity/mention, this overlaps with https://github.com/responsible-ai-collaborative/aiid/issues/443

**Comment by kepae** [comment]
Coming back around to this -- I started creating an empty dev env with my UL account but got sidetracked on other issues (and got stuck navigating the app services setup, formerly known as Realm). Should be able to get back to this soon.

**Comment by pdcp1** [comment]
New Atlas environment: [aiid-dev-empty](https://cloud.mongodb.com/v2/64f74f2c486ff808bae5cc32)
New Netlify site: [aiid-dev-empty](https://app.netlify.com/sites/aiid-dev-empty/overview)

**Comment by pdcp1** [comment]
@kepae We need to change the `aiid-dev-empty` app Deployment Region to `Global` on: https://realm.mongodb.com/groups/64f74f2c486ff808bae5cc32/apps/64fb334a4e6e86cec64a9e70/settings/general

<img width="1178" alt="image" src="https://github.com/responsible-ai-collaborative/aiid/assets/6564809/1f4c86dc-866f-4c56-a446-c8cfeb1b50ea">

**Comment by kepae** [comment]
@pdcp1 ack; in migration. Could take up to 30 min from now.

**Comment by kepae** [comment]
Courtesy @pdcp1 we have
* empty environment deployed in Realm and mirroring staging code with pushes:
https://github.com/responsible-ai-collaborative/aiid/deployments/empty
* Netlify site: https://aiid-dev-empty.netlify.app/
* new conditionals in tests, many of which enable testing in the empty environment: https://github.com/responsible-ai-collaborative/aiid/pull/2303

@cesarvarela Please lose this if you feel it enables https://github.com/responsible-ai-collaborative/aiid/issues/2112 ?
