### ISSUE TITLE
Improve report pages: Show page for each `/report/*`, regardless of incident associations

### ISSUE THREAD

**Issue by kepae** [responsible-ai-collaborative/aiid#2229]
Currently, simple raw report pages are only generated for reports that are **not** associated with incidents.
For example, report 2973 generates a page at https://incidentdatabase.ai/reports/2973/ as it does not support a minted incidents (but rather exists as an *issue report*), but report 1 does not generate such a page(https://incidentdatabase.ai/reports/1/) because it is linked to an incident (https://incidentdatabase.ai/cite/1/).

This behavior may simply be because the report pages weren't prioritized, or because this is a built-in structure to avoid linking a report when an incident page should instead be the focus. However, if a report later becomes part of an incident, the report URL is now a dead end. (should it be that way? do protest.)

Creating a page for every report is also useful in the case where future discovery/explore features may surface reports independently of incidents (e.g. #2047). A useful page would also contain pointers to incidents that are based on the report.

Goals:
- [ ] every report URL endpoint results in a report page
- [ ] report pages surface connection/membership to the incident(s) they support

**Comment by kepae** [comment]
@cesarvarela do you think you'll squash this in the path of #2047? If not, let me know. I'm thinking this is a quick fix but it's not a priority.

**Comment by kepae** [comment]
@cesarvarela I think we should revive this feature – editors can use this to query (and improve/refine) instances where reports are shared across incidents.

**Comment by clari182** [comment]
@kepae I'll take over this one. 
Now that we have https://incidentdatabase.ai/apps/incidents/?view=reports I also realized none of the links were working.
The other thing that I think should be updated after this change, is enabling clicking on the reports title (on the cite page), so it shows the full report on its own page. Right now what the title does is expanding/collapsing the text but IMO it's a bit confusing.
