### ISSUE TITLE
Update Daniel and Patrick affiliation on leadersboards.

### ISSUE THREAD

**Issue by Janetbananet** [responsible-ai-collaborative/aiid#2234]
Remove "(BNH.ai)" from Daniel Atherton and Patrick Hall. See Danny's full Slack note below:

Would it be possible to remove the "([BNH.ai](http://bnh.ai/))" parenthetical from my name and Patrick Hall's name as they appear throughout the AIID? ("Daniel Atherton ([BNH.AI](http://bnh.ai/))" and "Patrick Hall ([BNH.AI](http://bnh.ai/))" are how they appear on the leaderboards and throughout all reports we submitted.) As we are no longer affiliated with [BNH.AI](http://bnh.ai/), it seems appropriate to revise our names in the system and not upload reports with any names that create confusion in the system.

Change to only names, no affiliation.

**Comment by kepae** [comment]
I noted this as a TODO for myself, currently looking into a simple database migration.

**Comment by kepae** [comment]
Resolved in production with release https://github.com/responsible-ai-collaborative/aiid/pull/2227
