### ISSUE TITLE
Content overflows horizontally at medium widths

### ISSUE THREAD

**Issue by lmcnulty** [responsible-ai-collaborative/aiid#2252]
This may be related to recent changes to the layout.

![image](https://github.com/responsible-ai-collaborative/aiid/assets/25443411/9b880895-cd3c-4590-9ec2-695347ae5cb9)

**Comment by cesarvarela** [comment]
Whoops, it is, seems like Firefox isn't liking `overflow:clip`

I'll try to find an alternative because leaving `overflow:hidden` breaks `position:sticky`.
