### ISSUE TITLE
Some classification attributes are not not defined in any taxonomy

### ISSUE THREAD

**Issue by cesarvarela** [responsible-ai-collaborative/aiid#2260]
Taxonomies:

<img width="865" alt="image" src="https://github.com/responsible-ai-collaborative/aiid/assets/1172479/5a175a8f-555e-409a-aa95-1831db0d33a4">

Classifications:

<img width="981" alt="image" src="https://github.com/responsible-ai-collaborative/aiid/assets/1172479/0e26f6c8-ec12-44f0-9c29-8c7b92147246">

@lmcnulty, this looks like a bug, right? Should we add this to the taxonomy definition?

**Comment by cesarvarela** [comment]
Looks like `Reviewer` is present on `CSETv0` but missing on `CSETv1` 🤔 

<img width="687" alt="image" src="https://github.com/responsible-ai-collaborative/aiid/assets/1172479/77caeaa8-03c4-4889-ac3b-7b85c53f42e4">

**Comment by cesarvarela** [comment]
Another one:
<img width="707" alt="image" src="https://github.com/responsible-ai-collaborative/aiid/assets/1172479/c7293952-db35-4583-a39c-111071cb9777">

Maybe I'm not looking at this the way it is supposed to be but I'll keep a list in any case.

**Comment by cesarvarela** [comment]
<img width="653" alt="image" src="https://github.com/responsible-ai-collaborative/aiid/assets/1172479/37c3d6c7-d955-44f1-8ff9-68dea2b7eec0">

**Comment by cesarvarela** [comment]
<img width="672" alt="image" src="https://github.com/responsible-ai-collaborative/aiid/assets/1172479/7021ef3f-e83f-4363-a62d-1ccce6f05f93">

**Comment by cesarvarela** [comment]
<img width="670" alt="image" src="https://github.com/responsible-ai-collaborative/aiid/assets/1172479/2ae61b2c-fb58-4ac8-b677-16a0745d52c2">

**Comment by lmcnulty** [comment]
These are from old version of the taxonomy that I guess weren't migrated properly. It's the classifications which should be updated, not the taxonomies.

'Report, Test, or Study' → 'Report, Test, or Study of data'  
'Reviewer' → 'Peer Reviewer'  
'Harm Level Notes' →  'AI Tangible Harm Level Notes'  
'City' → 'Location City'  
'State or Province' →   'Location State/Province (two letters)'  
'Possibly Identifiable Harmed Entity' → 'Harmed Class of Entities'

**Comment by kepae** [comment]
@cesarvarela you mentioned you might fix this while interacting with the classifications collection. I'll assign it to you for now so it doesn't remain in limbo but say otherwise if you need someone else to address it.

**Comment by cesarvarela** [comment]
@lmcnulty, can you provide the mappings for these, too:

```
[Harm Level] not found in taxonomy [CSETv1]
[Region] not found in taxonomy [CSETv1]
[Property Damage Cost] not found in taxonomy [CSETv1]
[Financial Cost] not found in taxonomy [CSETv1]
[Harm Level] not found in taxonomy [CSETv1]
[Region] not found in taxonomy [CSETv1]
[Property Damage Cost] not found in taxonomy [CSETv1]
[Financial Cost] not found in taxonomy [CSETv1]
[Clear Link to AI] not found in taxonomy [CSETv1_Annotator-3]
[AI Linked to Special Interest Intangible Harm] not found in taxonomy [CSETv1_Annotator-3]
```

**Comment by lmcnulty** [comment]
I think it's supposed to be this:

- `Harm Level` → `AI Harm Level`
- `Region` → `Location Region`
- `Property Damage Cost` → Delete
- `Financial Cost` → Delete
- `Clear Link to AI` → `Clear link to technology`
- `AI Linked to Special Interest Intangible Harm` → `Clear link to Technology` (case difference is deliberate)

We may want to check with Heather or Mia.

**Comment by cesarvarela** [comment]
There is a test now making sure this does not happen again

https://github.com/responsible-ai-collaborative/aiid/blob/master/site/gatsby-site/cypress/e2e/integration/integrity.cy.js#L109
