### ISSUE TITLE
CsetTool merge broken

### ISSUE THREAD

**Issue by lmcnulty** [responsible-ai-collaborative/aiid#2268]
From Mia:

> Hi everyone! I am having some issues with the reconciliation tool: when I click on Merge Classification the button keeps buffering. A small red popup appears stating that classifications have been merged, but when I go back to the incident page the reconciled annotation (CSETv1) does not appear.

**Comment by kepae** [comment]
Fixed in production with #2264.

**Comment by kepae** [comment]
Maybe not fixed completely:

> the buffering is fixed, but the reconciled annotation (CSETv1) still doesn't appear. Just tried for incident #27.

**Comment by kepae** [comment]
Closing per offline discussion, tool is working correctly, modulo some needs to refresh the page and requesting live data after changes are made.
