### ISSUE TITLE
Mobile grid layout items exceed screen width and do not display fully, only on particular incident page

### ISSUE THREAD

**Issue by kepae** [responsible-ai-collaborative/aiid#2270]
Specifically incident 492: https://incidentdatabase.ai/cite/492

<img width="562" alt="image" src="https://github.com/responsible-ai-collaborative/aiid/assets/4238598/4f798a0d-c9a5-4e7a-ae5b-016d7592ce86">

<img width="562" alt="image" src="https://github.com/responsible-ai-collaborative/aiid/assets/4238598/43759266-4ab6-43a1-af81-ec5f291bcbd0">

This was surfaced by Google Search Console's mobile usability test, and as far as I can tell is *not* impacting other incident pages. I don't yet know why, so labeling this a high priority as it may be impacting others.

Reproduced in FF and Chrome.

**Comment by pdcp1** [comment]
Closing this since it was merged into Staging
