### ISSUE TITLE
Knowledge-base Strategy

### ISSUE THREAD

**Issue by lmcnulty** [responsible-ai-collaborative/aiid#2278]
Currently, we have documentation in a few Markdown files in the main repository. This is good for long-lived technical docs that benefit from git features like diffs and merges. However, it creates a relatively large amount of friction when adding documentation – even if you already have the repository set up, you need to create a new branch, edit the markdown files, add them to your staging area, write a commit message, push to your fork of the repository, open a pull request, cancel the unnecessary deploy preview, and wait for someone to merge the changes.

I sometimes write informal notes to myself that would probably be useful to other developers, particularly outside contributors and those onboarding to the project. We currently don't have a good shared place for these. There's also a lot of useful information that gets posted on Slack or in issue/PR threads but becomes hard to find later. I think we should have a more permanent home for information that's likely to be needed again.

One thing we've talked about was the desire for notes that could be kept private to contributors. I can see the use for this, since I think most people feel able to write more freely when it's not world-readable. On the other hand, posting publicly will help first-time contributors who haven't been given access yet. It will also allow our notes to show up in search engines, which will help us if e.g. one team member does a web search for an error which another team member encountered before and wrote down the solution to.

---

My view is that we should create public a GitHub wiki for this repository – it seems like the simplest option, and we already operate pretty openly in issue and PR threads. I think most notes can comfortably be made public, and should the need for private ones come up, we can find a different place for them.

Of course, I'd like to hear anyone else's ideas.

**Comment by kepae** [comment]
+1 to public wiki for snippets, notes, and things that would be useful to other developers. Thanks for writing up your thoughts.

I was thinking about this yesterday and I agree with your last sentiment -- if needed, we can always create a private repo just to contain a wiki.
We should make sure it's dev-centric at first, not editor or organizationally targeted. (those resources would benefit from other "community" style tools.)

I also believe a public wiki has the benefit of encouraging some readability and can, ideally, be inviting to contributors. :-)

**Comment by pdcp1** [comment]
I agree with you both. The public wiki will be a good starting point as a dev reference.
If there are private or sensitive information to share, like password, keys, secrets, etc. we can think in secondary place to share those.

**Comment by kepae** [comment]
I've created the wiki here: https://github.com/responsible-ai-collaborative/aiid/wiki

We can start with one section aimed at the use cases described. @lmcnulty , since you have some notes to share already, would you like to post them and do a rough label/section name as you see fit?

Low-cost to updating and moving them as they grow, compared to the README. :-)

**Comment by pdcp1** [comment]
@kepae I'm not able to create or edit the wiki. Maybe it's because I don't have access to that section of the repo.

<img width="1314" alt="image" src="https://github.com/responsible-ai-collaborative/aiid/assets/6564809/d3ddbaed-db59-4919-b56f-d81b804e737e">

**Comment by kepae** [comment]
Oops, thanks, I've changed the permissions. Would you please test again?

**Comment by pdcp1** [comment]
Now yes, I can edit. Thanks!
