### ISSUE TITLE
Checklisting – Review Public API Design

### ISSUE THREAD

**Issue by kepae** [responsible-ai-collaborative/aiid#2298]
Currently, the Risk Checklisting feature describes and prototypes an experimental REST API that would be used both by AIID's risk checklist feature and external users:
https://github.com/lmcnulty/aiid-risk-checklisting-design/blob/main/api.md

### General idea and endpoints
The use of the API follows a query pattern centered around searching for and retrieving "precedents" (incidents from AIID) via particular tags (currently populated from [the GMF taxonomy](https://incidentdatabase.ai/taxonomy/gmf/)). As I read it:
1. `/search_tags`: Query the API to discover available classification "search tags" useful for discovering potential risk precedents by tags that identify properties of the intelligent system in question (e.g. `"GMF:Known AI Technology:Transformer"`, `"GMF:Known AI Goal:Chatbot"`).
1. `/risk_tags`: Similarly, query the API to discover tags that represent the risks that materialized or considered in incident, such as known failure attributes (e.g. `"GMF:Known AI Technical Failure:Misinformation Generation Hazard"`).
1.  `/precedent`: Retrieve a particular precedent by ID (which correspond to a particular incident in AIID, its associated search and risk tags, and other data).
1. `/risks`: Retrieve the precedents in the database given particular tags (precedents, which correspond 1:1 to/represent individual classified incidents) corresponding to a given set of tags (either search or risk tags).

### Questions/Review
In moving from prototype to "alpha" functionality in the codebase, we should confirm that this functionality and implied workflow are sufficient for the AIID-hosted risk checklisting feature as well as a public general audience.
_(Note: This is distinct, but related to, the implementation of stateful user-centric implementations of the feature on AIID.)_

Some questions in mind:

* Is a RESTful API preferred to a GraphQL endpoint, and why?
    * My instinct is that we should prefer sticking to GraphQL not only because we currently expose a GraphQL endpoint but also for the machine-readable spec. (Or, if we want to use REST, consider adopting an OpenAPI-compliant interface to accomplish similar.
    * (I don't mean to belabor this point, but it has implications for if we host other APIs in the future, and how we will extend this one when desired.)

* Prototyping painpoints with AIID data and data structures?
    * The GMF taxonomy is in a few ways elegant, but there are still limitations in the expressiveness of the taxonomy schema in Mongo. How have these presented?

More questions and review comments welcome; this is to get the conversation started. We might consider a group brainstorm on this.

**Comment by lmcnulty** [comment]
> Is a RESTful API preferred to a GraphQL endpoint, and why?

> My instinct is that we should prefer sticking to GraphQL not only because we currently expose a GraphQL endpoint 

As far as I can tell, the current public GraphQL endpoint is just a thin wrapper around the GraphQL we get from Realm. Realm's GraphQL is tightly coupled to how we represent data in the database internally, and that changes frequently. For instance, when we changed from classifications having an `incident_id` to an `incidents` list, it would broken things if anyone had been using the public API for classifications. I think public APIs that we promote should have a limited surface area with a stability promise that we can transform any changing internal data representation to match. We could do that with GraphQL, but I think it would be confusing to have multiple GraphQL systems that work differently. Using GraphQL internally and JSON-flavored REST for public APIs is not unusual -- I believe Reddit does it. 

> but also for the machine-readable spec. (Or, if we want to use REST, consider adopting an OpenAPI-compliant interface to accomplish similar.

This is a valid point, and I like the idea of using OpenAPI if we continue with REST. 

> The GMF taxonomy is in a few ways elegant, but there are still limitations in the expressiveness of the taxonomy schema in Mongo. How have these presented?

The main incompatibility is that GMF wants to be a schema for annotating documents, and the taxonomy system is not built for that specifically. @npit [originally](https://github.com/responsible-ai-collaborative/aiid/issues/1334) envisioned a system that looked like this:

![image1](https://github.com/responsible-ai-collaborative/aiid/assets/25443411/9245d1fc-f106-48ba-81f6-55954704d07e)

We weren't prepared to build this and have had to emulate it with forms. So annotation is done by copying a snippet of text from the source article and filling out some associated fields. There's no association between the snippet and the report it comes from -- it's just a regular form field.

The other main issue is the distinction between known and potential goals, methods, and failures. Right now "Known Goals" and "Potential Goals" are not associated in any way, and for some uses we have to deduplicate them.

**Comment by kepae** [comment]
>  I think public APIs that we promote should have a limited surface area with a stability promise that we can transform any changing internal data representation to match. 

Agreed, certainly. Our current GraphQL endpoint is a naive mirror of our data. In that way, it's less an interface and more of a database query; it breaks the abstraction of the interface. However, it's useful for exploring the data as an open platform.

For Risk Checklisting, we can be strict about what is a supported and abstracted interface/API, and what are implementation details.

> We could do that with GraphQL, but I think it would be confusing to have multiple GraphQL systems that work differently.

I agree it could be confusing overhead to say "this is a GrapQL resolver we expose to mirror the data" and "this is a supported GraphQL API for a feature."
Notwithstanding the "naive" GraphQL service we have mirroring the DB and type defs of the data, would it be confusing to have multiple GraphQL endpoints/resolvers exposing separate resources/queries in the future? For instance, today we could produce a Checklisting resolver that just promises to return the transformed data.

This may matter more, if (when?) we have other features that hit the usability limit of Gatsby serverless functions and we run a separate API server. 

> This is a valid point, and I like the idea of using OpenAPI if we continue with REST.

@lmcnulty would you like to roughly spec out the changes to the API to make it work with OpenAPI spec? If it looks good and we can support it, then we can implement that.
(plus if we have a standing goal of the API, it helps move the initial commit in https://github.com/responsible-ai-collaborative/aiid/pull/1852)

**Comment by cesarvarela** [comment]
If we take a step back, our goal is to develop a product that is useful (obviously), that's easy to maintain, accessible for new developers to get into, etc. (we might want to have a separate discussion about our overall product vision)

In my view, integrating both GraphQL and plain old REST in the same app would add confusion for a very small (and subjective) win. Even when I get the feeling that graphql might be going out of fashion, or sometimes it adds unnecessary complexity, there is a ton of the app already written using it, and it is difficult to justify from a business standpoint to rewrite all that (and a bit nightmarish when I think of rewriting everything including tests).

This feels like bikesheddy to me.

**Comment by lmcnulty** [comment]
To be clear, the only part of the app I would propose using REST for is public APIs with stability promises. I think we should continue using GraphQL internally and that we shouldn't rewrite anything.

As far as I can tell, it seems like everyone except me is leaning towards using GraphQL instead of REST for the public API, so I'm fine going forward with that. However, I'm not sure what that will look like for the Checklisting project. My questions are:

- Do we want separate, stable GraphQL endpoint for the checklisting features? We ultimately want to expose this to design partners like Fairly.ai, so it's important that we be able to keep it stable against changes to our database structure. If so...
  - ...should we use that public endpoint for our own checklisting UI? I've done this with the REST prototype, the logic being that we're less likely to break it if it breaks our own stuff too. However, I think it would extraordinarily confusing for our GraphQL queries in the checklisting feature to be different from GraphQL queries everywhere else in the app. So if we do add another GraphQL endpoint, I'd rather not use it at all internally and just depend on tests for stability.
  - ...how do we go about making another GraphQL endpoint? With REST it's trivial, and when we just forward GraphQL requests to Realm, it's trivial, but if there's any structural mapping or logic beyond that, then we have to parse the request and respond appropriately. That means we need to decide what libraries to use, etc.
 
I think for now I'm going to rewrite the checklisting PR to use our regular, private GraphQL endpoint, and we can do ideation for a public GraphQL api in [the design repo](https://github.com/lmcnulty/aiid-risk-checklisting-design/).

**Comment by cesarvarela** [comment]
> Do we want separate, stable GraphQL endpoint for the checklisting features? We..

- I think we should only have one endpoint (only one URL that we have to care about).
- Once we commit to a public API, we'll have to introduce versioning (`incidentdatabase.ai/api/graphql/v1`, and so), which will force us to host our own graphQL server, but thanks to graphql stitching, we can do it gradually without having to do it all at once, forwarding most of the requests to the current Atlas endpoint (if we are careful about schema upgrades.).
- Example: https://shopify.dev/docs/api/usage/versioning#the-api-version-release-schedule

The current endpoint https://incidentdatabase.ai/api/graphql  already makes use of stitching:  https://github.com/responsible-ai-collaborative/aiid/blob/master/site/gatsby-site/src/api/graphql.js#L35

> how do we go about making another GraphQL endpoint? With REST it's trivial, and when we just forward GraphQL requests to Realm, it's trivial, but if there's any structural mapping or logic beyond that, then we have to parse the request and respond appropriately. That means we need to decide what libraries to use, etc.

If these new queries are more or less aligned with how Realm does it I think it should be okay. Do you have an example of a query that returns greatly from what we already have?

**Comment by lmcnulty** [comment]
> If these new queries are more or less aligned with how Realm does it I think it should be okay. Do you have an example of a query that differs greatly from what we already have?

The main concept of the checklisting api is that you provide search tags and get a list of precedents grouped by risk tags (underlyingly, classifications).

```bash
curl -G "https://incidentdatabase.ai/api/riskManagement/v1/risks" --data-urlencode \
'tags=GMF:Known AI Technology:Language Modeling___GMF:Known AI Goal:Question Answering'
```

```json
{
  "risks": [
    {
      "tag": "GMF:Failure:Gaming Vulnerability",
      "precedents": [
        {
          "incident_id": 146,
          "url": "https://incidentdatabase.ai/cite/146",
          "title": "Research Prototype AI, Delphi, Reportedly Gave Racially Biased Answers on Ethics",
          "description": "A publicly accessible research model[...]moral judgments.",
          "search_tags": [
            "GMF:Known AI Technology:Language Modeling",
            "GMF:Known AI Goal:Question Answering",
            "GMF:Known AI Technology:Distributional Learning"
          ],
          "risk_tags": [
            "GMF:Known AI Technical Failure:Distributional Bias",
            "GMF:Failure:Gaming Vulnerability"
          ]
        },
        {
          "incident_id": 72,
          "url": "https://incidentdatabase.ai/cite/72",
          "title": "Facebook translates 'good morning' into 'attack them'",
          "description": "Facebook's automatic language[...]in Beitar Illit, Israel.",
          "search_Tags": [
            "GMF:Known AI Technology:Language Modeling"
          ],
          "risk_tags": [
            "GMF:Failure:Gaming Vulnerability"
          ]
        }
      ]
    }
  ]
}
```

Translated to GraphQL, we'd ideally have something like this

```grahpql
query Risks(tags: ...) {
  risks {
    tag
    precedents {
      title
      incident_id
      url
      description
      search_tags
      risk_tags
    }
  }
}
```

But getting there from the underlying data format, which has a separate classifications collection with serialized values, requires [a fair amount of logic](https://github.com/responsible-ai-collaborative/aiid/pull/1852/files#diff-a45d04a3d7b5b77e3d9a9d2b28da7f7c644ca445dc05cb8c2c1683b083674ff4). I'm not sure where that would go if we were using GraphQL. We could just ask the API users to do the work themselves with the underlying data format, but I think we'll get more traction if the API for this feature seems clean and purpose-built.

**Comment by cesarvarela** [comment]
That's what Atlas custom resolvers are for: https://www.mongodb.com/docs/atlas/app-services/graphql/custom-resolvers/#:~:text=Custom%20resolvers%20allow%20you%20to,document%20of%20the%20extended%20type.

Most of the code you have there can be copied and pasted, plus some config and tweaks here and there, and it will work.

In your case, you should extend the Query type so the new resolver sits at the root of the graph, but this is an example we are currently using that extends the `Report` type.

Custom resolver definition:
https://github.com/responsible-ai-collaborative/aiid/blob/master/site/realm/graphql/custom_resolvers/report_translations.json

The function associated with the custom resolver:
https://github.com/responsible-ai-collaborative/aiid/blob/master/site/realm/functions/reportTranslations.js

**Comment by cesarvarela** [comment]
Custom resolvers are a PITA to work with, but it is doable:
- to include external node dependencies, you have to upload a zip file, which I think we should avoid, but it seems you are using none
- the only way to debug them is to use the function editor UI in Atlas 
- sometimes it is faster to develop them TDD style: https://github.com/responsible-ai-collaborative/aiid/blob/master/site/gatsby-site/cypress/e2e/unit/functions/promoteSubmissionToReport.cy.js

**Comment by kepae** [comment]
Overall, I think it is reasonable and expected that introducing a first public, feature-driven (rather than transparency-of-data-driven) API is bringing up this discussion. It has important impacts for what developers will maintain, and having even two developers agree on its implementation is important in a small team.

That said, yes, I don't mean to invite bikeshedding or yak shaving. In the future, a 30-minute meeting or quick huddles on slack can be better.
______

> I think we'll get more traction if the API for this feature seems clean and purpose-built.

Definitely. We shouldn't expect callers to be doing extra work. To that end, I think the query you enumerated above is ideal for the request/response... and we should do the extra work server-side.

I'm late, but as César pointed out, this business logic can be executed on the Atlas server side, defined in a separate function that takes as input the GraphQL request (corresponding to the Risk API endpoint) and does the messy logic internally.  (We can also push to realm independently of the static site if we need, which I think is a plus.)

This code and logic ultimately shouldn't look too different than a well-tested REST API. But I also agree, testing Atlas functions is less direct than testing a local function. Mocking services, like the mongo connection, is possible:
https://www.mongodb.com/docs/atlas/app-services/functions/test/#mock-services

In our code, an example of overriding the context:
https://github.com/responsible-ai-collaborative/aiid/blob/72a4b5d21758db18e04f0f095f3f1563c1fc8d8a/site/gatsby-site/cypress/e2e/unit/functions/onNewIncident.cy.js#L64
______

> ...should we use that public endpoint for our own checklisting UI? I've done this with the REST prototype, the logic being that we're less likely to break it if it breaks our own stuff too

We should definitely aim to "dogfood" our own API like this and keep this in mind when exposing an endpoint in the v1 launch. While prototyping, it's less important. @lmcnulty would you like to revisit this point after discussing more of how a graphql implementation would work in practice with Atlas fucntions/custom resolvers?
For my own part, I'd like to confirm it's possible without too much effort, implementation-wise.

**Comment by kepae** [comment]
The GraphQL custom resolver was introduced in https://github.com/responsible-ai-collaborative/aiid/commit/18ec6999912fd0bc2982fe72202ef095193f7d82. We can close this issue for the purposes of design and planning the initial API.
