### ISSUE TITLE
Checklisting – Authentication

### ISSUE THREAD

**Issue by lmcnulty** [responsible-ai-collaborative/aiid#2300]
Currently anyone can edit any checklist. This needs to change before the feature goes anywhere.

**Comment by kepae** [comment]
@lmcnulty I believe this is okay to close? especially in favor of more fine-grained questions on auth access to different resources. I started thinking about this in https://github.com/responsible-ai-collaborative/aiid/issues/2386.

**Comment by lmcnulty** [comment]
Yes, that's fine.
