### ISSUE TITLE
User Accounts – Implement flow for re-sending verification emails

### ISSUE THREAD

**Issue by kepae** [responsible-ai-collaborative/aiid#2335]
Currently, when a user tried to sign-in without having verified their account, they only receive an error toast stating "Confirmation required".

At this point, there should be a way for a user to request to re-send the verification email, in the event that the original email never reached them or can't find it. (In practice, this is likely a new verification email if the token has expired.)

**Comment by pdcp1** [comment]
Closing this since it was already merged into Staging
