### ISSUE TITLE
Edit Incident – Blank page error

### ISSUE THREAD

**Issue by kepae** [responsible-ai-collaborative/aiid#2353]
Specifically on Incident 586, per Danny:

> When I click "Edit Incident" on that page, something similar to the "Your Account" glitch occurs; the page attempts to load and then suddenly goes blank.

I can reproduce this in production currently:
https://incidentdatabase.ai/incidents/edit/?incident_id=568
Has failed requests with error:
`TypeError: p.users.find(...) is undefined`

**Comment by datherton09** [comment]
Seems like the blank page appears for me on this one still when I click the "Edit incident" button. Not a huge priority, but thought I'd flag it just in case.
