### ISSUE TITLE
Incident List sort/order function?

### ISSUE THREAD

**Issue by datherton09** [responsible-ai-collaborative/aiid#2425]
Another very low-priority thought that could be helpful: A way to quickly sort ascending/descending on the Incident List (https://incidentdatabase.ai/summaries/incidents/) page? (I do most of my editing by launching off from this page.)

**Comment by pdcp1** [comment]
@datherton09 Do you have a specific Incident sort field? Or is it OK to sort ascending/descending by date?

**Comment by datherton09** [comment]
@pdcp1 Ascending/descending by date of incident and/or incident number would be perfect! Just getting the latest ones up at the top could save a fair bit of time in the long run in terms of adding new reports. Thank you :)

**Comment by datherton09** [comment]
@pdcp1 @kepae If the sorting-by-date is too complicated (and I could imagine it might be at this juncture, especially if we ever implement multiple incident dates per incident number), then sorting ascending/descending simply by incident number would be very helpful in and of itself!

**Comment by pdcp1** [comment]
@datherton09 Could you test this preview link https://deploy-preview-2495--staging-aiid.netlify.app/summaries/incidents/ and let me know if that is what you expected? Thanks!

**Comment by datherton09** [comment]
@pdcp1 This is PERFECT! It'll greatly increase editing efficiency! Thank you so much for all this -- much appreciated! :)

**Comment by datherton09** [comment]
@pdcp1 Not sure if this matters with the way the system is set up, but I noticed in your deploy preview link that Incident 616 is different from the current Incident 616. Just wanted to flag that in case of the potential for any accidental override. Thanks again!!

**Comment by pdcp1** [comment]
> @pdcp1 Not sure if this matters with the way the system is set up, but I noticed in your deploy preview link that Incident 616 is different from the current Incident 616. Just wanted to flag that in case of the potential for any accidental override. Thanks again!!

That difference is correct. The incident data used on this preview link is from the Staging environment, not Production. That's why you can see some info discrepancies.

**Comment by pdcp1** [comment]
Closing this since it was already released to Production https://incidentdatabase.ai/summaries/incidents/

**Comment by pdcp1** [comment]
@datherton09 This is live! https://incidentdatabase.ai/summaries/incidents

**Comment by datherton09** [comment]
@pdcp1 It's glorious! Thank you so much! :)
