### ISSUE TITLE
API endpoint for report membership checking – "Is this report indexed in the AIID?"

### ISSUE THREAD

**Issue by kepae** [responsible-ai-collaborative/aiid#2492]
External services compiling and referencing AI incidents in news and other media could benefit from querying if a particular URL is ingested in the incidents database and retrieving the incidents or other molecules with which it is associated.

**Comment by kepae** [comment]
@cesarvarela would this be a good candidate for experimenting with a first maintained GraphQL server? No existing functionality depends on it, we don't have promises to support this endpoint, doesn't handle user data so can just just depend on "vanilla"/basic Mongo Atlas functionality, and we can use it as a foothold to port other GraphQL functionality into in the future.

**Comment by kepae** [comment]
@cesarvarela We are increasing the priority on this per discussion. Long-term, this functionality needs to exist in the GraphQL API server we are planning to prototype and support. Short-term, we should add this functionality to our API, ideally in a way that's separate from the reflected Atlas-generated schema. Let's discuss this today on the path to prototyping the API.

**Comment by cesarvarela** [comment]
From what we talked I think the call signature should be something like this:

```
query areTheseReportsIndexed(input: AreTheseReportsIndexedQuery) {
  results: [ReportsIndexResult]
}

type AreTheseReportsIndexedQuery {
  urls: [String]
}

type AreTheseReportsIndexResult {
  url: String
  incidents: [Incident]
  reports: [Report]
}

```

Example call:

```
query areTheseReportsIndexed(input: { urls: ["https://1.com/path/", "https://2.com/path/?querystring=1"] }) {
  results {
    incidents {
      incident_id
      title
    }
   reports {
      report_number
      title
    }
  }
}
```

Response: 

```
      areTheseReportsIndexed:
      {
        results:
          [
            // indexed 
            {
              url: "https://1.com/path/",
              incidents: [
                {
                  incident_id: 1,
                  title: "Incident 1 title"
                }
              ],
              reports: []
            },
            // not indexed 
            {
              url: "https://2.com/path/",
              incidents: [],
              reports: []
            },
          ]
      }
    }
```

(open to change the name, I'm no a fan)

**Comment by kepae** [comment]
Nice! The input and return signatures look good to me.

Some thoughts:
* **query name:** `lookupCanonicalIncidents`? `lookupIncidentsByReport`? Given that it also reasonably returns indexed reports (in addition to incidents), perhaps we should make it more generic: `lookupByUrl`? `UrlLookupQuery`? (and the client can know from the GraphQL endpoint that it returns incidents, reports, etc.. But trying to think what is conventional). Still thinking here, too.
* **canonical incident URL:** in the response, we should also return the AIID url(s) for the incident(s), and not leave that to the client. Should we materialize a `url` field on incidents in the resolver, even though we don't store them with the URL? Not sure what the typical approach is here. (for reports, the `url` field is already defined and stored)
* **type name:** I don't think we should define a `type` ending with the suffix "query", based on the other graphQL schema I've seen; otherwise it could look like the query request itself. Perhaps `<queryName>Input`? `<queryName>Request` + `<queryName>Response` [a la gRPC](https://grpc.io/docs/what-is-grpc/core-concepts/#service-definition)?

What do you think?

**Comment by cesarvarela** [comment]
> query name:

Went with `lookupByUrl`

> canonical incident URL

I added a `permalink` field, but maybe


> type name

By default, Atlas adds a `QueryInput` suffix to query type names:
<img width="419" alt="image" src="https://github.com/responsible-ai-collaborative/aiid/assets/1172479/7d703b17-2d4d-4e1e-9110-84e8071ea0d4">

And for results, the `Payload` suffix:

<img width="555" alt="image" src="https://github.com/responsible-ai-collaborative/aiid/assets/1172479/e80a2d0b-cb69-4ca9-b80c-47855cfcb6ce">
