### ISSUE TITLE
Design and create interface for editing entities

### ISSUE THREAD

**Issue by kepae** [responsible-ai-collaborative/aiid#2536]
This issue concerns designing and implementing a user interface that will become the home of curating entities.

Entities will become more prominent data in AIID:
* as other interfaces link to them (such as interfaces desired in #2047)
* when we wish to enrich them with other data (#1437)
* or if we need to modify them with respect to other entities (#2465).

Thus, we will need a home entrypoint and interface for interacting with and editing entity objects after they have been created. We know not all of the operations we will need to support, but we can start with the basics described in #1437.

Questions to consider:
* What is the basic design of the interface? Will it be extensible?
* What API/GraphQL operations will be needed to interact with the data? Where are the static/dynamic boundaries on the data?

**Comment by pdcp1** [comment]
@kepae An initial mockup for the Entity edit page is in our Figma workspace https://www.figma.com/file/KI28jWrOO3soKp9dTg7b0d/Entities-workflow?type=design&node-id=0%3A1&mode=design&t=a1M9nWWeHzoisF2d-1

We should take this as a kick-off design. I added some fields that I consider appropriate but we can discuss which ones are more important to implement in an initial phase.
Feel free to edit it. I'm open to any suggestions and discussions.

<img width="737" alt="image" src="https://github.com/responsible-ai-collaborative/aiid/assets/6564809/9e3584e8-a6af-455f-bb69-6d61f20bf3c7">

**Comment by kepae** [comment]
@pdcp1 I think we can close this issue now that we have the "base" interface that we can extend. Please feel free to re-open!
