### ISSUE TITLE
Discover – Classifications filter facets counting field values, not search results

### ISSUE THREAD

**Issue by kepae** [responsible-ai-collaborative/aiid#2577]
The field facet currently counts the number of unique _values_ in the given property, rather than the number of search results (incidents and/or reports) attributed with each value.

For example: CSETv1 > Physical Objects should be 28 rather than 2 in the below example (if I count correctly).

<img width="1185" alt="image" src="https://github.com/responsible-ai-collaborative/aiid/assets/4238598/3151a2db-f240-4095-a4cd-a2ca6e700e69">

See https://github.com/responsible-ai-collaborative/aiid/issues/2330#issuecomment-1749498903 for an example mock with proper facet counts.

@cesarvarela -- could be a good opportunity to share Algolia responsibilities with the team so it's not just you!

**Comment by cesarvarela** [comment]
I couldn't find an easy way to get that count from Algolia (without adding another field to each Aglolia Record) but using the value with the largest count might get us close to that number:

<img width="514" alt="image" src="https://github.com/responsible-ai-collaborative/aiid/assets/1172479/849335cc-53d5-4b0a-ad6a-f70a6fba65b4">

**Comment by cesarvarela** [comment]
(Algolia returns counts for leaves; to get the exact count, we would have to add another property to records that set attributes as leaves)
