### ISSUE TITLE
Add support for larger runners in workflows

### ISSUE THREAD

**Issue by cesarvarela** [responsible-ai-collaborative/aiid#2600]
Workflows should pick from the available runners, including the larger ones if available, and if not, default to the standard ones.

**Comment by kepae** [comment]
Tackled partially in:
* https://github.com/responsible-ai-collaborative/aiid/pull/2613

**Comment by kepae** [comment]
Added the repository-level vars for the runner configuration:
<img width="736" alt="image" src="https://github.com/responsible-ai-collaborative/aiid/assets/4238598/26260817-7e49-48ee-be34-34343d28390c">

We can close this once we see some runs. :-)

**Comment by cesarvarela** [comment]
<img width="560" alt="image" src="https://github.com/responsible-ai-collaborative/aiid/assets/1172479/97ac284e-7d65-48e7-acb4-c4baedac93ce">
