### ISSUE TITLE
Edit Submission Form – `incident_editor` seems unable to accept or reject incident reports

### ISSUE THREAD

**Issue by kepae** [responsible-ai-collaborative/aiid#2606]
Yesterday, I changed @datherton09's AIID account from `admin` to `incident_editor` and `taxonomy_editor` as part of:
* https://github.com/responsible-ai-collaborative/aiid/issues/2383#issue-1968598857

 However, he then reported being unable to accept or reject incident report submissions, with the corresponding UI being disabled/greyed out:

![image](https://github.com/responsible-ai-collaborative/aiid/assets/4238598/09ee5590-c504-49fc-962a-6340dce68437)

I reverted his account back to `admin` permissions and this resolved the issue. This leads me to believe there is a codepath in the editing flow still requiring `admin` permission.

**Comment by pdcp1** [comment]
Closing this since it was already merged into Staging
