### ISSUE TITLE
Submission review page appears to be pending load

### ISSUE THREAD

**Issue by smcgregor** [responsible-ai-collaborative/aiid#2642]
The skeleton on quick submit never goes away. Maybe there is no data to render for the first time in a while? There are also some failed network requests.

<img width="1668" alt="Screenshot 2024-02-15 at 4 29 17 PM" src="https://github.com/responsible-ai-collaborative/aiid/assets/64780/b556eab2-7e0b-45fe-8d03-901ecec0c40d">

**Comment by kepae** [comment]
I can reproduce this. @clari182 would you please take a look, and consider tackling this after wrapping up the pending user role fixes?
