### ISSUE TITLE
Issue Reports – Dedicated page for viewing table or list of issue reports

### ISSUE THREAD

**Issue by kepae** [responsible-ai-collaborative/aiid#2681]
Editors could use a more lightweight way of digging through the history of issue reports than the [discover interface's filtering method](https://incidentdatabase.ai/apps/discover/?display=list&is_incident_report=false), like the ["all incidents in list form"](https://incidentdatabase.ai/summaries/incidents/) summary a.k.a. "power user mode." The main impetus is so that when/if the database begins to accept more varied types of reports, there is a way to easily review the existing reports and connect them to incidents.

Specifically, we should list **all** issue reports in some manner along with dates of submission and publication, especially while the collection size is manageable for a single page. As of now, there are 223 such reports.
EDIT: Additionally, all reports should be visible on _one page_.

For now, the only technical handle on what constitutes an issue report is whether the field on the report document `is_incident_report` is `false`. This might change if we open up to more types of reports:
- #2292

Options:
- Create a static page (perhaps `/summaries/issues/`) that lists reports by their title, also displaying their date submitted and date published.
- Alternatively, we could create a table view (like we do for incidents as well: https://incidentdatabase.ai/apps/incidents/) that displays all this info. This might be worth it for easier sorting implementation.

@datherton09 @Janet-ResponsibleAI what do you think? Which interface would be more helpful?

**Comment by datherton09** [comment]
Thanks, @kepae ! I could go with either option -- whatever is most convenient on the engineering end!

**Comment by Janet-ResponsibleAI** [comment]
If the static page is much easier/faster to create I'd say go for that for now. The sorting ability of the table view may ultimately be more useful, but without the concept or process in place for how editors will be systematically reviewing issues it may not yet be worth the extra effort (if it is more effort).

**Comment by kepae** [comment]
Thanks both! @clari182 if you have cycles for this next week, let me know and we can prioritize this among other things perhaps.
