### ISSUE TITLE
Separate pageCreator for landing page

### ISSUE THREAD

**Issue by lmcnulty** [responsible-ai-collaborative/aiid#2682]
If I'm not mistaken, the landing page is currently generated from the [createWordCountsPage.js](https://github.com/responsible-ai-collaborative/aiid/blob/91ab98aba974da67b2aedf921e430d4f9d2caf73/site/gatsby-site/page-creators/createWordCountsPage.js#L15) file, because the landing page used to have a word counts preview widget. It doesn't anymore, so this is very confusing.

**Comment by clari182** [comment]
Closing because solved here https://github.com/responsible-ai-collaborative/aiid/pull/2710
