### ISSUE TITLE
Last "Next Incident" button redirects to a null incident

### ISSUE THREAD

**Issue by pdcp1** [responsible-ai-collaborative/aiid#2695]
As part of the testing of https://github.com/responsible-ai-collaborative/aiid/pull/2689 I found an edge-case test.

## Steps to reproduce

1. Go to the last incident (at this moment the last incident is https://incidentdatabase.ai/cite/652 )
2. Scroll down and check the `Next Incident` button. It should be disabled
3. Click that `Next Incident` button anyways
4. It redirects to https://incidentdatabase.ai/cite/null/

The same happens with the first incident https://incidentdatabase.ai/cite/1/ and the `Previous Incident` button.

## Notes
In addition to the disabled visual state, the button shouldn't be clickable (completely disabled)

**Comment by kepae** [comment]
I believe this is now fixed.
