### ISSUE TITLE
Non-machine translated content is appearing labeled as machine translated

### ISSUE THREAD

**Issue by smcgregor** [responsible-ai-collaborative/aiid#2759]
See: https://incidentdatabase.ai/ja/apps/discover/?is_incident_report=true

The machine-translated badge is appearing on the non-translated content when localized to Japan. I plugged it into Google translate to confirm that is what the text says.

<img width="493" alt="Screenshot 2024-04-27 at 5 55 32 PM" src="https://github.com/responsible-ai-collaborative/aiid/assets/64780/c5ed615c-3af0-469f-bbde-f52b2f1120c9">

**Comment by kepae** [comment]
@pdcp1 Could you please take a look at this when you get a chance? This might be related to the machine translations which are now running per #2701 changes.

**Comment by pdcp1** [comment]
@kepae let's check if this is still happening after the fix on the translation process referred to here:

https://github.com/responsible-ai-collaborative/aiid/issues/2701#issuecomment-2083780574

**Comment by kepae** [comment]
@pdcp1 how's this looking with the latest translation pipeline fix?

**Comment by pdcp1** [comment]
> @pdcp1 how's this looking with the latest translation pipeline fix?

The Discover page badges fix is pending. The last changes fixed the "machine-translated badge" in the Incident report cards. I will assign this to me so I can work on a fix. I pretty sure that the fix will be similar.

**Comment by pdcp1** [comment]
@kepae In order to cover and fix the Discover case, I opened this PR #3264
We need to add a new Algolia boolean field, `is_translated`, to identify all items that have translations.

**Comment by pdcp1** [comment]
I will close this issue since it was fixed and merged into Staging ✅
This is an example URL from Staging https://staging-aiid.netlify.app/ja/apps/discover
