### ISSUE TITLE
Sidebar anchors are broken

### ISSUE THREAD

**Issue by smcgregor** [responsible-ai-collaborative/aiid#2769]
Click on sidebar on this page and it will change the anchor text, for example:

https://incidentdatabase.ai/about/#why%22aiincidents%22?

but it will not scroll to the anchor and if you do a page reload it will not load at the anchor point.

Tested on Chrome and Edge.

**Comment by lmcnulty** [comment]
It looks like the heading ID attributes aren't there.

![image](https://github.com/responsible-ai-collaborative/aiid/assets/25443411/62f7a803-afeb-4db4-ab1a-3b2c83490349)
