### ISSUE TITLE
Allow user to track submissions

### ISSUE THREAD

**Issue by chinzeshen** [responsible-ai-collaborative/aiid#2783]
Users cannot track incident submission. Currently users can only sign in as subscribers by default.

**Comment by kepae** [comment]
How would you like to track incident submission as a user?

We currently have two ways:
* see the submission queue in general: https://incidentdatabase.ai/apps/submitted/
* receive email updates for submitted incidents if you are signed in with your account. This is temporarily paused but we are re-enabling it (https://github.com/responsible-ai-collaborative/aiid/issues/2733)

**Comment by chinzeshen** [comment]
I think the first way isn't ideal, in my case I submitted an incident and
after a few days it just disappeared from the submission queue, and I
couldn't find it in the list of incidents either. I don't know why it was
not accepted, and I could not access it anymore and fix whatever that
needed to be fixed if there were something to be fixed.

The second way seems good once re-enabled.

**Comment by kepae** [comment]
Gotcha! Thanks for submitting to AIID and for the feedback -- it's good to know that the email notifications are useful! They're enabled in production again.

Please let us know if the email notifications work as expected or fit your need when you submit another report. :-)
