### ISSUE TITLE
Add an icon to `Risk Checklists` menu item

### ISSUE THREAD

**Issue by pdcp1** [responsible-ai-collaborative/aiid#2786]
I believe we should select an icon for the 'Risk Checklists' menu item that matches the others.
It's especially important when the sidebar menu is collapsed (see the second screenshot below)

<img width="264" alt="Screenshot 2024-05-15 at 6 25 24 PM" src="https://github.com/responsible-ai-collaborative/aiid/assets/6564809/d92625b8-6735-416b-a0ee-f55eb8652fe1">

<img width="333" alt="image" src="https://github.com/responsible-ai-collaborative/aiid/assets/6564809/5e415398-10a1-43f3-8a8a-ec282ab97637">

**Comment by kepae** [comment]
Indeed. @lmcnulty and I were just discussing this. :-)

**Comment by pdcp1** [comment]
Great! let's close this issue once https://github.com/responsible-ai-collaborative/aiid/pull/2752 is merged.
