### ISSUE TITLE
Improve Similiar and dissimilar incidents edition UX

### ISSUE THREAD

**Issue by pdcp1** [responsible-ai-collaborative/aiid#2799]
On Incident edition page (e.g.: https://staging-aiid.netlify.app/incidents/edit/?incident_id=659)

Both sections (`Manually-selected similar and dissimilar incidents` and `Reports`) disappear and reload on each change without a "loading" or a spinner.
In addition to that, every time I click on `Yes` or `No`, all reports change under the same incident at the same time. That is the expected behaviour but it's confusing. 

This is a screen recording to visualize what I mean.

https://github.com/responsible-ai-collaborative/aiid/assets/6564809/05d603bf-7151-4e87-9bb0-47ec29e81c6a

_Originally posted by @pdcp1 in https://github.com/responsible-ai-collaborative/aiid/issues/2797#issuecomment-2130327525_

**Comment by clari182** [comment]
Hey @datherton09, can you take a look at this and tell me what you think?

I used this UI recently and also found it very confusing. Since you're the one that uses it the most, your input would be very helpful!

- Do you think all the reports should appear for the incident when you're searching? Maybe we could only display one card per incident with its title.

**Comment by datherton09** [comment]
@clari182 I agree -- I've never once felt the need to decide if any individual report within an incident ID is related or not. I've always kept it at the incident ID level.

**Comment by kepae** [comment]
Per @datherton09:
> Seeming to have trouble in the "similar incident IDs" field having the suggestions expand beyond four suggestions, which results in me not being able to select the one I need -- encountered this problem a couple of times. Not urgent, but flagging it.

![image](https://github.com/user-attachments/assets/6431f244-a06e-40e9-9450-bdd00d5b31e3)

@clari182 would you please look at this and find the best way to expand this to show all retrieved incident suggestions?

**Comment by pdcp1** [comment]
Closing this since it was released to Production
