### ISSUE TITLE
Update "Subscribe" button to suggest account creation / logging in

### ISSUE THREAD

**Issue by kepae** [responsible-ai-collaborative/aiid#2818]
In-person feedback I received, confirming some previous discussions we had internally:
> How can I create an account? I only see a subscribe button.

This is particularly important to get across before publishing a blog post on risk checklisting, which for now requires users to have accounts.

@lmcnulty , would you like to cook up some suggestions for how to present the button? How it should appear for both signed in and anonymous/logged out users.

**Comment by lmcnulty** [comment]
For reference, here's the [old thread](https://github.com/responsible-ai-collaborative/aiid/issues/1345#issuecomment-1302585062) where we discussed the wording of the button. There are now more things linked to user accounts, so I don't think the reasoning for using "subscribe" applies anymore.

Currently the subscribe button leads to the sign up page, and you need to click another link to get to the login page. It feels like the obvious thing to do would be to change "Subscribe" to "Sign up" and leave the logged-in message as "Your Account." 

I have a git branch changing the messaging on the checklists page to have a link to the login page when not already logged in, but it seems like I didn't actually open a PR for it. I'll do that shorty.
