### ISSUE TITLE
Make conditionalIntercept alias parameter obligatory

### ISSUE THREAD

**Issue by cesarvarela** [responsible-ai-collaborative/aiid#2868]
If an API call is mocked, we should ensure the mock is hit.

There is a chance that a request might slip through and unwantedly hit the database 💥 

https://github.com/responsible-ai-collaborative/aiid/blob/master/site/gatsby-site/playwright/utils.ts#L31

**Comment by kepae** [comment]
Can we completely separate tests that can run statically and those that hit real resources (which we should carefully and explicitly isolate)?

**Comment by cesarvarela** [comment]
I would suggest a `smoke` folder next to the `e2e` folder for that

**Comment by cesarvarela** [comment]
https://github.com/responsible-ai-collaborative/aiid/issues/2886
