### ISSUE TITLE
Checklist Feature When Not Logged In

### ISSUE THREAD

**Issue by smcgregor** [responsible-ai-collaborative/aiid#2870]
When I am not logged in, I am looking around for where I can create a checklist. The messaging makes it seem like I should click somewhere to create a checklist, when I really should be clicking to login.

<img width="1063" alt="Screenshot 2024-06-15 at 5 57 02 PM" src="https://github.com/responsible-ai-collaborative/aiid/assets/64780/05fe18b5-ac2c-4c9c-aeb7-d338ca778d60">

**Comment by kepae** [comment]
This is being addressed in #2820.

**Comment by smcgregor** [comment]
sorry for the dupe, closing.
