### ISSUE TITLE
Tests accessing production

### ISSUE THREAD

**Issue by kepae** [responsible-ai-collaborative/aiid#2872]
Per @datherton09, test submissions are showing up in the submission queue:
![image](https://github.com/responsible-ai-collaborative/aiid/assets/4238598/0cae559a-4c61-4790-8e44-638113006029)

Corresponds to at least this test:
https://github.com/responsible-ai-collaborative/aiid/blob/e2b9b5c634b3ad0e514e336603dd490abee6ff26/site/gatsby-site/playwright/e2e/submit.spec.ts#L1717

Until we've found the environment/config problem, I've disabled all CI/CD so that no scheduled runs or triggered runs from PRs should execute tests. The concern is that there may be other tests hitting production DB.

**Comment by kepae** [comment]
(This is a Monday -- not Sunday -- critical.)

**Comment by cesarvarela** [comment]
@kepae I've deleted `E2E_ADMIN_USERNAME` and `E2E_ADMIN_PASSWORD` from the `production` environment. That's what was giving them access to production.

So, it is safe to enable CI again. Some other tests will fail because of this, but I'll fix those later.

**Comment by kepae** [comment]
Thanks @cesarvarela . Re-enabled CI/CD and pushing production to capture updates.

**Comment by kepae** [comment]
@cesarvarela This is still happening, despite CI/CD in production not being provided with the above env variables.
