### ISSUE TITLE
Incident 704 not found (Live incident data not loading)

### ISSUE THREAD

**Issue by collinstarkweather** [responsible-ai-collaborative/aiid#2880]
Searching for "We asked ChatGPT for legal advice – here are five reasons why you shouldn’t" will turn up incident 704:

![image](https://github.com/responsible-ai-collaborative/aiid/assets/64484722/93dab759-73b2-4a67-adfc-31adaf35162e)

However, clicking on the "Show Details on Incident #&#x2060;704" button results in a page indicating the incident cannot be found:

![image](https://github.com/responsible-ai-collaborative/aiid/assets/64484722/60446991-6425-4147-b6c6-d7dcb1043121)

**Comment by collinstarkweather** [comment]
> Thanks @collinstarkweather ! I believe this is partially because the search index was updated with new incidents before the static site has been re-built.
> 
> That said, we should retrieve live incidents if they exist, regardless. @cesarvarela to confirm?

Thanks for your reply, @kepae.  Not knowing more about how data is structured internally, I'm not sure if this is problematic or not, but I did notice that there are two incidents that are designated incident 704 in the database:

![image](https://github.com/responsible-ai-collaborative/aiid/assets/64484722/b148885f-7337-450a-b639-2e63d69f75df)

**Comment by kepae** [comment]
Thanks @collinstarkweather . In this case, these are actually two of the indexed reports. Together they are contained by/substantiate Incident 704. (To be resolved shortly!)

**Comment by smcgregor** [comment]
@collinstarkweather I circled where you can change the displayed cards to singular incidents as named by AIID editors.

@kepae Our titles are so much better than the headlines that I am very frequently changing the dropdown. We should think about changing the default setting. Maybe do a quick poll on the Slack/Twitter/etc.

![340469617-b148885f-7337-450a-b639-2e63d69f75df](https://github.com/responsible-ai-collaborative/aiid/assets/64780/2bda00d7-7376-4a47-9200-849947796862)

**Comment by kepae** [comment]
All fixed here! Opened https://github.com/responsible-ai-collaborative/aiid/issues/2884 to track that idea!
