### ISSUE TITLE
Risk Checklisting Crash

### ISSUE THREAD

**Issue by smcgregor** [responsible-ai-collaborative/aiid#2916]
I can reliably produce a crash when I do the following:

1. Login
2. Click on risk checklisting
3. Click to create a new risk checklist
4. Click the "Add Risk" button
5. Open the new risk that was added to the list
6. Change the Risk Status to "Not Applicable"
7. The screen will now be blank with the following error in the console
8. 
<img width="982" alt="Screenshot 2024-06-26 at 6 50 04 AM" src="https://github.com/responsible-ai-collaborative/aiid/assets/64780/8a40d9ed-62dd-4687-af3d-6502e83a250b">

**Comment by pdcp1** [comment]
Closing this since it was merged into Staging
