### ISSUE TITLE
Email Notifications Post-build plugin failing: `Response not successful: Received status code 400`

### ISSUE THREAD

**Issue by kepae** [responsible-ai-collaborative/aiid#2944]
We are successfully populating the queue of incident notifications to send again, but now the plugin that runs after the site build is failing with a 400 error. As @pdcp1 pointed out, this may be related to an issue with one or both env variables:
`GATSBY_REALM_APP_ID` , `REALM_GRAPHQL_API_KEY`

However, these variables are both set and accessible to actions in the workflow in the "Build using Netlify" step:
https://github.com/responsible-ai-collaborative/aiid/blob/8a8979e45a21d178cc4d696783975c18aa99ae81/.github/workflows/deploy.yml#L94

Debugging continues...

**Comment by pdcp1** [comment]
**Update:** 

[Today's Production release](https://github.com/responsible-ai-collaborative/aiid/actions/runs/9781425993/job/27007092768#step:9:428) processed 6 notifications.

[All 6 notifications processed](https://github.com/user-attachments/files/16089745/customData.notifications.json)

I received 3 emails for New Incidents:
<img width="1380" alt="image" src="https://github.com/responsible-ai-collaborative/aiid/assets/6564809/96677c2b-8c85-4a7c-9c44-0ce414a59d71">

**Comment by pdcp1** [comment]
I will keep this issue open until we verify notifications continue to work in the next production releases.

**Comment by pdcp1** [comment]
From Sendgrid:
<img width="1527" alt="image" src="https://github.com/responsible-ai-collaborative/aiid/assets/6564809/606a4360-fbea-4fb1-857a-8584f90e7f32">

**Comment by pdcp1** [comment]
Update: Today's deploy https://github.com/responsible-ai-collaborative/aiid/actions/runs/9841302624/job/27169799868#step:9:426

It does not have any notifications to process. Let's continue monitoring until we have something to process and verify if the email notifications still work.

**Comment by pdcp1** [comment]
Update: Today's deploy https://github.com/responsible-ai-collaborative/aiid/actions/runs/9996425044/job/27632128923#step:9:428

26 notifications were processed
![image](https://github.com/user-attachments/assets/b878d9bc-051d-41fd-9591-c15b9b7413db)

<img width="1480" alt="image" src="https://github.com/user-attachments/assets/a7ca4744-41e4-4e5f-a709-ff916692dac2">

Closing the ticket since this is the second consecutive time it has worked as expected.
