### ISSUE TITLE
Page layout breaks on 100% default zoom, desktop + mobile

### ISSUE THREAD

**Issue by kepae** [responsible-ai-collaborative/aiid#2956]
The container seems to go beyond the screen width. Confirmed in Chrome (MacOS, Windows, + mobile view) and Edge (Windows).
Does *not* reproduce in Firefox (MacOS, desktop or mobile).
![Screenshot 2024-07-08 at 9 37 52 PM](https://github.com/responsible-ai-collaborative/aiid/assets/4238598/bc3c88b9-c6ff-4834-ae44-ff45d0683192)

![Screenshot 2024-07-08 at 9 39 11 PM](https://github.com/responsible-ai-collaborative/aiid/assets/4238598/52b34482-f003-441b-a66f-4f40021fd534)

![image](https://github.com/responsible-ai-collaborative/aiid/assets/4238598/c3f26aae-45ec-4369-acae-9994ce5ae7eb)

**Comment by lmcnulty** [comment]
Does this happen you initially load the page at a small screen size, or only when you resize the screen to a smaller size? In my brief testing, it looks like the latter.

**Comment by kepae** [comment]
Initial load at any size on my part. Up to about 1530px wide seems to be the breakpoint. Less than that the layout breaks, over it aligns further left properly.

**Comment by smcgregor** [comment]
When I edit the page DOM to remove the incident carousel, the width restores.

**Comment by kepae** [comment]
The desktop we could live with, but I think we ought to triage the mobile view. Either delete the carousel entirely for now or hide it on mobile screen sizes.

**Comment by kepae** [comment]
Weirdly, providing the style `hidden md:block` to hide the carousel on mobile also _fixes_ it in desktop/md...
![Screenshot 2024-07-08 at 10 14 38 PM](https://github.com/responsible-ai-collaborative/aiid/assets/4238598/7303c7ae-70be-4867-bdaa-bddb11c4261b)

**Comment by kepae** [comment]
Merged #2958 as a triage. CD is carrying it to production and ignoring test failures here: https://github.com/responsible-ai-collaborative/aiid/actions/runs/9850283450

**Comment by smcgregor** [comment]
It looks like there is a similar issue with the discover app.

<img width="1412" alt="Screenshot 2024-07-10 at 12 04 33 AM" src="https://github.com/responsible-ai-collaborative/aiid/assets/64780/09a22e6c-0b4b-4eef-a501-ca8ef4e0be84">

**Comment by kepae** [comment]
Good fix @clari182 ! :-)
