### ISSUE TITLE
Mobile drop-down menu does not collapse/close when clicking Discover or Submit buttons

### ISSUE THREAD

**Issue by kepae** [responsible-ai-collaborative/aiid#2996]
When clicking the "Discover" or "Submit" button in mobile views, the mobile menu does not collapse despite the page being correctly re-directed. The user can close the menu and they will be on the correct page, but this is confusing behavior. The user should expect to click the button once and the menu to not remain after navigation.

![image](https://github.com/user-attachments/assets/d22de9b2-b064-46c5-9d66-427c0ab1416a)

Tested in Chrome and Firefox mobile browsers.

**Comment by kepae** [comment]
@clari182 FYI if you have cycles!

**Comment by pdcp1** [comment]
Closing this since it was merged and fixed on Staging
