### ISSUE TITLE
Refactor Google analytics tag tracking to separate environments

### ISSUE THREAD

**Issue by kepae** [responsible-ai-collaborative/aiid#3015]
Currently, we use [gatsby-plugin-google-gtag](https://www.gatsbyjs.com/plugins/gatsby-plugin-google-gtag/) to configure our site with the given Google Analytics tag.

At the moment, this always ends up instrumenting the site in all environments (local, CI/CD, staging, production) with the same tag. To identify production traffic in the analytics we have to filter by host name to incidentdatabase.ai -- but this restricts access to some analytics features or makes them harder to use.

We should refactor so that either the tag is only present in production environments.
Alternatively, if there are better ways to separate environments for the sake of analytics, we can do that.

https://github.com/responsible-ai-collaborative/aiid/blob/f10e79b7f4a2f827366b19a7494a0898c6298c52/site/gatsby-site/gatsby-config.js#L67

**Comment by pdcp1** [comment]
This was merged into Staging, but let's close this issue when we merge it to [Production](https://github.com/responsible-ai-collaborative/aiid/pull/3260), in order to double-check and test the changes.

**Comment by clari182** [comment]
@kepae are we good to close this issue? Is google analytics only tracking in prod?

**Comment by kepae** [comment]
Yes, confirmed! Thank you.
