### ISSUE TITLE
Fix CSET taxonomies snapshots and CSV exports

### ISSUE THREAD

**Issue by pdcp1** [responsible-ai-collaborative/aiid#3023]
As part of this issue, we should:

- [x] Fix the existing CSET database dump by using the correct namespace
  - https://github.com/responsible-ai-collaborative/aiid/pull/3030 
- [x] Convert the CSET taxonomy CSV output into a more user-friendly format
  - https://github.com/responsible-ai-collaborative/aiid/pull/3082
- [x] Export GMF taxonomy in a similar CSV format
  - https://github.com/responsible-ai-collaborative/aiid/pull/3082
- [x] Analyse the possibility of migrating the DB dump code ([mongodb-awesome-backup](https://github.com/responsible-ai-collaborative/mongodb-awesome-backup)) to this repo as a Github action 
  - https://github.com/responsible-ai-collaborative/aiid/pull/3030

**Comment by kepae** [comment]
And after fixing + updating, also export the GMF taxonomy in a similar format such that the CSVs could be compared, if desired. :-)

**Comment by pdcp1** [comment]
All items are done. We can close this issue

**Comment by pdcp1** [comment]
@responsible-ai-collaborative/aiid-dev 
I just checked the [first automatic backup](https://github.com/responsible-ai-collaborative/aiid/actions/runs/10881621540) (it runs each Monday) and it works as expected 👍 

<img width="310" alt="image" src="https://github.com/user-attachments/assets/2892be4c-55f2-4029-9279-74f4836ca558">



This is the file generated: https://pub-a5fe3e44369c4cabb576fa0d2c09fdf6.r2.dev/backup-20240916100453.tar.bz2
