### ISSUE TITLE
Some searches crash the Discover app

### ISSUE THREAD

**Issue by cesarvarela** [responsible-ai-collaborative/aiid#3035]
From an email report: 

> I see that some searches are causing a console error. It looks like some values are null, which is causing the error. For instance, in the hit below, epoch_date_modified: null is causing this error. 
>  
> To reproduce: 
> 1. Search for "Harris"
> 2. Notice that the console error causes the results page to break. 
>  
> I attached a screenshot where I set a breakpoint. 
>  
> Here's an example of the result hit mentioned above:
>  
> {
>     "authors": [
>         "James Liddell"
>     ],
>     "epoch_date_downloaded": 1724025600,
>     "epoch_date_modified": null,
>     "epoch_date_published": 1724025600,
>     "epoch_date_submitted": 1724025600,
>     "image_url": "",
>     "language": "en",
>     "report_number": 4006,
>     "source_domain": "[the-independent.com](http://the-independent.com/)",
>     "submitters": [
>         "Daniel Atherton"
>     ],
>     "title": "Trump posts AI-generated image of Harris speaking at DNC with communist flags",
>     "name": "Trump posts AI-generated image of Harris speaking at DNC with communist flags",
>     "url": "https://www.the-independent.com/news/world/americas/us-politics/trump-ai-communism-harris-dnc-b2598303.html",
>     "tags": [],
>     "cloudinary_id": "",
>     "text": "Donald Trump has taken a last-minute swipe at Kamala Harris ahead of the first day of the Democratic National Convention (DNC) in Chicago, as he posted an AI-generated image of the vice president speaking to a jam-packed crowd of Communists.\n\nHarris has been on the receiving end of a barrage of personal attacks from the former president as she pulls ahead in the national polls -- including all seven battleground states, bar Nevada.\n\nNow, Trump has upped the ante, using the very technology he falsely accused his Democratic rival's campaign of using to over-inflate her crowd sizes at Detroit Metro Airport last week: artificial intelligence.\n\nThe Republican presidential nominee posted the AI image to X on Sunday showing a female figure, which appears to be Harris, wearing a red blazer and speaking to a giant crowd in front of a hammer and sickle, the symbol of the Soviet Union, cascading from the ceiling. The word Chicago is blown up and illuminated in large red letters in the background -- a clear nod to the DNC which kicks off in Illinois on Monday evening.\n\nMore than 50,000 visitors -- including delegates, journalists and invited guests -- are expected to descend on the Windy City for the four-day convention at the United Center as the Harris-Walz ticket ceremonially gets rung in.\n\nJust a few weeks ago, President Joe Biden was expected to take to the DNC stage to deliver his headline speech as the party's 2024 presidential nominee. Now, along with First Lady Jill, he will deliver a message of unity as the outgoing president on Monday after stepping off the Democratic ticket last month.\n\nOther political heavyweights slated to headline the gathering include the Clintons, Obamas and the grandson of former president Jimmy Carter, Jason Carter.\n\nHarris will close out the convention on Thursday as she accepts the Democratic presidential nomination, outlining a roadmap for the future that pushes back against Trump's rhetoric that the nation is in decline.\n\nIn an attempt to undermine Harris at the DNC, Trump and his Republican allies are planning a convention of their own in his Chicago hotel, with immigration, crime and the economy being its key themes.\n\nThe former president and running mate JD Vance will also host rallies and smaller \"messaging events\" around the country as Democrats are concentrated in Chicago, according to his campaign team.\n\nTrump's posting of the AI-generated photo comes a day after he attempted to align the vice president with the far-left during a rally in Wilkes-Barre, Pennsylvania, on Saturday.\n\nHe denounced Harris as going \"full communist\" for her economic policies while, rather confusingly, also branding her a \"fascist\".\n\n\"In her speech yesterday, Kamala went full communist,\" he said, in reference to Harris's crackdown on so-called \"price gouging on food,\" she announced in Raleigh, North Carolina on Friday.\n\n\"Comrade Kamala announced that she wants to institute socialist price controls. You saw that never worked before... it will cause rationing, hunger and skyrocketing prices,\" he added.\n",
>     "mongodb_id": "66c3b11ba7feb77170e84ce1",
>     "featured": 0,
>     "is_incident_report": true,
>     "namespaces": [],
>     "classifications": [],
>     "incident_id": 767,
>     "incident_date": "2024-08-18",
>     "epoch_incident_date": 1723939200,
>     "incident_title": "AI Image of Kamala Harris at DNC with Communist Flags Circulated by Trump",
>     "incident_description": "Donald Trump shared an AI-generated image on social media that falsely depicted Kamala Harris speaking at a DNC event surrounded by communist imagery including the hammer and sickle of the Soviet Union. The image was intended to undermine Harris ahead of the Democratic National Convention and to suggest that her views are aligned with communism.",
>     "objectID": "4006",
>     "_snippetResult": {
>         "text": {
>             "value": "Donald Trump has taken a last-minute swipe at Kamala Harris ahead of the first",
>             "matchLevel": "none"
>         }
>     },
>     "_highlightResult": {
>         "title": {
>             "value": "Trump posts AI-generated image of Harris speaking at DNC with communist flags",
>             "matchLevel": "none",
>             "matchedWords": []
>         },
>         "text": {
>             "value": "Donald Trump has taken a last-minute swipe at Kamala Harris ahead of the first day of the Democratic National Convention (DNC) in Chicago, as he posted an AI-generated image of the vice president speaking to a jam-packed crowd of Communists.\n\nHarris has been on the receiving end of a barrage of personal attacks from the former president as she pulls ahead in the national polls -- including all seven battleground states, bar Nevada.\n\nNow, Trump has upped the ante, using the very technology he falsely accused his Democratic rival&#39;s campaign of using to over-inflate her crowd sizes at Detroit Metro Airport last week: artificial intelligence.\n\nThe Republican presidential nominee posted the AI image to X on Sunday showing a female figure, which appears to be Harris, wearing a red blazer and speaking to a giant crowd in front of a hammer and sickle, the symbol of the Soviet Union, cascading from the ceiling. The word Chicago is blown up and illuminated in large red letters in the background -- a clear nod to the DNC which kicks off in Illinois on Monday evening.\n\nMore than 50,000 visitors -- including delegates, journalists and invited guests -- are expected to descend on the Windy City for the four-day convention at the United Center as the Harris-Walz ticket ceremonially gets rung in.\n\nJust a few weeks ago, President Joe Biden was expected to take to the DNC stage to deliver his headline speech as the party&#39;s 2024 presidential nominee. Now, along with First Lady Jill, he will deliver a message of unity as the outgoing president on Monday after stepping off the Democratic ticket last month.\n\nOther political heavyweights slated to headline the gathering include the Clintons, Obamas and the grandson of former president Jimmy Carter, Jason Carter.\n\nHarris will close out the convention on Thursday as she accepts the Democratic presidential nomination, outlining a roadmap for the future that pushes back against Trump&#39;s rhetoric that the nation is in decline.\n\nIn an attempt to undermine Harris at the DNC, Trump and his Republican allies are planning a convention of their own in his Chicago hotel, with immigration, crime and the economy being its key themes.\n\nThe former president and running mate JD Vance will also host rallies and smaller &quot;messaging events&quot; around the country as Democrats are concentrated in Chicago, according to his campaign team.\n\nTrump&#39;s posting of the AI-generated photo comes a day after he attempted to align the vice president with the far-left during a rally in Wilkes-Barre, Pennsylvania, on Saturday.\n\nHe denounced Harris as going &quot;full communist&quot; for her economic policies while, rather confusingly, also branding her a &quot;fascist&quot;.\n\n&quot;In her speech yesterday, Kamala went full communist,&quot; he said, in reference to Harris&#39;s crackdown on so-called &quot;price gouging on food,&quot; she announced in Raleigh, North Carolina on Friday.\n\n&quot;Comrade Kamala announced that she wants to institute socialist price controls. You saw that never worked before... it will cause rationing, hunger and skyrocketing prices,&quot; he added.\n",
>             "matchLevel": "none",
>             "matchedWords": []
>         },
>         "incident_title": {
>             "value": "AI Image of Kamala Harris at DNC with Communist Flags Circulated by Trump",
>             "matchLevel": "none",
>             "matchedWords": []
>         },
>         "incident_description": {
>             "value": "Donald Trump shared an AI-generated image on social media that falsely depicted Kamala Harris speaking at a DNC event surrounded by communist imagery including the hammer and sickle of the Soviet Union. The image was intended to undermine Harris ahead of the Democratic National Convention and to suggest that her views are aligned with communism.",
>             "matchLevel": "none",
>             "matchedWords": []
>         }
>     },
>     "__position": 9
> }

**Comment by pdcp1** [comment]
Closing this issue since the fix was merged into Staging

**Comment by kepae** [comment]
I do not think this issue is resolved by the above change. Please also see:
* https://github.com/responsible-ai-collaborative/aiid/issues/3040#issuecomment-2310277035

**Comment by pdcp1** [comment]
@kepae I just tested on **Staging** all the reported cases and they work as expected. They all appeared to be connected to the fields that were missing. Fixed on https://github.com/responsible-ai-collaborative/aiid/pull/3037

 - searching by "Harris"
 - sorting by "Newest Published Date"
 - sorting by "Newest Submitted Date"
 - filtering by Date and choosing the last 2 months (e.g. July 2024 - August 2024)
 
 The fix has not yet been released to production.

@cesarvarela maybe we should add some tests that verify the filters work. What do you think?

**Comment by kepae** [comment]
Ah, I think you're right @pdcp1 -- sorry, didn't realize this wasn't deployed in production yet. :-)
