### ISSUE TITLE
Submission freezing after approval

### ISSUE THREAD

**Issue by clari182** [responsible-ai-collaborative/aiid#3053]
Submissions are freezing after approval. Approval does go through, but no success message or redirect to the submission list.

**Comment by cesarvarela** [comment]
I have a fix for this here: https://github.com/responsible-ai-collaborative/aiid/pull/3027/files#diff-717d21375b31a03c9c172b2ce5a1e1a18ed82ab73e6ee402bd676c886e9c18d8R63

**Comment by cesarvarela** [comment]
The fix has been merged into https://github.com/responsible-ai-collaborative/aiid/pull/3041
