### ISSUE TITLE
Email notifications are not working on Production

### ISSUE THREAD

**Issue by pdcp1** [responsible-ai-collaborative/aiid#3097]
From production Rollbar:

[[Process Pending Notifications: Submission Promoted]: read not permitted](https://app.rollbar.com/a/seanbmcgregor/fix/item/AIID/6857)

-----

Email notifications are working correctly on the GitHub action on Staging.

This is the Atlas MongoDB log on Staging:

<img width="1373" alt="image" src="https://github.com/user-attachments/assets/f2fd138b-700d-4647-b955-2c35b6d0d4e3">

It uses this user to call the `processNotification` mutation from the GitHub action:

**User name:** `staging-graphql`
**User id:** `624e7e038fd3c8e5c7770aa0`

<img width="1567" alt="image" src="https://github.com/user-attachments/assets/b4c3810f-b390-4b03-993e-287b3aff0053">

@kepae We should check the same on Production and see if the user has the permissions needed.

**Comment by cesarvarela** [comment]
I will start migrating this collection to our API today or tomorrow, so the problems at least will be different 🥳

**Comment by kepae** [comment]
I believe this issue is now fixed with the cleanup in #3104.
