### ISSUE TITLE
Classifications editor is endlessly loading

### ISSUE THREAD

**Issue by npit** [responsible-ai-collaborative/aiid#3105]
Can't get the classifications editor widget to load.
Tried on multiple incidents, on incognito / hard refresh, on firefox and vivaldi.

![image](https://github.com/user-attachments/assets/1362eb3f-1736-4b91-91b6-5993b99ceaed)
![image](https://github.com/user-attachments/assets/b711fe11-f196-4a9d-9edc-622165bcf702)

**Comment by kepae** [comment]
This might be the same thing as:
* #3106 

Investigating!

**Comment by kepae** [comment]
I can no longer reproduce this and believe this is resolved with #3106. Please open if it re-occurs.
