### ISSUE TITLE
Production Workflow ignores Playwright test results

### ISSUE THREAD

**Issue by cesarvarela** [responsible-ai-collaborative/aiid#3167]
This workflow should not be deployed, because test-playwright-full failed:

<img width="1122" alt="image" src="https://github.com/user-attachments/assets/f0e8b5f2-45db-4f9d-98cc-847695dfb469">

https://github.com/responsible-ai-collaborative/aiid/actions/runs/11447858175

**Comment by pdcp1** [comment]
Closing this since it was merged into Staging
