### ISSUE TITLE
Improve "Submit" button in submission form

### ISSUE THREAD

**Issue by clari182** [responsible-ai-collaborative/aiid#3185]
`Submit` button can be mistaken for the next step buttons

Possible solutions:
- Change `Submit` button location
- Add a confirmation message before submitting

**Comment by kepae** [comment]
I think adding the confirmation message makes the most sense for now. Should we indicate in the dialog something like:

"Please confirm you are ready to submit this report. Report details cannot be changed after submission."

Options: Return to submission, Submit

What do you think?
