### ISSUE TITLE
Email Notification System: Action Items & Recovery Plan

### ISSUE THREAD

**Issue by cesarvarela** [responsible-ai-collaborative/aiid#3217]
## Fixes & Prevention
- [x] Confirm original bugfix for email addressing is in production (César)
- [x] Add email pipeline validation function:
  - [x] Implement ASSERT-like function for single recipient validation
  - [x] Add unit tests for validation function
- [x] Improve error reporting for process notification API
- [x] Disable notifications during forced deploys

## Review & Security
- [x] Verify Mailersend token pause functionality
- [x] Verify user data isolation from staging backups

## Cleanup & Recovery
- [x] Run migration to remove pending notifications
- [x] Re-enable notification system

**Comment by cesarvarela** [comment]
Only task left is to check the pause functionality @kepae

**Comment by kepae** [comment]
@cesarvarela if you have a local dev setup, would you please consider pausing the tokens and observing if that is sufficient?
Otherwise I will create a dev setup, as I haven't done that yet.

I really can't imagine "pausing" doesn't work, but we're being thorough.

**Comment by cesarvarela** [comment]
Regarding the pausing of tokens, it depends on how the mailer send API is used:

If using an API token with no SMTP user, pausing works as expected.

If using an API token with an SMTP user, you have to pause both the token and the SMTP user.


To send emails from a dev environment without validating a domain, you have to create an SMTP user, where pausing only the token won't work.
