### ISSUE TITLE
Database Migrations

### ISSUE THREAD

**Issue by cesarvarela** [responsible-ai-collaborative/aiid#416]
To enforce a strict schema, some collections will need  updates:

- [ ] `Quality Control` classification should be bool, but some instances are `null` ( I'm setting the field as `mixed` temporarily)
- [ ] Taxa collection `permited_values` should non-nullable array
- [x] incidents collection to incident_reports and make the incidents collection have only one record per incident.

...

**Comment by smcgregor** [comment]
Let's also migrate the incidents collection to incident_reports and make the incidents collection have only one record per incident.

**Comment by smcgregor** [comment]
Closed with #559
