### ISSUE TITLE
404 page is broken

### ISSUE THREAD

**Issue by cesarvarela** [responsible-ai-collaborative/aiid#469]
![image](https://user-images.githubusercontent.com/1172479/154968457-71267408-9542-457d-b02f-5bed6c972f9c.png)

**Comment by smcgregor** [comment]
I think this may be a Netlify hosting issue. The 404 page exists when you hit its address on localhost.

**Comment by cesarvarela** [comment]
This is not happening anymore. It seems like now all URLs that should  display a 404 get redirected to `/`

**Comment by smcgregor** [comment]
Production and staging both show the message you give above, at least for me.

**Comment by cesarvarela** [comment]
Oh, interesting, it seems it is browser dependent... investigating..

**Comment by cesarvarela** [comment]
Still broken in staging :/ https://staging-aiid.netlify.app/dasdasd going to look a little bit more into it later

**Comment by cesarvarela** [comment]
This exact same issue is being tracked here: https://github.com/netlify/netlify-plugin-gatsby/issues/330

**Comment by cesarvarela** [comment]
probably fixed by #555
