### ISSUE TITLE
Resources taxonomy is missing from db backups

### ISSUE THREAD

**Issue by cesarvarela** [responsible-ai-collaborative/aiid#497]
Maybe add it as a migration?

**Comment by smcgregor** [comment]
You checked the most recent one? It should be in the MongoDB object, but needs to be added here for the CSV files to populate: https://github.com/aiincidentdatabase/mongodb-awesome-backup/blob/master/bin/backup.sh#L72

**Comment by cesarvarela** [comment]
The last snapshot from here seems kind of old:

https://incidentdatabase.ai/research/snapshots?lang=en

Maybe because of this?
![image](https://user-images.githubusercontent.com/1172479/157672332-4ac47fae-fed4-44d1-a3e0-f1b6a1c9f336.png)

**Comment by smcgregor** [comment]
I just clicked it to manually run. GitHub does this because it doesn't believe projects really want to sit there periodically running workflows. I also told it to run for the next 60 days...

**Comment by smcgregor** [comment]
I believe this is taken care of.
