### ISSUE TITLE
Add Normative Fields to New Incidents Collection

### ISSUE THREAD

**Issue by smcgregor** [responsible-ai-collaborative/aiid#500]
The following fields should be added to the new incidents collection and initialized from the CSET taxonomy values,

* Incident title (string)
* Incident description (string)
* Alleged harmed or nearly harmed parties (string)
* Alleged developer of AI system (string)
* Alleged deployer of AI system (string)

**Comment by cesarvarela** [comment]
Seems like field names here are slightly different from the names in the taxonomy.  Right now I have:

- Incident title -> title of first report with same incident_id
- Incident description ->   description of first report with same incident_id
- Alleged harmed or nearly harmed parties -> ?
- Alleged developer of AI system (string) -> CSET `System developer`
- Alleged deployer of AI system (string) -> ?

**Comment by smcgregor** [comment]
* Incident title (string) -> title of first report sorted by publish date with same incident_id
* Incident description (string) -> CSET `Short description of the incident`
* Alleged harmed or nearly harmed parties ([string]) -> (leave blank for now)
* Alleged developers of AI system ([string]) -> CSET `System developer`
* Alleged deployers of AI system ([string]) -> CSET `System developer`

Does this sound good?

**Comment by cesarvarela** [comment]
I just noticed that `System developer` is defined as an array in the classifications schema, but you mention that `Alleged developer of AI system ` and `Alleged deployer of AI system` should be strings; what should I do?

**Comment by smcgregor** [comment]
Array is better here.
