### ISSUE TITLE
Incident Submission and Edit Form

### ISSUE THREAD

**Issue by smcgregor** [responsible-ai-collaborative/aiid#524]
Recent changes have introduced collection normalization to the incident reports so there are separate collections between incidents and incident reports. Now we need to enforce the relationship between these two collections.

1. [x] A new form component for editing incidents needs to be created.
2. [x] The citation pages need an "Edit Incident" button that is only displayed to authenticated users 
3. [x] The `epoch_incident_date` and `incident_date` fields should be removed from the reports collection and should only be on the incidents collection.
4. [ ] This documentation needs updating: https://github.com/responsible-ai-collaborative/aiid/blob/staging/mongo.md
5. [x] Also, #520 

Once these are in place, I (Sean) will do the following:

1. [ ] Process all incidents in the database to have the normative fields #514 
2. [ ] Display the following sentence at the top of all citation pages: "Alleged incident: An intelligent system developed by {organization} and deployed by {organization}  harmed or nearly harmed {harmed entity} when {title}"
3. [ ] Display the current description from the database below the sentence

**Comment by cesarvarela** [comment]
Should there be a Delete Incident button?

**Comment by smcgregor** [comment]
No, in the future we will add a button that adds a record to the duplicates collection, which serves as a pointer to a different incident record. Let's presume incidents are permanent for now since that is more complicated logic.

**Comment by cesarvarela** [comment]
Docs updated.

**Comment by smcgregor** [comment]
Closing this since we have finished most of this and moved on.
