### ISSUE TITLE
Bad Incident Report Date on Landing Page

### ISSUE THREAD

**Issue by smcgregor** [responsible-ai-collaborative/aiid#536]
The current "latest incident report" content gives a date of 1969. See: https://incidentdatabase.ai/

**Comment by smcgregor** [comment]
@cesarvarela can you do a hotfix to master on this one?

**Comment by smcgregor** [comment]
Potentially removing the content block until this is fixed in your feature branch.

**Comment by smcgregor** [comment]
FYI @cesarvarela https://github.com/responsible-ai-collaborative/aiid/commit/0f68fd3e049ed96404f4c39f0138ff276e1efa02

**Comment by cesarvarela** [comment]
Fixed in #549
