### ISSUE TITLE
Broken Incident Ingestion

### ISSUE THREAD

**Issue by smcgregor** [responsible-ai-collaborative/aiid#566]
I just added two new incident reports, both of which should be associated with new incidents. The first report was associated with a new incident (incident_id 178), but the second incident report was also associated with incident_id 178. It gets weirder, details below.

The following shows the incidents collection, where there are two documents with incident_id 178 and only the first of them has reports, both of which have the same report number.
![Screen Shot 2022-04-27 at 4 12 23 PM](https://user-images.githubusercontent.com/64780/165646228-fffa7ed3-4402-40d3-87aa-8ce75cf75962.png)

The reports collection has,

![Screen Shot 2022-04-27 at 4 10 59 PM](https://user-images.githubusercontent.com/64780/165646233-3235d9ea-26f4-4138-bd9b-7f5c3e47c83b.png)

The report_number is duplicated.

(scrolling down to have the complete picture)

![Screen Shot 2022-04-27 at 4 11 07 PM](https://user-images.githubusercontent.com/64780/165646231-6aea1cfa-2ddb-41db-b1d8-fc4a032fed89.png)

**Comment by cesarvarela** [comment]
This is caused by Apollo's cache, which is a bit aggressive and doesn't query the last incident_id/report_number the second time and then 💥 

going to disable caching for that query...

**Comment by cesarvarela** [comment]
It should be fixed by #567. The entire process will be less messy once #522 is up.

**Comment by smcgregor** [comment]
I deleted the last added report and incident. If everything builds properly, I'll add back the following incident and report.
```
https://www.vox.com/future-perfect/23023538/ai-dalle-2-openai-bias-gpt-3-incentives 

Submitter: Irina Borisova King
```

**Comment by smcgregor** [comment]
I refreshed the page between adding incident reports, so I didn't put this through its paces, but I believe it is fixed.
