### ISSUE TITLE
Bad Data on Staging

### ISSUE THREAD

**Issue by smcgregor** [responsible-ai-collaborative/aiid#578]
I am opening this issue then closing it immediately since the immediate cause is solved, but we may need to reopen this if it reoccurs -- I don't know what caused the data issue to begin with.

Build Problem:
![Screen Shot 2022-04-28 at 5 14 18 PM](https://user-images.githubusercontent.com/64780/165867274-4069e863-84c3-439a-9f4c-6c80c55510f4.png)

This also happens when building locally.

This record was causing the problem on staging:

![Screen Shot 2022-04-28 at 5 08 54 PM](https://user-images.githubusercontent.com/64780/165867148-6d7170d3-e5f2-431e-9a9b-fb1cdbfe2fe6.png)

I fixed the problem by deleting the entry in the array on staging, and now the build is passing.

FYI @cesarvarela

**Comment by smcgregor** [comment]
@cesarvarela I reopened this because ~6 reports seem to have disappeared from the database on staging for incident number 10. This is breaking the build:

https://app.netlify.com/sites/staging-aiid/deploys/626b30aff3d98903d8605711

I am guessing this is either the product of a rogue test case, or one of us messed with the data?

**Comment by smcgregor** [comment]
I just updated the staging database from production without changing the user data and ran one of the offending tests locally. It passed, so I am going to retry the build.

**Comment by smcgregor** [comment]
@cesarvarela I updated this issue to read `Bad Data on Staging`. Please feel free to close it if you think the issue is not likely to recur, tests are currently passing.

**Comment by cesarvarela** [comment]
It hasn't happened on my env (yet) so hopefully, it is just because of #566
