### ISSUE TITLE
Improve Incident Table App

### ISSUE THREAD

**Issue by smcgregor** [responsible-ai-collaborative/aiid#584]
#541 introduces a table view for the incidents collection. I am going to merge it to staging, but I am not going to place it in the navigation yet.

Improvements to be made,

(blocking general availability)
- [x] When applying a tag in the form, the tag is not applied if you do not terminate the tag by pressing enter
- [x] Make the incident number a link to the citation page
- [x] The loading spinner should present a more friendly loading picture
- [x] The `Actions` column should be hidden if you are not logged in
- [x] Zebra the rows so it is easier to read

(good to have but not blocking)
- [x] The table header should float as you scroll down the page
- [x] Should have the filtering functionality of `/apps/classifications`
- [ ] Expand the row to display more text after clicking on the row
- [x] While a record is updating, the modal's controls should be disabled
- [x] Toast indicating the record has been updated should trigger the modal to disappear
- [x] The `save` and `close` button should be on the same line, with one pulling left and the other pulling right. It may also be better to label the `save` button as `update`.

![Screen Shot 2022-04-29 at 5 58 02 PM](https://user-images.githubusercontent.com/64780/166084324-c1322519-e86b-4fa8-9c26-85c1232ab813.png)

**Comment by cesarvarela** [comment]
_When applying a tag in the form, the tag is not applied if you do not terminate the tag by pressing enter_
Do you think it should commit the tag on blur?

_he Actions column should be hidden if you are not logged in_
is there a role for this or just `isAdmin`?

_Should have the filtering functionality of_
The filters appear if you click on the filter icon, do mean to have the filters always visible or something else?

**Comment by smcgregor** [comment]
It should commit the tag when you submit the form, I think the blur event triggers when you push the submit button?

Any of the editor roles would work here.

If you compare to the table presented for classifications, I think the affordances there were clearer on what you could do with the column.

**Comment by smcgregor** [comment]
Bug:

- [ ] `Alleged Developer of AISystem` is not presenting anything in the table, when you can see the expected contents in the edit form.

**Comment by smcgregor** [comment]
Bug:

- [ ] I pressed enter when typing in an alleged deployer of AI system and the whole app crashed.

<img width="1467" alt="Screen Shot 2022-05-14 at 8 28 18 PM" src="https://user-images.githubusercontent.com/64780/168455891-b0747200-4c26-47a1-a740-2e7e40cb2d1c.png">
