### ISSUE TITLE
Duplicated fields in Submitted reports ui

### ISSUE THREAD

**Issue by cesarvarela** [responsible-ai-collaborative/aiid#596]
`authors` and `submitters` fields are twice, not sure if there is a reason for that.

<img width="978" alt="image" src="https://user-images.githubusercontent.com/1172479/167961507-6176bcbd-79c3-42ce-9a27-88f448427003.png">

Also this fields are rendered using an `EditableListItem` components that seems to have an inline edit functionally that isn't working at the moment.

**Comment by smcgregor** [comment]
Both are bugs. I have not placed a high priority on it because I am currently the only one managing this queue. That is changing as I type, however.

**Comment by lmcnulty** [comment]
Resolved by https://github.com/responsible-ai-collaborative/aiid/pull/641.
