### ISSUE TITLE
Integrate NLP API for Incident Similarity

### ISSUE THREAD

**Issue by smcgregor** [responsible-ai-collaborative/aiid#597]
[This repository](https://github.com/responsible-ai-collaborative/nlp-lambdas) provides an AWS lambda function for assessing similarity of incidents. It has not been integrated into the user interface in any way and is a service developed by a team of capstone students who worked on it for their senior project over 8 months. This issue is to track developments on integrating the lambda function with the user interface. Targeted user stories include,

- [ ] "I want to know if this candidate incident report is related to any incident reports currently in the database so I can avoid [ingesting](https://incidentdatabase.ai/apps/submitted) duplicate incidents"
- [ ] "I want to know which incidents are semantically related to the current incident on the [citation page](https://incidentdatabase.ai/cite/16?lang=en) so I can browse incidents on the same theme"
- [ ] "I want to know whether any news articles being published today are similar to incidents already in the database so I can monitor the world for new incidents"

I ordered these user stories from least to most challenging in terms of the number of hours required to resolve them.

This is the start of a much larger backlog, but the initial effort should be confined to the following,

- [x] Review the documentation of the lambda repository and ask for clarification if anything is not clear
- [x] Start up a development version of the AWS lambda function
- [ ] Integrate the lambda function with the "related incidents" feature as a new component that displays incidents most related to incident that is being considered for ingestion

That completes drop one. The next drop should include,

- [ ] Propose a design for the "related incidents" feature (use some form of mockup tool)
- [ ] Get design reviewed (synchronously)
- [ ] Design Checklist
  - [ ] The NLP API is only hit for related incidents when ingesting new reports
  - [ ] The related incidents can be edited on the citation page
  - [ ] There is adequate documentation to how this is working
  - [ ] There is an opportunity for end users to flag problems in the design
  - [ ] Includes a "related incidents" field in the incidents collection and schema
  - [ ] Whenever a new report is ingested into the database, related incidents fields should be appropriately updated
- [ ] Adopt a tSNE (or similar) rendering library for JS
- [ ] Adopt visualization design
- [ ] Integrate visualization as new application into the database

**Comment by smcgregor** [comment]
WIP: https://github.com/responsible-ai-collaborative/aiid/pull/652

**Comment by lmcnulty** [comment]
Mock-up for incident similarity on cite page:

https://user-images.githubusercontent.com/25443411/173131439-1fc1b05c-50d8-4d5e-83d4-6607edf9886d.mp4

- The eye icon will take the user to the eventual visualization
- The question mark icon will take the user to some explanation of the NLP system (blog post?)
- The edit icon will will be visible without hover -- it should only be shown to editors, however.

You can see the [interactive mock-up on Penpot](https://design.penpot.app/#/view/01f56010-e754-11ec-970d-75f6b8214121?page-id=01f56011-e754-11ec-970d-75f6b8214121&section=interactions&index=0&share-id=c3b9c7d0-e8e5-11ec-8abe-f940e3befd53).

**Comment by smcgregor** [comment]
@lmcnulty Great mock up! Comments below,

1. This shifts the citation page to two column format, which I think is an improvement, but it will need to shift to single column in mobile.
2. The "Related Report, By textual similarity" is not true for cases where a human has manually selected a related incident or affirmed the machine selection, so I think the subheader may need to be changed.
3. You can presume this will roll out with a blog post you can link to in order to explain what is happening.
4. The flags should be on the header or on the individual cards, but not both. It works to have both, but I think it is a bit more cluttered.
5. You are currently scoping to "Related Reports," but I think it is more appropriate to the API to make it display "Related Incidents," where you pull the information provided [here](https://incidentdatabase.ai/apps/incidents) and display an arbitrary image from one of the reports.
6. The "Related Reports" modal looks great, but I don't think we should support a text search box there. I think we should employ the same cards that present when you are submitting a new incident, which look for incidents that are related based on author, dates, and (soon) semantic similarity of text. If the user wants to do something more complicated than this, then they can go to the "Discover" application and poke around. With this change , the responsibility of the modal is to remove related _incidents_ and support adding related incidents by a single form element.
7. Rather than have an eye symbol link to an eventual relatedness visualization, I think having the "Related Reports" header link to a `/apps/related#INCIDENT_ID` visualization would likely present a better affordance.

**Comment by lmcnulty** [comment]
With changes according to (4), (5), and (7):

![related-incidents-mockup_revised](https://user-images.githubusercontent.com/25443411/173403032-e4d05568-5a7f-42f3-b8a5-3ae013064d43.png)

For (2), maybe we could add a separate subheader for editor-selected incidents:

![related-incidents-mockup_when-edited](https://user-images.githubusercontent.com/25443411/173403109-d5e6caf0-e6e9-4688-9710-56e6886fb3bc.png)

For (1), the options that come to mind are (a) putting the sidebar in a modal that can be brought up with a button attached to each report or (b) just putting the list of related incidents under reach report. I'll work on a mockup for that.

I need to think more about (6).

**Comment by lmcnulty** [comment]
Mobile view with "similar incidents," no domain in card:

<table>
<tr>
<td>
<img height="500" src="https://user-images.githubusercontent.com/25443411/173598117-9f437a20-cce9-4974-b607-7badac82fad5.png">
</td>
<td>
<img height="500" src="https://user-images.githubusercontent.com/25443411/173598935-ed8c7984-d4e3-426a-9ddb-7ccf0be21f5a.png">
</td>
</tr>
</table>

**Comment by lmcnulty** [comment]
Here's my current draft of the system design:

- Add `nlp_similar_incidents` field to `submissions` and `reports`
  - value is a list of objects with fields `incident_id` (int), `similarity` (float)
- Add `editor_similar_incidents` (`[int]`), `editor_dissimilar_incidents` (`[int]`), and `flagged_incidents` (`[int]`) fields to `reports`
  - These contain only the incident ids, since they don't have a numeric similarity
- On report submission, set `nlp_similar_incidents` to the values returned by the api
- On promotion, copy `nlp_similar_incidents` over to new report,
  initialize `editor_similar_incidents`, `editor_dissimilar_incidents`, and `fladded_incidents` as `[]`
- When a report's text is edited, hit the api and update `nlp_similar_incidents`
- Add a function that optionally runs and build time
  - If possible, it should trigger `nlp-lambdas/state_update.py`.
    Otherwise, whoever is running the build should manually run `state_update.py` in advance.
  - It should then call the api for every report and update its `nlp_similar_incidents`.
- On `/cite`, for each report
  - for each incident in `nlp_similar_incidents` and `editor_similar_incidents`
    - if the incident is not in `nlp_dissimilar_incidents`
      - query and display the title, date, number of reports, and first report image
- An editor can add an incident to `editor_similar_incidents` or to `editor_dissimilar_incidents`
- When a user flags an incident, set `flag` to true 
  and make the flag icon appear red for that user
  - Don't indicate to every user that an incident is flagged
    → It would look bad if a user saw that items
    were correctly flagged but hadn't been handled yet.

**Comment by lmcnulty** [comment]
- Semantically related incidents on the submission form were added in #736.
- Similar Incidents on the citation page were added in #761.
- A spatial visualization was added in #779.
- A draft for the use case "I want to know whether any news articles being published today are similar to incidents already in the database so I can monitor the world for new incidents" is open in #1024.

I believe every point in this issue has been addressed over the past three months, so it can now be closed.
