### ISSUE TITLE
Citation Retrieval Date Goes Blank

### ISSUE THREAD

**Issue by smcgregor** [responsible-ai-collaborative/aiid#600]
@cesarvarela The build on staging is now failing with an empty string being reported. See: https://app.netlify.com/teams/netlify-alp70lu/builds/627ff248ec6ef800089a8d47

It looks like this is related to #593. I am going to clear the cache and retry, but I believe this will pop up in builds every 24 hours.

**Comment by smcgregor** [comment]
Same problem after clearing the cache and running again: https://app.netlify.com/sites/staging-aiid/deploys/627ff61d8e33d51f5f2f9294

**Comment by cesarvarela** [comment]
looking

**Comment by cesarvarela** [comment]
if #601 doesn't work let's skip the test and try with something else later, because this is a cypress thing, the text is there.
