### ISSUE TITLE
Use Internet Archive Document Indexing for Permalinks

### ISSUE THREAD

**Issue by smcgregor** [responsible-ai-collaborative/aiid#61]
Many of the linked reports have their address change or their content leaves the web entirely. The internet archive offers a variety of services for permanently indexing URLs. These services should be used to update URLs as they move about and to permanently link the content as stored by the archive.

https://blog.archive.org/2017/01/25/see-something-save-something/

https://blog.archive.org/2016/09/27/persistent-url-service-purl-org-now-run-by-the-internet-archive/

**Comment by smcgregor** [comment]
@cesarvarela please check whether we can do a client-side URL for this without DB changes, otherwise links or example boilerplate for intergration server side would be useful.

**Comment by smcgregor** [comment]
Addressed in https://github.com/PartnershipOnAI/aiid/pull/222

I am going to leave this issue open a bit longer since I would like to return to this after we test the feature in production. We should likely apply this to all source links and not just the links in the cards. I don't want to make the change globally until we know this is no issues with it.

**Comment by smcgregor** [comment]
@cesarvarela I am taking you off this very old issue, but I am going to leave it in the backlog. The UX around links out to the web content could be greatly improved. Sometimes we link to the archive, sometimes to the original link, this should be improved in the coming UI update.

**Comment by lmcnulty** [comment]
I'm inclined to think we should submit the link to the archive on report submission. 

When displaying links, I can think of a few options:

- Use a link-styled [split dropdown button](https://getbootstrap.com/docs/4.2/components/dropdowns/#split-button) to allow switching between a default and alternative destination.
  - Probably not many people would think to use it.
  - Should we default to the original source, or the archive?
- Link to the original, but display an archive.org icon beside it linking to the archived version
  - Seems like the option that discloses the choice most clearly, but only to those who already know about the Internet Archive. 
  - Would also add visual clutter.
- Add a build-time option to query all the report urls, and display the archive url if the response code is non-200.
  - Most helpful to the user
  - Also most complicated.
  - Could be combined with the first option, affecting the default but still including both links.

**Comment by smcgregor** [comment]
I think I prefer the first option here, with the default being the original
source. Tough call though. I don't think we should put in all the build
time mechanics yet.
