### ISSUE TITLE
Editors field

### ISSUE THREAD

**Issue by lmcnulty** [responsible-ai-collaborative/aiid#620]
- [x] [[#608](https://github.com/responsible-ai-collaborative/aiid/issues/608)]: Suggest a new field for one of the database collections and indicate you will be working on it as part of your climb up the issue ladder. 

  I'm going to follow the suggestion of adding an `editors` field to the schema of the `incidents` collection
  
- [x]  Update the field definition of the [MongoDB doc](https://github.com/responsible-ai-collaborative/aiid/blob/master/mongo.md) to include your new field  

  ~~I'm not sure that I understand the way that the documentation in `mongo.md` is meant to correspond to the `schema.json` files. It seems like the section [Incidents Collection Details](https://github.com/responsible-ai-collaborative/aiid/blob/staging/mongo.md#incidents-collection-details) lists fields like `authors` that don't seem to be in [`incidents/schema.json`](https://github.com/responsible-ai-collaborative/aiid/blob/staging/site/realm/data_sources/mongodb-atlas/aiidprod/incidents/schema.json). I see that `authors`, however, is in [`reports/schema.json`](https://github.com/responsible-ai-collaborative/aiid/blob/staging/site/realm/data_sources/mongodb-atlas/aiidprod/incidents/schema.json).~~

  I've added this [on my fork](https://github.com/lmcnulty/aiid/commit/ce4810818945a9bc3c813d234baae0292d0bd267). I'll make a pull request once I've checked off everything here.

- [x]  Update the [schema](https://github.com/responsible-ai-collaborative/aiid/tree/master/site/realm/data_sources/mongodb-atlas/aiidprod) for the appropriate collection so MongoDB Realm understands the new entry. https://github.com/lmcnulty/aiid/commit/d8851638d6d7a920653b69de5de5d8f4af60b472#diff-976ecf02622395a1cb80b01026cf49ba9a64c5a3162177ec53172b11bdebbeb3R30
- [x] Update the [GraphQL associated with the collection](https://github.com/responsible-ai-collaborative/aiid/tree/master/site/gatsby-site/src/graphql) containing the new field. https://github.com/lmcnulty/aiid/commit/d8851638d6d7a920653b69de5de5d8f4af60b472#diff-ec3f3a231e378087537b009320cdf6e8b92a544cbc271c212e963302d4e17babR9
- [X] Write a migration to assign Sean McGregor as editor on all current incidents https://github.com/lmcnulty/aiid/commit/fc9a29998c13fc2001d01a43f642baf0e3388683
- [X] Update the user interface so the field is appropriately exposed in the forms of the website
  - [X]  Display editors in Incident Stats https://github.com/lmcnulty/aiid/commit/1da10312c2fe01e9fb0d464e7e7766805e2496ad
  - [X] Display editors in citations https://github.com/lmcnulty/aiid/commit/41ec290279431eb24d2b4e6a98e6e461e3ccc497
  - [X] Add form fields for editors https://github.com/lmcnulty/aiid/commit/98195994bdf6e7492014764e8523db0f434017af
- [X] Write tests covering the new field https://github.com/lmcnulty/aiid/commit/5cf4bd1daf0289aa6f6696540f897c38f4751da7

**Comment by smcgregor** [comment]
I have been needling @cesarvarela on updating this file, but I think it recently got out of date. It is important since it tells people what the definition of the fields are, and makes them accessible to people that don't necessarily know how to interpret the schema files. Further, some people work with the CSV dumps, which don't necessarily correspond to the schema.

The schema file is more authoritative than the markdown documentation, but in your change set you are starting with the documentation and César will be coming around to update this shortly.

I edited the issue to change the quotes to check boxes.

**Comment by smcgregor** [comment]
Your schema change looks good! I think you also need "Write a migration to assign Sean McGregor as editor on all current incidents."

**Comment by smcgregor** [comment]
Closing this. We are likely to open it again at some point in the future to tie the editor to user account actions, but that is not currently a priority.
