### ISSUE TITLE
Remove Gitbook's leftovers

### ISSUE THREAD

**Issue by cesarvarela** [responsible-ai-collaborative/aiid#622]
Not sure if this is necessary. Maybe a leftover from the gitbook stuff (there are some other leftovers around too)

https://github.com/responsible-ai-collaborative/aiid/blob/master/site/gatsby-site/src/custom-sw-code.js

**Comment by smcgregor** [comment]
It came with the GitBook starter. If nothing breaks, we can remove it.

**Comment by cesarvarela** [comment]
I've focused on that file but there are some other gitbook leftovers, I'll update the issue's title:

https://github.com/responsible-ai-collaborative/aiid/blob/master/site/gatsby-site/src/components/search/index.js

https://github.com/responsible-ai-collaborative/aiid/blob/master/site/gatsby-site/src/components/ui/Header.js

Seems like there was some kind of global search going on.
