### ISSUE TITLE
Hitting Enter in non-"Text" fields triggers report submission

### ISSUE THREAD

**Issue by LKchemposer** [responsible-ai-collaborative/aiid#624]
During report submission, if I accidentally hit Enter in any of the field except for the Text field, and if all the fields are filled in without raising an error, the report is submitted. In other words, hitting Enter in the Text field is registered as inserting a new line, whereas in other fields, it is registered as submitting the report.

This is an issue because submitters might not be done with the info editing process (e.g., still working on the text)

Potential solution: adding a (review &) confirmation step (e.g., as a pop-up) before submitting the report

**Comment by smcgregor** [comment]
I think we should just make the form submit exclusively when the submit button is pressed. Does that sound good?

**Comment by LKchemposer** [comment]
That sounds great!

**Comment by smcgregor** [comment]
Should be solved by #639 currently in staging.
