### ISSUE TITLE
Updates to Ingestion Criteria

### ISSUE THREAD

**Issue by LKchemposer** [responsible-ai-collaborative/aiid#625]
There are cases that do not fit conventionally the mental model of the criteria: "<party a> produced an intelligent system that was deployed by <party b> and its deployment is associated with harms of <party c>"

Cases are discussed below with justifications

### Incident 190

- Sample report: [ByteDance Made Fake Accounts With Content Scraped From Instagram and Snapchat, Former Employees Say](https://www.buzzfeednews.com/article/emilybakerwhite/bytedance-scraped-fake-accounts-instagram-snapchat)
- Justification: an AI does not have to necessarily cause harm only at deployment stage, the development, research, testing stages of AI systems can also cause harm. The incident fits all current criteria: (1) AI system: the TikTok For You recommendation system; (2) caused: it is a “but-for” cause; but for the existence of the algo being developed by TikTok, harms wouldn’t have occurred. the algo (being how it is currently) directly benefits from the harm inflicted, the harm is deliberate or accidental, depending on the perspective; (3) harm: privacy invasion of users, data processing without consent, psychological harms to users.

**Comment by smcgregor** [comment]
This is done. We still need to publish the update, but it is on the way to public view.
