### ISSUE TITLE
Multi-lingual support for submissions

### ISSUE THREAD

**Issue by LKchemposer** [responsible-ai-collaborative/aiid#626]
Please add multi-lingual support for submissions (e.g., incident 186, report [Las víctimas denuncian fallos en VioGén, el algoritmo contra la violencia de género](https://www.eldiario.es/tecnologia/victimas-denuncian-fallos-viogen-algoritmo-violencia-genero_1_8815201.html) in the report queue).

**Comment by smcgregor** [comment]
Let's add the language field to the incident edit form, but not the submit form. Users should not see the language field since we can handle it on our end.

**Comment by smcgregor** [comment]
@cesarvarela I added this to your backlog because I think we are likely to deliver multi-lingual support next.
