### ISSUE TITLE
Submitter-editor communication field

### ISSUE THREAD

**Issue by LKchemposer** [responsible-ai-collaborative/aiid#628]
User story: "I want to communicate to the editor about an issue, about explain my decision for some report submission info, or provide extra info about the incident"

Potential solution: add an optional text field "Note to Editor" where submitters can communicate to editors; this field doesn't get ingested into the database.

**Comment by smcgregor** [comment]
I like this more from the perspective of process management (e.g., you can write notes to me and vice versa) than I do for the general public. Specifically, I don't like out of band/out of sight information influencing the incident report status when that should be part of one or more reports.

Perhaps we should create an "editor notes" field as a text blob and when users submit they have the option of initializing the field with their perspective. In the editing process we can then either include the notes, or remove them at ingestion time. Thoughts?

**Comment by LKchemposer** [comment]
Yep, sounds good

**Comment by lmcnulty** [comment]
Here's how I expect I'll handle this:
- [ ] Add `"editor_notes": { "bsonType": "string" }` to the schema for both aiidprod.submissions and aiidprod.reports. 
- [ ] Write a migration adding the field as an empty string for all existing submissions and reports.
- [ ] Add text entry fields for editor_notes in `SubmissionForm.js` and `IncidentReportForm.js`
- [ ] Add the extra fields to `handleSubmit` in `SubmitForm.js` and `pages/cite/edit.js`
- [ ] Update the queries in `gatsby-site/src/graphql/reports.js` and `submissions.js`
- [ ] In `promoteSubmissionToReport.js`, copy the editor_notes to the new incident if the editor chooses to keep them.
- [ ] Add a card to display the notes in `cite.js` and `SubmissionReview.js`
- [ ] Perhaps when there are notes in a submission and the editor has not modified them, when they press the button promote the submission, they should get a prompt saying that there are unmodified notes with [Delete] and [Continue] options.

**Comment by smcgregor** [comment]
Good checklist, a few comments,

`Add text entry fields for editor_notes in SubmissionForm.js and IncidentReportForm.js`: Only display the form element if the user is logged in.

`Add a card to display the notes in cite.js and SubmissionReview.js`: only if the field is non-empty

No need for: `Perhaps when there are notes in a submission and the editor has not modified them, when they press the button promote the submission, they should get a prompt saying that there are unmodified notes with [Delete] and [Continue] options.`

**Comment by lmcnulty** [comment]
This is resolved by #677.
