### ISSUE TITLE
A11y skip-to-content link

### ISSUE THREAD

**Issue by lmcnulty** [responsible-ai-collaborative/aiid#645]
It's an accessibility [best practice](https://www.w3.org/WAI/WCAG21/Techniques/general/G1) for the first focusable element on a page to be a hidden link that skips past the site navigation and to the main page content. This is important for users of screen-readers that announce elements in the order they appear in the DOM. It's also helpful for keyboard navigation. E.g.

https://user-images.githubusercontent.com/25443411/170301144-34b4fde7-8743-4329-bfc8-279d9d0cb80e.mp4

**Comment by smcgregor** [comment]
Interesting, sounds good to me!
