### ISSUE TITLE
Run tests on Github

### ISSUE THREAD

**Issue by cesarvarela** [responsible-ai-collaborative/aiid#667]
- [x] deploy previews
- [x] #2540
- [x] #2541
- [x] #2542
- [x] #2543
- [x] #2214
- [x] #2587
- [x] #2600

**Comment by smcgregor** [comment]
This is the first issue in a collection of DevOps related issues that we need to advance, including,

* The test system currently blocks deployment to staging and to production, but it should really only block deployment to production.
* We should have a testing database that is initialized with the current state of production at test time, along with a more static test database to ensure tests are replicatable.
* The [NLP-Lambdas repository](https://github.com/responsible-ai-collaborative/nlp-lambdas) needs a strategy for updating its state.csv file, which is integrated with the components @lmcnulty is working on. That repo has a few hot points that need addressing.

@pdcp1 I am assigning you to this issue (just the first part of moving to GitHub for test parallelization), but please don't work on it until next week and continue working the issue queue now. After this initial issue is addressed, we will talk about those other DevOps/backend issues

**Comment by smcgregor** [comment]
We are running on CircleCI now.

**Comment by cesarvarela** [comment]
We are back at it, this time, we'll run on a large GitHub runner.

**Comment by kepae** [comment]
#2508 advances this issue. Next up is experimenting with code coverage in:
* #2214.
