### ISSUE TITLE
All submissions are displayed with incident_id: 0

### ISSUE THREAD

**Issue by lmcnulty** [responsible-ai-collaborative/aiid#676]
On the current production site, every submission in the queue is listed as having incident_id: 0. While I was my development realm app, I saw that `incident_id` was removed from submissions schema. I'm guessing that means the row in the table just needs to be removed.

<img width="500" src="https://user-images.githubusercontent.com/25443411/171916254-913d17a2-381c-48ed-ae46-f356e68f6d05.png">

<img width="500" src="https://user-images.githubusercontent.com/25443411/171916374-596c6062-3e07-48f2-aff8-16931a024e2f.png">

<img width="500" src="https://user-images.githubusercontent.com/25443411/171916564-1efc1ec2-858e-49b5-bad5-bc22469e5e46.png">

**Comment by smcgregor** [comment]
`0` means it will be a new incident. Non-zero numbers mean the report will be associated with a current incident.

**Comment by lmcnulty** [comment]
Oh, ok. Perhaps in the table it could be displayed as "None" instead?

**Comment by smcgregor** [comment]
Maybe `New Incident`

**Comment by cesarvarela** [comment]
>  incident_id was removed from submissions schema

You are confusing `submissions` with `reports`, it was confusing to me at first too.

**Comment by clari182** [comment]
Closing this out since it was fixed here: https://github.com/responsible-ai-collaborative/aiid/commit/dacc29681654a0d2e7d938e317c33b4342160774#diff-81700d227180dd421efab3503d75b9550d8c97ab9ce18c660661e7a9bb2cd451R28
Thanks @lmcnulty for the help!
