### ISSUE TITLE
Missing `source_domain`s

### ISSUE THREAD

**Issue by lmcnulty** [responsible-ai-collaborative/aiid#684]
In the production submission queue, the source_domain field is displayed as empty for submissions made on or after May 18.

<img src="https://user-images.githubusercontent.com/25443411/172249002-0816b5bd-5939-44c5-8985-580a74f2803a.png" height="120"/>

**Comment by cesarvarela** [comment]
Yup, should be fixed once this one is merged: https://github.com/responsible-ai-collaborative/aiid/pull/673

**Comment by lmcnulty** [comment]
Great!
