### ISSUE TITLE
Set incident titles as required in JSON schema

### ISSUE THREAD

**Issue by cesarvarela** [responsible-ai-collaborative/aiid#692]
Once incident titles are updated, let's not forget to set as required in the schema.

related PR #685

**Comment by smcgregor** [comment]
Using this issue to track the assignment of values to the table here:

https://incidentdatabase.ai/apps/incidents

I went through and assigned the first 10 and will continue sweeping through the list. @LKchemposer please update here if/when you do the same and we will ensure efforts are not duplicated.

After the table is filled, we will make these values required at ingestion time.

**Comment by smcgregor** [comment]
I did 3 more, done through 13.

**Comment by smcgregor** [comment]
Sounds good. Titles, and the alleged developers, deployers, and harmed parties.

**Comment by LKchemposer** [comment]
Completed to incident 103! No more large gap between incidents.

That being said, here are the left-overs (to be done by me):

- [ ] 193
- [ ] 173
- [ ] 168
- [ ] 161
- [ ] 148
- [ ] 138
- [ ] 136
- [ ] 128
- [ ] 125
- [ ] 102 → ~50

**Comment by lmcnulty** [comment]
Resolved by #990.
