### ISSUE TITLE
Improve OpenGraph meta tags

### ISSUE THREAD

**Issue by cesarvarela** [responsible-ai-collaborative/aiid#697]
Open graph meta tags need an update/standardization. Sharing incidentdatabase.ai links could do better: 

Facebook:

<img width="1038" alt="image" src="https://user-images.githubusercontent.com/1172479/172948609-6e59a99d-243d-416e-ac34-65bbe632512e.png">

Linked in:

<img width="570" alt="image" src="https://user-images.githubusercontent.com/1172479/172948232-098f1a50-0493-4332-9c3a-fc21dc135229.png">

Shares could show the incident title, a description, a picture, etc.

**Comment by pdcp1** [comment]
@smcgregor Should we improve the Title and Description metatag texts or should we leave it as it is?
They are not descriptive of the actual incident.
ie: Title "Incident 217" and description "Citation record for Incident 217"

**Comment by smcgregor** [comment]
I think these non descriptive examples may be from staging rather than
production. Regardless, the incident titles are set to roll out shortly and
are the subject of improvement/editing and you can but around them.
