### ISSUE TITLE
Report images not rendered in citation page, but rendered in preview

### ISSUE THREAD

**Issue by LKchemposer** [responsible-ai-collaborative/aiid#707]
For example, this image for [report 1761](https://incidentdatabase.ai/cite/edit?report_number=1761) was rendered in the preview page and in the edit window:

<img width="1000" alt="image" src="https://user-images.githubusercontent.com/39468345/173755973-64f9ee55-048c-47cd-acf8-d9859ff6229c.png">

but was not rendered in the citation page:

<img width="1000" alt="image" src="https://user-images.githubusercontent.com/39468345/173756256-3186e9ea-6000-40d3-9097-18626d382044.png">

A few other reports in the [incident page](https://incidentdatabase.ai/cite/208?lang=en) also run into the same issue.

**Comment by smcgregor** [comment]
Is this happening selectively, or in all cases for you?

**Comment by LKchemposer** [comment]
Interestingly, with the new deployment, the issue is gone
