### ISSUE TITLE
Preview images not rendered in Edit Submission window

### ISSUE THREAD

**Issue by LKchemposer** [responsible-ai-collaborative/aiid#729]
Images were not rendered in the Edit Submission window, despite image address exists (verified via opening a new tab).

<img width="785" alt="image" src="https://user-images.githubusercontent.com/39468345/175618024-8a67ec65-4ada-4f10-8da8-4a75967a1295.png">

**Comment by lmcnulty** [comment]
Entering `https://wp-assets.futurism.com/2022/06/dall-e-mini-racist.jpg` seems to work currently. However, there may be other addresses that will not work.

**Comment by smcgregor** [comment]
I am going to close this since I _think_ it has been addressed, please reopen if experienced again.
