### ISSUE TITLE
Classifications Database view of CSET Taxonomy does not flatten and dedeup array values for filtering/faceting

### ISSUE THREAD

**Issue by kepae** [responsible-ai-collaborative/aiid#739]
When using the Classifications Database view of the CSET taxonomy, faceted search for columns where values are arrays is broken. Specifically, arrays are not flattened and deduped to form sets of the individual values. This affects multiple taxonomy field facets.

For example, the "Named Entities" field contains an incident with the following entities:
"New York Department of Education, United Federation of Teachers,Sheri Lederman,Common Core,Governor Andrew Cuomo"

**Expected behavior:** when filtering on Named Entities, there are 5 distinct entities to select in the dropdown:
- `New York Department of Education`
- `United Federation of Teachers`
- `Sheri Lederman`
- `Common Core`
- `Governor Andrew Cuomo`

**Actual behavior:** there is one entity with all the values concatenated:
- `New York Department of Education, United Federation of Teachers,Sheri Lederman,Common Core,Governor Andrew Cuomo`

![image](https://user-images.githubusercontent.com/4238598/176080730-4fd24739-9452-4b12-a68a-e3c52de6331a.png)

I haven't queried the schema myself to confirm that it's the mongo type, but I saw https://github.com/responsible-ai-collaborative/aiid/pull/155 with schema migrations containing:
```
<...>
    {
      "short_name": "Named entities",
      "long_name": "Named entities",
      "short_description": "These are the organizations and people related to the incident.",
      "long_description": "Organizations and people can both be related to the incident and are typically mentioned in incident reports.",
      "display_type": "list",
      "mongo_type": "array",
      <...>
    },
<...>
```

**Comment by smcgregor** [comment]
Thanks @kepae confirmed on the expected and current behavior. I tagged it to the current backlog and I believe this arises to the level of being a bug.
