### ISSUE TITLE
Incidents whose reports better fit as context

### ISSUE THREAD

**Issue by LKchemposer** [responsible-ai-collaborative/aiid#746]
There are some incidents whose reports (sometimes, there is only one) better fit as context to other incidents as opposed to an incident of a deployed system causing real-world harm. Their report class are to be changed to [TBD], when it is available.

- [168](https://incidentdatabase.ai/cite/168?lang=en) - discusses inherent flaw of the technology (e.g., [Popularity Bias in Collaborative Filtering-Based Multimedia Recommender Systems](https://incidentdatabase.ai/cite/168?lang=en#r622b87967c8c02e4c619d04a))
- [161](https://incidentdatabase.ai/cite/161?lang=en) - its single report fits more as context to [93](https://incidentdatabase.ai/cite/93?lang=en) 
- [173](https://incidentdatabase.ai/cite/173?lang=en) - individual systems need to be identified to satisfy criteria of incidents, per https://github.com/responsible-ai-collaborative/aiid/issues/745
- [143](https://incidentdatabase.ai/cite/143) - discusses a general problem of content moderation on social media platforms, but also reports the specific incident
- [136](https://incidentdatabase.ai/cite/136) - discusses a general problem of brand safety tech
- [129](https://incidentdatabase.ai/cite/129) - discusses broadly Facebook's failing to adequately moderate content without specific instance, can be treated as context to [215](https://incidentdatabase.ai/cite/215)
- [125](https://incidentdatabase.ai/cite/125)

To-do:

- [ ] Change report class to [TBD]

**Comment by smcgregor** [comment]
Adding to the list:

Incident 29 concerns the "tank story," which may be apocryphal.
https://incidentdatabase.ai/cite/29

Incident 21 seems to be primarily about performance issues in a competition and is not necessarily an incident.
https://incidentdatabase.ai/cite/21

Does not meet current definition and criteria
https://incidentdatabase.ai/cite/42

Was designed to be humorous and is in fact humorous
https://incidentdatabase.ai/cite/62

**Comment by smcgregor** [comment]
@LKchemposer can you consolidate the lists here and move them to #449 ?
