### ISSUE TITLE
Discover page - sorts and filters

### ISSUE THREAD

**Issue by LKchemposer** [responsible-ai-collaborative/aiid#747]
- User story: "I want the incidents or reports to be sorted by incident date, submitted date, and/or published date of report, ascending or descending, within a time range, because I'd like to see how the incidents or reports progress over time."

Current report display on the Discover page are not sorted by time

<img width="1145" alt="image" src="https://user-images.githubusercontent.com/39468345/176384156-a49bb6bb-fb7e-4d3b-85b8-209060f063a1.png">

**Comment by smcgregor** [comment]
I think this one should be for supporting sort orders, in general.
