### ISSUE TITLE
Incident redundancy

### ISSUE THREAD

**Issue by LKchemposer** [responsible-ai-collaborative/aiid#768]
[Incident 130](https://incidentdatabase.ai/cite/130)'s sole report (about Alibaba Cloud developing FRT to profile Muslim Uyghur minorities) is an example of [incident 107](https://incidentdatabase.ai/cite/107), which is about Chinese tech firms developing FRT to identify people by race, targeting Uyghur Muslims.

To-do:

- [ ] Set report 1464's `incident_id` as `107`

**Comment by smcgregor** [comment]
We just discussed this verbally. Neither of us like merging incidents, but in the case of the reporting surrounding 130 and 107, multiple firms are listed in all the reports and the firms listed in headlines are shared between both reports as well. Given the nature of these particular incidents, we have decided to complete the merge.

@LKchemposer please add the report from 130 to 107 via the interface, then I will add the entry to the duplicates table so the UI will direct people properly.

**Comment by smcgregor** [comment]
@LKchemposer have you added the report from 130 to 107?

**Comment by LKchemposer** [comment]
done

**Comment by smcgregor** [comment]
Duplicate record added.
