### ISSUE TITLE
All blog posts have content of join-raic

### ISSUE THREAD

**Issue by lmcnulty** [responsible-ai-collaborative/aiid#775]
In the current staging, all the blog posts have the content of the join-raic post:

https://staging-aiid.netlify.app/blog/representation-and-imagination
https://staging-aiid.netlify.app/blog/the-first-taxonomy-of-ai-incidents

**Comment by smcgregor** [comment]
Confirmed. Weird. Added @cesarvarela since this is likely related to the translations.

**Comment by smcgregor** [comment]
@cesarvarela status on this?
