### ISSUE TITLE
Rep. 1605 - flagged

### ISSUE THREAD

**Issue by LKchemposer** [responsible-ai-collaborative/aiid#781]
Report 1605 - [Microsoft made an AI algorithm to predict pregnancies of specific preteen girls](https://incidentdatabase.ai/cite/184#r6286836de0eed158517c5def) - should be a report of [incident 188](https://incidentdatabase.ai/cite/188) which discusses Argentinian teenage-pregnancy algorithm, and not of [incident 184](https://incidentdatabase.ai/cite/184) which discusses Sao Paolo's use of FRT

To-do:

- [x] Change report 1605's `incident_id` to `188`

**Comment by smcgregor** [comment]
@LKchemposer I think we took care of this previously? I am not seeing that report.

**Comment by LKchemposer** [comment]
yes I believe so, since that report is now in incident 188
