### ISSUE TITLE
Latest Incident Report image broken on mobile

### ISSUE THREAD

**Issue by clari182** [responsible-ai-collaborative/aiid#785]
### Issue:
When loading the Home page on mobile, the "Latest Incident Report" image breaks on iPhone sizes

### Evidence
![image](https://user-images.githubusercontent.com/4105289/178362755-4a790cff-452d-49d5-92ec-ce9bc4917e8c.png)

### Steps to reproduce  
1. Open https://incidentdatabase.ai/ in chrome with iPhone dimensions
2. First image appears broken in section "latest Incident Report"

**Comment by smcgregor** [comment]
I am not seeing that when I shrink chrome on desktop or open on Firefox with my Android phone. Can you refresh one more time to see if it persists?
