### ISSUE TITLE
Add incident title, description, developer, deployer, and harmed parties to submission form

### ISSUE THREAD

**Issue by smcgregor** [responsible-ai-collaborative/aiid#798]
All current incidents in production will soon have the information found [here](https://incidentdatabase.ai/apps/incidents/). This is something that took @LKchemposer and myself quite a bit of time to manually input. Now we need to ensure that all future incidents have this information.

- [ ] When [creating new incidents](https://incidentdatabase.ai/apps/submit), the user should have the **option** of submitting the incident detail information.
- [ ] When [promoting a submission](https://incidentdatabase.ai/apps/submitted) to an incident, the editor adding the incident should be required to specify the additional fields.
- [ ] Finally, we need to update staging with the data from production (since we are now making the data required and the data does not exist on staging)

**Comment by clari182** [comment]
Closing issue as it has been merged in #805
