### ISSUE TITLE
Multi lingual support for dates

### ISSUE THREAD

**Issue by cesarvarela** [responsible-ai-collaborative/aiid#803]
Dates should be localized across the site.

 Format should be pulled from https://github.com/responsible-ai-collaborative/aiid/blob/master/site/gatsby-site/i18n/config.json

**Comment by smcgregor** [comment]
I think the fastest thing here is to adopt `yyyy-mm-dd` universally since it won't require per-language setting, is generally interpretable by most cultures, and the sort order matches chronological order.
