### ISSUE TITLE
Broken Production Build

### ISSUE THREAD

**Issue by smcgregor** [responsible-ai-collaborative/aiid#808]
Production build is reliably broken:

```
11:03:51 AM: The function zip ../../../../../tmp/zisi-62d059d73d5bf8000888c36b/__dsg.zip size is 53.9 MB, which is larger than the maximum supported size of 52.4 MB.
11:03:51 AM: There are a few reasons this could happen, such as accidentally bundling a large dependency or adding lots of files to "included_files".
```

https://app.netlify.com/teams/netlify-alp70lu/builds/62d059d73d5bf8000888c36b

**Comment by cesarvarela** [comment]
It looks like the same issue as here:

https://answers.netlify.com/t/unwanted-zip-files-causing-build-failures/52745/7

And from the build logs the `data.mdb` is huge: 

![image](https://user-images.githubusercontent.com/1172479/179127178-7bf4e98f-c892-46dd-9d29-9ab3426a299d.png)

So adding something like this to `netlify.toml` **may** work:

```
[functions]
  included_files = ["!site/gatsby-site/.cache/data/datastore/data.mdb"]
```

I can take a shot at this tomorrow.  I have no idea why they bundle the `.cache` folder like that; I'm not positive it is necessary.

**Comment by smcgregor** [comment]
Sounds good. We can ride the old version for a day since this won't take it down. CC @LKchemposer

**Comment by cesarvarela** [comment]
@smcgregor after some google looks like Netlify already proposes a solution which is described here: https://docs.netlify.com/integrations/frameworks/gatsby/#optional-loading-of-the-gatsby-datastore-from-the-cdn

But before trying that, I've run the same build (same branch and DB) on a different Netlify box and didn't get that error, so maybe you can try to run the deploy again but clear Netlify's cache first?


A similar issue is being tracked here: https://github.com/netlify/netlify-plugin-gatsby/issues/323

**Comment by smcgregor** [comment]
Cleared cache and pending deploy now.

**Comment by cesarvarela** [comment]
It went through 🥳

**Comment by smcgregor** [comment]
Excellent, please close if appropriate!
