### ISSUE TITLE
Memory leak in the Quick Search component

### ISSUE THREAD

**Issue by cesarvarela** [responsible-ai-collaborative/aiid#813]
https://github.com/responsible-ai-collaborative/aiid/blob/98e64c0d7892af429de8af93eb35b0d653d55781/site/gatsby-site/src/components/landing/QuickSearch.js#L23-L38

A few things happening here:

- `useEffect` without dependency array runs on every render
- `resize` handler keeps being added over and over
- because there is no cleanup function in the hook, the event handler keeps referencing the component even after the user navigates away from the page

This is not site-breaking or anything; just pointing this out for educational purposes only 🎓

**Comment by lmcnulty** [comment]
Thanks! I had yet to learn some of the details of the `useEffect` hook when I wrote this.
