### ISSUE TITLE
Translated texts breaks some HTML elements

### ISSUE THREAD

**Issue by pdcp1** [responsible-ai-collaborative/aiid#836]
This issue was found as part of the CR of PR #833 

It was found on the `/about` page but it probably happen in another page.

### Steps to reproduce
1- Go to preview link: https://deploy-preview-833--staging-aiid.netlify.app/es/about
2- In the first section text and check the link for [FARS](https://www.nhtsa.gov/research-data/fatality-analysis-reporting-system-fars))

### Screenshot
<img width="995" alt="image" src="https://user-images.githubusercontent.com/6564809/180322238-471d1ddc-ead8-4ecd-9370-5f9ff0f063d5.png">

**Comment by smcgregor** [comment]
See also: https://incidentdatabase.ai/fr/research/1-criteria/

**Comment by cesarvarela** [comment]
Fixed some formatting errors. Might be some other left, but this is not an issue per se.
