### ISSUE TITLE
Install Cypress Slack integration

### ISSUE THREAD

**Issue by pdcp1** [responsible-ai-collaborative/aiid#840]
Slack Integration allows you to see your Cypress test results directly in your teams' Slack channels.

If we agree that this Slack app is too much information about Cypress test notifications we can remove it. We are going to have that information on Github and emails anyways.

It should only notify if `staging` or `production` tests fail

[👉 How to install documentation](https://docs.cypress.io/guides/dashboard/slack-integration#Install-the-Cypress-Slack-app)

![image](https://user-images.githubusercontent.com/6564809/180456700-9e90738c-9f5e-4bed-b832-e4d85b2587ac.png)

**Comment by pdcp1** [comment]
Done!

**Comment by smcgregor** [comment]
I don't think anyone is clamoring for this at the moment. If you would like this, please reopen.
