### ISSUE TITLE
Report mistakenly added without incident id

### ISSUE THREAD

**Issue by LKchemposer** [responsible-ai-collaborative/aiid#866]
I added report [Due to license plate reader error, cop approaches innocent man, weapon in hand](https://incidentdatabase.ai/cite/246#r62df7881a6f43c979e2455c8), but forgot to assign an incident id for it, so the report was assigned as a new inc. 247.

- [x] Re-submit/duplicate report and assigned to inc. 246
- [x] Remove inc. 247

**Comment by smcgregor** [comment]
Done!
