### ISSUE TITLE
"Fetch info" only fetches half of the report

### ISSUE THREAD

**Issue by LKchemposer** [responsible-ai-collaborative/aiid#867]
Report url: https://www.wired.com/story/cruises-robot-car-outages/

The text fetched via "Fetch info" button only contains texts, and embedded links, up to a few paragraphs (`... billions it has poured into building its technology.`). The rest had to be copied and pasted in manually.

Ironically, this is the classic case of automation bias, because the submitter of this report (and I, at first) assumed that the tool did its job without needing to be verified.

**Comment by smcgregor** [comment]
I think this typically happens because the website being fetched has pagination or a fold. I don't think we are going to fix this anytime soon, so I am going to close it for now. In the future we may look to pay for a news API that specializes in doing this step for us.
