### ISSUE TITLE
Suggestion - bring back quick incident title view when incident id is inputted

### ISSUE THREAD

**Issue by LKchemposer** [responsible-ai-collaborative/aiid#868]
Could I have the feature where, once an incident id is assigned the title of the incident is shown right below, back?

It was a great quick sanity check to confirm whether the to-be-added report belongs to the incident from just its incident title. As of now, the report titles are shown in the "Incidents reports matched by ID: X" section, but that requires scrolling down a bit.

**Comment by lmcnulty** [comment]
How about we move each of the "Incident reports matched by..." right under the corresponding input? That seems like it would solve this issue and generally make the feature more useful.

**Comment by lmcnulty** [comment]
I've opened [a pull request](https://github.com/responsible-ai-collaborative/aiid/pull/894) for this that makes the list of related reports show up right under the incident ID input.

![image](https://user-images.githubusercontent.com/25443411/182690859-50dace84-8892-4df5-9f68-bb27220b2c84.png)

**Comment by LKchemposer** [comment]
Would it be possible to also show the `title` of the incident (and at max, 5 reports of that incident)? This feature is mainly used as a sanity check to confirm that the to-be-ingested report fits the incident id, so it doesn't need to take up a lot of space.

**Comment by lmcnulty** [comment]
This is solved my #894 now in staging, so I'm closing this for now.
