### ISSUE TITLE
Create project architecture diagram

### ISSUE THREAD

**Issue by pdcp1** [responsible-ai-collaborative/aiid#870]
### Diagram link:

https://drive.google.com/file/d/1kHT1EFrBjxGZOWewS0uUrOZ2QflqYUnA/view?usp=sharing

### Current diagram:

![AIID project arquitecture](https://user-images.githubusercontent.com/6564809/181662915-1a7eb2f4-eaef-4919-937d-db208548fa2a.jpeg)

**Comment by pdcp1** [comment]
@smcgregor Do you think that is a good idea to include this diagram as part of the README file?

**Comment by smcgregor** [comment]
Yes please. One comment: I don't believe we are pushing any content to Cloudinary during build time. Images are indexed in Cloudinary at the time they are submitted by users.

**Comment by pdcp1** [comment]
I have to change the diagram to be more clear about the difference between build time and the runtime. That Cloudinary icon is just to represent that the Netlify site uses Cloudinary to retrieve the report images on runtime. Good catch!
