### ISSUE TITLE
Deleting Reports from the UI Breaks the Build

### ISSUE THREAD

**Issue by smcgregor** [responsible-ai-collaborative/aiid#876]
I deleted a report on an incident via the UI and it broke the build. I believe it is a problem in the foreign key outside the reports collection not having anything to point to.

1. [x] Remove the foreign key
2. [ ] Update the `delete` action to do this automatically

The offending production build: https://app.netlify.com/sites/aiid/deploys/62e2277926f49700087fa2fb

**Comment by smcgregor** [comment]
I manually removed report 1116 from incident 60 on the incidents collection using the MongoDB interface. This should fix the build, but the GraphQL endpoint for deleting reports still needs an update for this.

**Comment by cesarvarela** [comment]
Interesting, I expected that because we are using the build-in delete a and the built-in relationships, it would "cascade," but it does not.

The fix should be to manually call the `unlinkReportFromIncident` mutation after deleting.

**Comment by lmcnulty** [comment]
I was coming up with a solution (#878) that just uses `updateIncident` rather than `unlinkReportFromIncident`, but maybe the latter would be cleaner.

**Comment by cesarvarela** [comment]
Oh, I just looked, and it is not implemented yet, so we'll have to stick to your solution.
