### ISSUE TITLE
Listing of all Incidents Bad References

### ISSUE THREAD

**Issue by smcgregor** [responsible-ai-collaborative/aiid#887]
It looks like the https://incidentdatabase.ai/summaries/incidents is presenting the references on the incidents collection, and that this is producing a bunch of missing reports. See the screen capture below. Incident 161 doesn't even have a single report properly linked.

<img width="1116" alt="Screen Shot 2022-08-02 at 8 42 12 AM" src="https://user-images.githubusercontent.com/64780/182416012-4e181874-fb48-48c1-a5e6-f74c634c1aa5.png">

* `Missing Report 23`
* `Missing Report 208`
* `Missing Report 233`
* `Missing Report 1522`
* `Missing Report 1530`
* `Missing Report 1605`

**Comment by lmcnulty** [comment]
This is now fixed [on staging](https://staging-aiid.netlify.app/summaries/incidents/).
