### ISSUE TITLE
Broken internal links

### ISSUE THREAD

**Issue by cesarvarela** [responsible-ai-collaborative/aiid#890]
Some internal links are pointing to non-existing pages, we should use one of those tools that crawl the site a find them.

Google's search console has this feature, too  I think 🤔

**Comment by smcgregor** [comment]
I just activated Google Search Console for incidentdatabase.ai. It takes a day to become active. I'll check back.

https://search.google.com/search-console?resource_id=sc-domain%3Aincidentdatabase.ai

**Comment by smcgregor** [comment]
I think this is good now.
