### ISSUE TITLE
Change Relevant UI from Reports to Incident Titles

### ISSUE THREAD

**Issue by smcgregor** [responsible-ai-collaborative/aiid#896]
Elements like those below are currently scoped to incident reports rather than incidents. Now that we have guaranteed incident titles and descriptions, we should change everything that is only showing incident report details for the purpose of presenting an incident to now use the incident titles, and potentially descriptions.

<img width="692" alt="Screen Shot 2022-08-04 at 8 49 19 AM" src="https://user-images.githubusercontent.com/64780/182890861-bf689519-d93f-490b-8d86-8999b2374e4d.png">

**Comment by lmcnulty** [comment]
I believe this is resolved now by #896 and #894.
