### ISSUE TITLE
Think-aloud user testing

### ISSUE THREAD

**Issue by lmcnulty** [responsible-ai-collaborative/aiid#902]
These are notes from a think-aloud user testing session I did with a friend using the live site on August 5, 2022. Some of the feedback will turn into more directly actionable issues – this issue collects a large number of points together and should likely remain open until the site has changed enough that this think-aloud no longer accurately reflects the user experience of the site.

-   Double quotes `"…"` denote the user’s words,
-   [Guillemets](https://en.wikipedia.org/wiki/Guillemet) `« … »` are used for all other forms of quotation.
-   Brackets denote `[…]` summary or clarification of the user’s words
-   Braces `{…}` denote my interpretation that doesn’t directly summarize the user’s words.

* * *

-   Landing page
    
    -   “The Logo looks cool”
    -   \[Bothered that « Welcome to the Artificial Intelligence Incident Database » is not all in one line\]
    -   “I’m not really sure how to search”
         - {Perhaps we could add badges containing recommended searches?}
    -   Searched « cars »
-   Discover
    
    -   Went to view switch – “what does this do” – switched back and forth a bunch of times
    -   Clicked « clear filters » (with no filter activated)
    -   “Yes, Starbucks _is_ shortchanging its baristas”
    -   “How do I go home” - clicked the title right away
-   Landing page
    
    -   Scrolled down
    -   At leaderboard, _laughs_ “let’s go anonymous”
    -   “What is discover” _clicks_
-   Discover
    
    -   “For some reason this is what I would have expected from the home page”
    -   “First report only?” _checks_ “Not sure what that did”
    -   Clicked link
-   Citation page
    
    -   auto-scrolled to bottom with picture, _Laughs_
    -   “What happens if I keep scrolling up?”
    -   Saw timeline
        -   “This is cool”
        -   “It could be cool to have a graph of report frequency over time”
            -   \[For a certain AI, like Dall-E\]
-   Clicked star count in header
    
    -   Saw me in the list of stargazers
    -   “hell yeah”
-   Blog
    
    -   Laughed at “using AI to connect AI incidents”
-   Landing page
    
    -   “There’s something about this \[the landing page above fold\] that feels sad”
        
        -   “Also it should be scarier”
    -   “Maybe there should be different coloration for the title”
        
    -   \[The borders of frames are very thin and hard to understand\]
        
-   She didn’t try most things in the the sidebar, so I suggested she go through it.
    
-   About page
    
    -   “It’s kind of just uggo”
        -   {padding above and below the header is too much}
        -   “There could be color coding”
        -   “If my mouse goes over something then it should react”
        -   “All black and white, little thin lines”
        -   “If I wanted to read a newspaper, I’d read a newspaper”
    -   At “Intelligent systems are currently prone to…”
        -   “I can understand this, but 99% of people are going to glaze over this”
    -   « What is an incident »
        -   “It’s unclear to me what these bullet point are examples of, except just incident reports”
    -   “It’s funny to me that so much space on the page is dedicated to the board of directors, when nobody cares”
-   Sidebar →
    
    -   “This is cool how it responds to my mousing over, and it’s a little tree”
-   Database Apps
    
    -   “ADHD brain overwhelmed by amount of text on webpage – want to close website”
        -   “Ideally the app links would be big colorful things”
            -   “Only when you mouse over should it show the text”
            -   “Focus more on communicating information visually”
-   Word counts
    
    -   “Stop words - not sure what that is”
        
        -   “None of this would be coherent to someone who isn’t a computer scientist or linguist”
            
            -   “It’s also not particularly relevant”
                -   “When I’m coming to this website, I want to know what are the big bad AIs”
                    
                    -   “Who’s doing the evil shit”
    -   \[Word cloud should be bigger (whole page)\]
        
    -   \[Need clues on how to interpret this\]
        
    -   After hearing what she said about stop words, I gave examples and mentioned that a drawback of stop words is that you sometimes lose interesting information – I gave the example that « he » and « she » are filtered out, but you can get a rough estimate of the gender representation in a text by the comparing the count of those words. This is among the techniques used in [Nabokov’s Favorite Word is Mauve](https://openlibrary.org/books/OL33009512M/Nabokov's_Favorite_Word_Is_Mauve) to find interesting patterns in classic literature. I mentioned that I checked the count in our corpus and « he » was used about three times as often as « she ».
        
        -   “See, that would be interesting”
            -   “Show prime examples of interesting information”
-   Since I didn’t think she would find it, I showed her how to reach /taxonomy/cset
    
    -   “No one knows what a taxonomy is”
    -   Scrolled down
        -   “Wait, this is the best thing!”
    -   Tried clicked on the pie graph section for « severe »
        -   “I want to go to discover when I click on the graph”
        -   Clicked on the linik above to get there
-   Discover
    
    -   {Confused by difference between reports and incidents}
        -   \[These are the same / duplicates – even have same images\]
            -   “Yeah, I’m basically only looking at the images”
    -   “I’m not sure about the decision to put all this text under the title.”
        -   \[I’m already getting an overview – If I want to know more I’ll click it\]
-   Landing page
    
    -   “Could be cool to have a counter of incidents on the homepage that’s always increasing”
    -   “In general, this website needs more art”
        -   \[You need animation and color coding\]
        -   \[Less text more incidents\]
        -   It should be an artwork – needs graphic design
        -   “The part I get drawn to the most is the top” \[best graphic design\]
-   Researcher guide
    
    -   « Defining an AI incident »
        -   “None of this told me how you define an AI incident”
        -   “It’s unclear to me what the connection between the aviation incident definition and AI incident is”
            -   “The only clear message was « the aviation industry has clear definitions, and we don’t »”
                -   “Does their classification of an « accident » apply here”
                    -   \[Do we classify anything as an accident?\]
                        -   “As far as I can tell, nothing is classified as an accident”
    -   \[likes the quote formatting\]
-   Roadmap
    
    -   “I’m not sure what a database roadmap is — what would I be looking for that would make me want to click here?”
        -   “It’s still unclear”
            -   “I guess if it’s common parlance what a roadmap is among researchers…”
            -   “It looks like a roadmap is just a plan”
    -   Page heading - “This is so ugly! Why is this \[the `<h1>`\] smaller than this \[the `<h2>`\]”
-   “The sidebar is my favorite part”
    
    -   "I like how the text changes to white, I like how it doesn’t change in one frame
        -   there’s a little bit of gradualness"
-   Went to « classifications view »
    
    -   “AAAH! I’m so overwhelmed”
        
    -   “What does this \[edit button\] mean”
        
        -   “It’s not clear what an action is”
    -   “Why is this \[text in row\] so small”
        
    -   “There should not be so much space given to the text \[the description\]”
        
    -   “If I ever have to scroll horizontally on a website, I’m out”
        
    -   \[It’s impressive that there’s so many ways of classifying incidents\]
        
    -   “Maybe it would be better to show the categories in a menu” with “sort by…”
        
    -   “I’m not sure how to search an incident ID”
        
    -   “I’m not sure why there are only 94”
        
    -   « Near miss »
        
        -   “This is really cool, though”
    -   “The functionality of this is really cool”
        
-   I suggested she go back to «Discover» and asked if she noticed the “Filter Search” option
    
    -   “No”
        
    -   \[Sometimes it’s scary to click on less obvious parts of websites because you don’t know where they’re going to take you\]
        
        -   “My mom would never click this \[the «filter search» option\]”
    -   “I wish severity or « harm caused » were here”
        
    -   \[It would be nice if the filters popups closed as soon as you moused away\]
        
    -   I explained the difference between reports and incidents
        
        -   “That’s _so_ confusing”
        -   “I would have never figured that out”
        -   “I’m _still_ confused about how that works”
    -   Went to classifications filter
        
        -   “I’m not sure what CSET is or if it’s relevant”
            
        -   “The classifications are what I would have expected the filters to be”
            
            -   \[It would be more relevant to the average user if the top-level filters were by severity, etc.\]
            -   « Harm to physical property »
                -   “See, this is really interesting”
            -   “What if I want to select multiple classifications”
                -   “Ok, that’s intuitive”
            -   “All of the classifications should not be crammed into here”
-   “Overall, I want to see some sensational AI awfulness within the first 5 seconds”

**Comment by smcgregor** [comment]
I am applying the "backlog" label to this with the understanding that it will be digested into individual incidents based off what was learned.

**Comment by smcgregor** [comment]
Closing this since I think it was digested into new incidents.

**Comment by smcgregor** [comment]
New ** issues **, not incident. whoops. 😵‍💫
