### ISSUE TITLE
 Hotpoints Discussion - Complain-athon - summary

### ISSUE THREAD

**Issue by cesarvarela** [responsible-ai-collaborative/aiid#903]
## submit form
-  is too complex
- alleged * fields would make things worse (start collapsed?) (also improve description popover) 
- author CSV could use the Tag component
- preloaded filler images for reports to make submitting reports easier/prettier 

## citation pages
- create reusable card components for reports and incidents

## landing page
- discover/submit buttons don't really look like buttons
- is this a documentation site?
- show a single row of the discover app above the fold (add a featured field to the incident's schema, editable through form)
- navigation should make a better separation of docs vs product 
 
## forms
- inconsistent UI/UX

## overall UI
- improvements on styling, make it clear what's what  (underline links,  shadow in buttons, etc.),

## wikification
- signups
- login
- profile page
- subscribe to updates

## incidents app
 - rough edges
 - improve spinner
 - overflowing scroll
 
## growth
- optimize for traffic
- comments
- subscribe to updates

**Comment by smcgregor** [comment]
Adding management of this issue to the backlog -- these need to be digested into individual issues and associated with a design/UX `initiative`.

**Comment by lmcnulty** [comment]
I've converted all of these into individual issues except those under Wikification and Growth, which I think others could address in issues more usefully.

**Comment by lmcnulty** [comment]
I think most of the wikification and growth tasks are underway, so I'm closing this.
