### ISSUE TITLE
Forgot to assign incident ID, resulted in incident duplicate

### ISSUE THREAD

**Issue by LKchemposer** [responsible-ai-collaborative/aiid#907]
I forgot to assign an `incident id` to a report that belonged to [incident 268](https://incidentdatabase.ai/cite/268), resulting in a falsely new [incident 269](https://incidentdatabase.ai/cite/269).

- [x] Manually add the report in incident 269 to incident 268
- [ ] Remove report in incident 269

**Comment by LKchemposer** [comment]
I was not able to manually add the report to 268, submitting the form gives the following error, despite all the necessary fields filled in:

> Was not able to create the report, please review the form and try again.

Is there an automated duplicate detection?

**Comment by smcgregor** [comment]
Done updating to add the duplicate record to the database. @LKchemposer here is the report to add to 268:

https://www.hrw.org/report/2020/09/10/video-unavailable/social-media-platforms-remove-evidence-war-crimes

**Comment by LKchemposer** [comment]
adding report to incident 268, done

**Comment by kepae** [comment]
Looks done to me. :-)
