### ISSUE TITLE
Review queue report update broken

### ISSUE THREAD

**Issue by LKchemposer** [responsible-ai-collaborative/aiid#909]
Candidate report `Dutch scandal serves as a warning for Europe over risks of using algorithms` in the review queue was not able to be updated, with the returned error:

> Error updating submission 62eba91b1aa91bf2a3ba0f67

![image](https://user-images.githubusercontent.com/39468345/183239707-1ac8df97-c917-41d8-9264-ac2de622490a.png)

**Comment by cesarvarela** [comment]
Does this happen on other submissions too?

**Comment by LKchemposer** [comment]
Ah, it has to do with the "Related" feature, as I found out. If I don't use the feature (i.e., everything `?`) then it is updated, otherwise, it runs into the error.

**Comment by cesarvarela** [comment]
assigning this to Luna since she's already working on it

**Comment by lmcnulty** [comment]
It looks like this has the same cause as #908 and will by fixed by https://github.com/responsible-ai-collaborative/aiid/pull/894.

**Comment by lmcnulty** [comment]
This is solved my #894 now in staging, so I'm closing this for now.
