### ISSUE TITLE
Translation Deployment Issues

### ISSUE THREAD

**Issue by smcgregor** [responsible-ai-collaborative/aiid#917]
WIP, I am still reviewing the functionality.

These are the issues associated with the translation feature.

# Blocking publication deployment

None

# High priority changes

* [x] The badge indicating something is translated by AI should link to the blog post
* [x] This menu is not localized. I think the English should also read: "View the original report at its source" and "View the report at the internet archive"
<img width="803" alt="Screen Shot 2022-08-10 at 12 09 54 PM" src="https://user-images.githubusercontent.com/64780/183998516-c6ad0243-976e-4436-bb21-572c5a401608.png">

* [x] There are some bad links in this list: https://staging-aiid.netlify.app/es/about_apps/
* [x] We should blur the offensive image of the blog post unless someone clicks it
* [x] Update the announcement blog post date to the 11th
* [ ] We want to be indexed in search engines in Spanish properly. I don't know what is involved here, but we need to look into it.
* [x] `Did our AI mess up? Flag  the unrelated incidents` Does not provide an obvious location to flag the non-related incidents.
* [x] Link in the question mark is not localized
<img width="444" alt="Screen Shot 2022-08-10 at 1 35 56 PM" src="https://user-images.githubusercontent.com/64780/184015143-fae9e029-cdad-4532-bce0-938e0cc93b5a.png">

* [x] Discover application has unused language selection parameter. For example, https://incidentdatabase.ai/es/apps/discover/?display=details&lang=en&page=1
* [ ] The instructions that pop up when you hover on the question mark of the submit form at currently always in English
* [ ] Toasts, like the one that pops up with submitting a report, have some non-localized links.

**Comment by smcgregor** [comment]
Hello @cesarvarela @lmcnulty @clari182 @pdcp1 , plugging back in for a short bit to get the translation feature out. I am reviewing the functionality now and creating a backlog associated with it. So far none of the issues are blocking rollout, but they will need to be addressed in short order. Please divide and conquer!

I'll edit the issue as I encounter hot points.

**Comment by cesarvarela** [comment]
@smcgregor you mean everywhere the badge is present it should link to the blog post? or only in the citation page?

If there is nothing particularly complex I can tackle them all

**Comment by smcgregor** [comment]
So far, only tweaks. I am going to get the deployment out in a moment so we can do the last changes in staging.

**Comment by LKchemposer** [comment]
small UI issue, where the `X` and the magnifying glass icon of the search bar are on top of the dropdown menu for language change.

<img width="421" alt="image" src="https://user-images.githubusercontent.com/39468345/184076509-7bebd3fa-f37a-45ab-8efa-541e9c7666c9.png">

**Comment by pdcp1** [comment]
@LKchemposer I will take a look at that one.

**Comment by cesarvarela** [comment]
Everything mentioned here is either fixed or ina separate issue
