### ISSUE TITLE
Design/Implement SEO strategy

### ISSUE THREAD

**Issue by cesarvarela** [responsible-ai-collaborative/aiid#935]
from #917

**Comment by smcgregor** [comment]
Let's limit this one to ensuring we are properly indexed in French and Spanish search.

**Comment by smcgregor** [comment]
@cesarvarela adding you here since you have been working this already.

**Comment by cesarvarela** [comment]
- canonical tests fixed
- alternate links fixed
- trailing slashes consistency has been added
