### ISSUE TITLE
The flagged incident list uses colons instead of table columns

### ISSUE THREAD

**Issue by lmcnulty** [responsible-ai-collaborative/aiid#941]
![colon-as-table](https://user-images.githubusercontent.com/25443411/184681006-7691ca90-b539-4891-8f01-3af675fa65dc.png)

**Comment by clari182** [comment]
Hey @lmcnulty looks good on desktop however on lower resolutions the table goes out of the main layout
<img width="832" alt="image" src="https://user-images.githubusercontent.com/4105289/187471262-b94ceffd-15d4-472c-9661-b8f9385d03d6.png">
<img width="439" alt="image" src="https://user-images.githubusercontent.com/4105289/187472900-c93e51ac-09cb-4997-98dc-c40393ea3480.png">
