### ISSUE TITLE
Tailwind future fixes

### ISSUE THREAD

**Issue by clari182** [responsible-ai-collaborative/aiid#947]
Once tailwind is live we need to address several fixes regarding screen sizing.
Right now there are several screen sizing used in different places that are not consistent.
We are using max-width in several places, and should only use min-width, if possible always use tailwind default breakpoints.
- Use tailwind default [screen sizing ](https://tailwindcss.com/docs/responsive-design)
- Only use min-width and not max-width -> convert classes to use mobile-first approach

**Comment by smcgregor** [comment]
We are opportunistically changing over to Tailwind across the site, so closing this as a tracking issue.
