### ISSUE TITLE
Non-English to English Report Titles Not Displayed

### ISSUE THREAD

**Issue by smcgregor** [responsible-ai-collaborative/aiid#949]
Found here: https://incidentdatabase.ai/cite/184#r6286836de0eed158517c5def

See below.

<img width="1442" alt="Screen Shot 2022-08-17 at 8 18 45 AM" src="https://user-images.githubusercontent.com/64780/185177838-7c2eb916-deee-4871-b809-fbb42e2c8ebd.png">

**Comment by smcgregor** [comment]
@cesarvarela @lmcnulty @clari182 @pdcp1 can one of you claim this one?

**Comment by cesarvarela** [comment]
![image](https://user-images.githubusercontent.com/1172479/185192410-bc641f3c-a101-4913-8e6a-a1b4912d22bd.png)

**Comment by cesarvarela** [comment]
@smcgregor what should we do here? 

This doesn't work because we don't translate from French yet. Only Spanish will work.

**Comment by cesarvarela** [comment]
![image](https://user-images.githubusercontent.com/1172479/185261384-e45feb32-4488-466b-b0e7-0a1fbd6c329f.png)
