### ISSUE TITLE
Report with empty values

### ISSUE THREAD

**Issue by cesarvarela** [responsible-ai-collaborative/aiid#952]
Not sure how this happened bug this breaks the build:

![image](https://user-images.githubusercontent.com/1172479/185209914-d5ab89d0-915c-415b-acda-17834ebc261f.png)

(I manually fixed it on staging)

**Comment by smcgregor** [comment]
What was breaking and what did you fix here?

**Comment by cesarvarela** [comment]
I just added a "Anonymous" to the submitter list

**Comment by smcgregor** [comment]
Closing since I deleted this report entirely from production. @LKchemposer will re-add it.

**Comment by LKchemposer** [comment]
report re-added
