### ISSUE TITLE
Fix Netlify build on developer's environment

### ISSUE THREAD

**Issue by pdcp1** [responsible-ai-collaborative/aiid#953]
Netlify build is failing for an unknown reason in each developer environment.
Here is an example of [Pablo's Netlify environment build](https://app.netlify.com/sites/pablo-staging-aiid/deploys/62fd343b718a2c005d76791c).

```
Error message
2:44:13 PM:   Command was killed with SIGKILL (Forced termination): gatsby build --verbose
```

This was reported by Cesar on [Netlify Support forum](https://answers.netlify.com/t/command-was-killed-with-sigkill-forced-termination-gatsby-build/73532). No answer yet.

<img width="830" alt="image" src="https://user-images.githubusercontent.com/6564809/185213096-85ce1a29-f60d-48e1-aa55-7e0122461814.png">

**Comment by smcgregor** [comment]
Running `gatsby build --verbose` is working on your local machine?

**Comment by pdcp1** [comment]
Yes, it's working on our local machines. It's also working on [Staging](https://app.netlify.com/sites/staging-aiid/deploys/62fd2d313c54ce007debc29c).
It fails on my [Netlify](https://app.netlify.com/sites/pablo-staging-aiid/deploys/62fd343b718a2c005d76791c)

I added the `--verbose` flag to get more info, but the error message is the same, it doesn't help.

It looks like it's something related to the bundles, this [post](https://answers.netlify.com/t/gatsby-deploy-returns-sigkill-it-works-locally/37708/3) talks about issues with large images or large files. I will keep investigating.

**Comment by smcgregor** [comment]
I think this may be a good opportunity for me to migrate the production Netlify from the legacy org to the new Netlify org. It is worth checking the environment variables in this to ensure there is no unreasonable variation between staging and production, for example, we specify the node version.

**Comment by cesarvarela** [comment]
I've tracked this error to this page: 

![image](https://user-images.githubusercontent.com/1172479/185235351-c7f55a5f-1d0f-436a-ba3e-b0147b3e9218.png)

now I'm testing what of that is exactly causing this

**Comment by cesarvarela** [comment]
Fixed in staging
