### ISSUE TITLE
Failing Build

### ISSUE THREAD

**Issue by cesarvarela** [responsible-ai-collaborative/aiid#958]
One of the reports linked to incident `268` is missing `submitters`:

![image](https://user-images.githubusercontent.com/1172479/185234065-cd89f34e-6552-4608-94cb-aa32d72c0812.png)

![image](https://user-images.githubusercontent.com/1172479/185234103-4451ec04-a6df-497e-96a3-a245df314a25.png)

**Comment by smcgregor** [comment]
I'm not seeing this in the backend, is this only on staging?

**Comment by cesarvarela** [comment]
It is fixed
