### ISSUE TITLE
Word counts page layout

### ISSUE THREAD

**Issue by lmcnulty** [responsible-ai-collaborative/aiid#967]
The word clouds on the word counts page are small and separated by a lot of space. The table is also very tall.

https://user-images.githubusercontent.com/25443411/185461149-ce4fee3e-beef-4361-9a75-b1d9bb46d279.mp4

I think it would look better if we made the word cloud take up the full width, and the table appeared after it, possibly with its own scrollbar. Rather than having separate word clouds, we should have a slider that allows the user to exclude the top N words.

**Comment by smcgregor** [comment]
This is done.
