### ISSUE TITLE
Feature suggestion - filter incidents by language of the report

### ISSUE THREAD

**Issue by LKchemposer** [responsible-ai-collaborative/aiid#986]
User stories:

- "I want to see all reports that were written in Vietnamese (or Spanish, or French)"
- @Janetbananet: "I want to search the database according to [a report's] country of origin"

Potential solution: add in the filter search the language of the original report

**Comment by smcgregor** [comment]
Let's keep the search in English, French, and Spanish for now, but filtering according to the report's original language sounds good to me.
