### ISSUE TITLE
Spinners

### ISSUE THREAD

**Issue by lmcnulty** [responsible-ai-collaborative/aiid#995]
In some places we use fairly small spinners when loading large elements. 

<img width="400" src="https://user-images.githubusercontent.com/25443411/186015276-4aa4e6bc-67da-4313-94ea-829201e136dc.png"/>

I think we should shift towards using [skeletons](https://flowbite.com/docs/components/skeleton/) as we adopt Flowbite.

**Comment by pdcp1** [comment]
This was addressed on this PR https://github.com/responsible-ai-collaborative/aiid/pull/1062

**Comment by cesarvarela** [comment]
I think that PR looks better (it is merged) but still the loader is a small blue thing in the middle of a white ocean. 

+1  skeletons.

**Comment by pdcp1** [comment]
If the spinner is to small, we can change the size of the `flowbite-react` Spinner to one of the supported sizes:
`'xs' | 'sm' | 'md' | 'lg' | 'xl'>`
