### ISSUE TITLE
Related selector bug

### ISSUE THREAD

**Issue by LKchemposer** [responsible-ai-collaborative/aiid#998]
![Screen Recording 2022-08-23 at 3 14 14 PM](https://user-images.githubusercontent.com/39468345/186109401-e22c3d42-afbc-4e9e-8b7c-065987032804.gif)

Also, there seems to be a duplicate in the list: two "Machine Bias - ProPublica."

**Comment by lmcnulty** [comment]
I don't think this occurs anymore. We can re-open if it does.
