### ISSUE TITLE
Tailwind list link style

### ISSUE THREAD

**Issue by lmcnulty** [responsible-ai-collaborative/aiid#999]
In `tailwind.css`, [we currently have](https://github.com/responsible-ai-collaborative/aiid/blob/staging/site/gatsby-site/src/tailwind.css#L15) the following rule:

```css
.tw-layout li a {
    @apply tw-text-black;
}
```

I'm not sure what this was intended for, but it's probably too general. Right now it makes the links in [/summaries/incidents](https://staging-aiid.netlify.app/summaries/incidents/) has to identify as such.

<img src="https://user-images.githubusercontent.com/25443411/186202317-51bb6754-b830-4807-8452-06aa19703d47.png" height="300"/>

There's the same problem when links appear in lists in textual pages, like in [/taxonomies](https://staging-aiid.netlify.app/taxonomies).

<img height="200" src="https://user-images.githubusercontent.com/25443411/186204900-c437e841-9bb4-44f4-807c-b417ff7f5215.png">

Tagging @clari182 because this is a tailwind issue.

**Comment by clari182** [comment]
@lmcnulty not intentional, I'll fix this on my next tailwind PR!
